### ISSUE TITLE
microprofile-openapi @Extension is missing in /openapi.yml model

### ISSUE THREAD

**Issue by dvddhln** [smallrye/smallrye-open-api#10]
Hi,
Here is from previous discussion: https://github.com/thorntail/thorntail/issues/1044

Currently the `@Extensions` on jax-rs methods are not being read, thus not adding it to the /openapi.yml model.

/david

**Comment by EricWittmann** [comment]
We need some code in `processJaxRsMethod` to read `@Extensions` if present:

https://github.com/smallrye/smallrye-open-api/blob/master/implementation/src/main/java/io/smallrye/openapi/runtime/scanner/OpenApiAnnotationScanner.java#L363-L666

**Comment by EricWittmann** [comment]
@msavy any interest in tackling this?

**Comment by EricWittmann** [comment]
@kenfinnigan @msavy @dvddhln Have a look at this PR: https://github.com/smallrye/smallrye-open-api/pull/12
