### ISSUE TITLE
Add support for @JsonView annotations

### ISSUE THREAD

**Issue by maliffi** [smallrye/smallrye-open-api#1008]
Hello,
I've seen that Swagger already support the usage of anootation `@JsonView` in order to filter input and output of a model class in RequestBody or ResponseBody (see https://github.com/swagger-api/swagger-core/issues/479 fixed with https://github.com/swagger-api/swagger-core/pull/2681 since 2018), but If I try using this annotation in my controller in order to selectively hide some fields of my model class from input or output in the swagger-ui, they are anyway displayed.
This is my example

```java
    @JsonView(RestViews.ViewAdmin.class)
    public CompletionStage<FilterRest> saveFilter(
            @Valid @JsonView(RestViews.Save.class) @ConvertGroup(to = ValidationGroups.Save.class) FilterRest filterRest) {
    }
```
My model class is:
```java
public class FilterRest {

    @JsonView({RestViews.Update.class, RestViews.ViewUser.class})
    @Null(groups = {ValidationGroups.Create.class})
    private String id;

    @JsonView({RestViews.Create.class, RestViews.ViewAdmin.class})
    @NotNull
    private Set<String> countryValidity;
```
Event the field `id` is marked with a different JsonView actually is showed in swagger-ui for the request in the API.

What am I doing wrong?

**Comment by phillip-kruger** [comment]
SmallRye OpenAPI is primarily a microprofile open API implementation. We do not support (yet) swagger annotations, although there is an open issue to add support for it. Once that is done we can look at supporting this

**Comment by mschorsch** [comment]
`JsonView` is a jackson annotation not a swagger annotation.

**Comment by mschorsch** [comment]
@phillip-kruger Is there a chance that this feature will be implemented in the near future?

JsonView support is very important for us, because we must generate different OpenAPI specifications from the same Rest-Api.

**Comment by MikeEdgar** [comment]
@maliffi , @mschorsch - based on the example in this issue, would you expect the `FilterRest` bean to result in 6 different schemas?

- FilterRest
- FilterRest_ViewAdmin
- FilterRest_Save
- FilterRest_Update
- FilterRest_ViewUser
- FilterRest_Create

**Comment by mschorsch** [comment]
Yes. It would be nice if i could choose (config flag?) which JsonView(s) should be generated.

**Comment by maliffi** [comment]
> yo

Yes, this is what I would expect to see in the `Schemas` section of swagger.
At the same time, the example autogenerated for each API should respect the RestView used to annotate the method of rest api

**Comment by maliffi** [comment]
> @maliffi , @mschorsch - based on the example in this issue, would you expect the `FilterRest` bean to result in 6 different schemas?
> 
> * FilterRest
> * FilterRest_ViewAdmin
> * FilterRest_Save
> * FilterRest_Update
> * FilterRest_ViewUser
> * FilterRest_Create

Yes, this is what I would expect to see in the `Schemas` section of swagger.
At the same time, the example autogenerated for each API should respect the RestView used to annotate the method of rest api

**Comment by mschorsch** [comment]
@MikeEdgar Do you know wegen this feature will be available? This issue prevents us from using smallrye-openapi in quarkus and is a blocker for our migration to resteasy-reactive in one of our projects.

**Comment by MikeEdgar** [comment]
@mschorsch I haven't had a chance to think about a solution for this one yet, but I hope to find some time soon.

**Comment by sandronm** [comment]
Don't want to put pressure on anybody but this feature will also be nice for our current developments.
I hope this will become a reality some day ;-)

Already thank you for your all work!

**Comment by antssilva96** [comment]
I'm in the same situation as @mschorsch, this is blocking the use of `quarkus-smallrye-openapi`.
