### ISSUE TITLE
Support for Any schema

### ISSUE THREAD

**Issue by sclorng** [smallrye/smallrye-open-api#1022]
Currently if we expose an object, the schema is

```
@Schema(description = "The value of the characteristic", required = true)
public Object getValue() {
    return value;
}
```
gives

```
value:
    description: The value of the characteristic
    type: object
```

Is it possible to not have the type attribute or just `{}` when no other attribute are present to express an Any schema ?

`io.smallrye:smallrye-open-api-core:jar:2.1.17`

**Comment by MikeEdgar** [comment]
@sclorng - you should be able to set the `type` to `null` with an `org.eclipse.microprofile.openapi.OASFilter` implementation. The model that results from the annotation scan would be made available for modification.

**Comment by MikeEdgar** [comment]
This should be supported, reference https://swagger.io/docs/specification/data-models/data-types/#any

**Comment by MikeEdgar** [comment]
@sclorng , you should be able to accomplish this by setting the following property:
`mp.openapi.schema.java.lang.Object={ "name": "AnyType" }`

This will result in something like:
```json
{
  "openapi" : "3.0.3",
  "components" : {
    "schemas" : {
      "TestBean" : {
        "type" : "object",
        "properties" : {
          "any" : {
            "$ref" : "#/components/schemas/AnyType"
          }
        }
      },
      "AnyType" : {}
    }
  }
}
```
