### ISSUE TITLE
Complex type properties with description are described with allOf

### ISSUE THREAD

**Issue by sclorng** [smallrye/smallrye-open-api#1023]
Given the following property

```
@Schema(description = "a description")
@JsonProperty("foo")
ComplexType getFoo();
```

the generated schema is

```
foo:
    allOf:
        - $ref: '#/components/schemas/ComplexType'
        - description: a description
 ```

I'm expecting to get

```
foo:
    description: a description
    $ref: '#/components/schemas/ComplexType'
 ```

`io.smallrye:smallrye-open-api-core:jar:2.1.17`

**Comment by scrocquesel** [comment]
I provide a repro test here https://github.com/scrocquesel/smallrye-open-api/commit/f4e2c0529c93a122ed33b9172e34e1a8c74c8bbf

**Comment by MikeEdgar** [comment]
@sclorng , @scrocquesel - the reason for the `allOf` is that `$ref` is mutually exclusive of other properties. See the section from the OpenAPI 3.0.3 spec regarding schema: https://swagger.io/specification/#schema-object

> Alternatively, any time a Schema Object can be used, a Reference Object can be used in its place. This allows referencing definitions instead of defining them inline.

What this means is that you can either have a schema _or_ a $ref (which is actually a Reference object, distinct from a schema).

**Comment by scrocquesel** [comment]
In the given link, look for Models with Polymorphism Support section. there is a sample :

```yaml
components:
  schemas:
    Pet:
      type: object
      discriminator:
        propertyName: petType
      properties:
        name:
          type: string
        petType:
          type: string
      required:
      - name
      - petType
    Cat:  ## "Cat" will be used as the discriminator value
      description: A representation of a cat
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        properties:
          huntingSkill:
            type: string
            description: The measured skill for hunting
            enum:
            - clueless
            - lazy
            - adventurous
            - aggressive
        required:
        - huntingSkill
    Dog:  ## "Dog" will be used as the discriminator value
      description: A representation of a dog
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        properties:
          packSize:
            type: integer
            format: int32
            description: the size of the pack the dog is from
            default: 0
            minimum: 0
        required:
        - packSize
```

**Comment by scrocquesel** [comment]
Oh right, I found the explanation here https://swagger.io/docs/specification/using-ref#sibling. Not so Json schema pitfall, I guess.

Nevertheless, shouldn't it be 

```
foo:
    description: a description
    allOf:
        - $ref: '#/components/schemas/ComplexType'
```

or, if I understand the philosophy, as the description describes the schema itself not the property. Then, description should simply be ignored (or merged on the target schema)

```
  ...
    foo:
        $ref: '#/components/schemas/ComplexType'
...
components:
   schemas:
      ComplexType:
          description: a description
          ...
```

In this case, I guess I should just omit the description on the annotation.

**Comment by MikeEdgar** [comment]
@scrocquesel - the `description` should apply to the property along with the schema referenced (a union of the two). In this example, the definition says "the schema of property `foo` is a combination of `'#/components/schemas/ComplexType'` and `description: a description`". At least that is my interpretation of `allOf` [1]

[1] https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

**Comment by phillip-kruger** [comment]
Agree, the description is for the property. If you need a description on the ComplexType then the type should contain that annotation. So I agree with the above output. (it describes foo).

**Comment by MikeEdgar** [comment]
I'm looking into a fix to keep local property properties/constraints outside of the `allOf`. Also, if the scanner detects a conflict between a local constraint and the referenced schema in the `allOf`, I think it needs to in-line the referenced schema instead and overlay the locally-overridden constraint.

**Comment by rvansa** [comment]
I just stumbled upon a similar issue, where 
```
@NotNull
public Access access
```
results in 
```
access:
  allOf:
          - $ref: '#/components/schemas/Access'
          - nullable: false
```
Naturally I don't want to remove the `@NotNull` as it is used for other validations. And for some reason when I process the generated document with `openapi-generator` to create Typescript API this results in
```
access: Access | null
```
