### ISSUE TITLE
NPE when @Produces is missing

### ISSUE THREAD

**Issue by silviu-negoita** [smallrye/smallrye-open-api#1026]
### Code to follow for reproducing the issue

1. `ResponseReader.addApiReponseSchemaFromAnnotation`:
```
APIResponse response = ResponseReader.readResponseSchema(context, annotation);

if (response.getDescription() == null) {
    response.setDescription(getReasonPhrase(status));
}
```
2. `ResponseReader.readResponseSchema`:

```
if (annotation == null || CurrentScannerInfo.getCurrentProduces() == null) {
    // Only generate the APIResponse if the endpoint declares an @Produces media type
    return null;
}
```

When `@Produces` is missing on the scanned method, it will raise the most known java exception: `NPE` 

Also, we are using @APIResponseSchema to specify the schema for a certain method, because we work with `javax.ws.rs.core.Response`. Maybe an enhancement is to prioritize it before returning null in method no 2 from above.

### Bonus maybe irelevent bug
Rename addApi**Reponse**SchemaFromAnnotation -> addApi**Response**SchemaFromAnnotation

### Env
* `quarkus` - 2.6.1
* `quarkus-smallrye-openapi1` - 2.6.1

**Comment by MikeEdgar** [comment]
@silviu-negoita - do you have a stack trace or a simple app you could share that demonstrates the problem?
