### ISSUE TITLE
Supplement schema restrictions using Bean Validation annotations, if present

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#103]
Add constraint information to field-level schemas when Bean Validation annotations are available and when the information is not already specified in the `@Schema` annotation.

**Comment by EricWittmann** [comment]
So this mean looking for e.g. `@NotNull` and whatnot and including that information in the generated OpenAPI schema, yes?

**Comment by MikeEdgar** [comment]
@EricWittmann , that's right. This would help keep application code a bit DRYer. :)

**Comment by MikeEdgar** [comment]
I have a branch ready for this change, but depending on what happens with #99 I may need to do a rebase due a small overlap with how the BV constraints are scanned and the changes in 99. If this change is better incorporated first, I'll go ahead and open the PR.

**Comment by EricWittmann** [comment]
Apologies - I dropped the ball on merging #99.  Done now.

**Comment by ChMThiel** [comment]
@MikeEdgar [Composite Constraints](https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#section-constraint-composition) are not evaluated for now, aren't they? Is that worth an issue?

**Comment by MikeEdgar** [comment]
@ChMThiel support for annotation composition was actually just added in #1684 and will be included in release 3.8 soon. Note that the current implementation does not currently support any `jakarta.validation.OverridesAttribute` annotations that may be present in the composing annotation.

**Comment by MikeEdgar** [comment]
@nimo23 they should be scanned automatically. `@Email` isn't one of the supported annotations, but `@NotBlank` should work.

**Comment by MikeEdgar** [comment]
It's part of the MicroProfile OpenAPI spec: https://download.eclipse.org/microprofile/microprofile-open-api-4.0.2/microprofile-openapi-spec-4.0.2.html#_jakarta_bean_validation_annotations
