### ISSUE TITLE
microprofile-open-api 3.0

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#1042]
@radcortez, I think you've started something for this in the `jakarta` branch, right?

**Comment by radcortez** [comment]
Yes. Everything should be done there.

The strategy is not to merge new changes there. We just redo the migration again, until we move this to `main`. I have a script for this. I'll push it to the repo.

**Comment by radcortez** [comment]
Ok, this should handle the migration:
https://github.com/smallrye/smallrye-open-api/blob/main/to-jakarta.sh

What I'm doing is resetting the `jakarta` branch with `main` and applying the migration again. I'm going to do an RC release of the current one.

**Comment by MikeEdgar** [comment]
@radcortez any concerns if I periodically reset and run the migration on `jakarta`? I'm using that branch as a base to verify MP 3.1 TCK changes (the _next_ release) so I'd like to keep it as current with `main` as possible.
