### ISSUE TITLE
@Deprecated is not being reflected in openapi definition

### ISSUE THREAD

**Issue by Postremus** [smallrye/smallrye-open-api#1049]
I used the `@java.langDeprecated` annotation on a resource method.
I expected the resource method to be marked as deprecated in swagger-ui, but it is not.

With `@Operation(deprecated = true)` however, the resorce methos is marked as deprecated.

To reproduce:
1. Download the reproducer: [openapi-deprecations.zip](https://github.com/smallrye/smallrye-open-api/files/8047470/openapi-deprecations.zip)
2. mvn quarkus:dev
3. Visit http://localhost:8080/q/swagger-ui
4. The /hello path is marked as deprecated
5. Now remove the `@Operation` from `GreetingResource#hello`. The method still has a `@java.langDeprecated` annotation.
6. Reload the page
7. The /hello path is not marked as deprecated anymore.

**Comment by MikeEdgar** [comment]
Looks like `@Deprecated` is only checked for parameters. This should be expanded to operations and schemas (at least).
