### ISSUE TITLE
Enum fields are included in schema

### ISSUE THREAD

**Issue by jannispl** [smallrye/smallrye-open-api#106]
I am trying to generate schema for an Enum type:
```
public enum JobState {
    DONE,
    FAILED,
    PROCESSING(FAILED, DONE),
    QUEUED(PROCESSING);

    private final JobState[] targetStates;

    JobState(final JobState... targetStates) {
        this.targetStates = targetStates;
    }
    ...
}
```

Unfortunately, currently this results in the `targetStates` field being included in the enumeration of the schema:

```
              state:
                enum:
                - DONE
                - FAILED
                - PROCESSING
                - QUEUED
                - targetStates
                type: string
```

**Comment by MikeEdgar** [comment]
Is there any case where the fields _should_ be picked up from the enum?

**Comment by jannispl** [comment]
Personally I think there should at least be a way to have the documentation represent the actual (de-)serialization logic, as implemented by (for example) Jackson.

I am not aware of any case where enum fields are included in the serialized form by any JSON object mapper.

*If anything*, then a use case would probably be aliases defined as `static`, referring to the same enum type:
```
enum Something {
    FIRST,
    SECOND
    ;

    public static final Something ALIAS_FIRST = FIRST;
}
```
However I don't think this should be the default behavior.
