### ISSUE TITLE
Implicit default values for primitive data types

### ISSUE THREAD

**Issue by Postremus** [smallrye/smallrye-open-api#1079]
I have a parameter defined as follows:

```
    @QueryParam("onlyNewest")
    public boolean onlyNewest;
```

Since this is a primitive boolean, it defaults to false if the user did not specify ?onlyNewest=true.
The openapi documentation does not reflect this however, no defaultvalue is set for this parameter.

Ideally, Smallrye Openapi could auto generate the default values for query parameters.

Also, at least for resteasy, following assignment as `true` has no effect. In my debugger I see the onlyNewest set to false.

```
    @QueryParam("onlyNewest")
    public boolean onlyNewest = true;
```

**Comment by phillip-kruger** [comment]
@MikeEdgar - what is your thoughts ? I would rather want an explicit `@Paramter(defaultValue="true"` or something like that.

**Comment by MikeEdgar** [comment]
To make this work with both JAX-RS and the OpenAPI scanner, I think the best approach is to use `@DefaultValue` co-located with the `@QueryParam`.

**Comment by phillip-kruger** [comment]
Great. Would that work for you @Postremus ? If so you can close this issue
