### ISSUE TITLE
Provide better examples for localdatetime

### ISSUE THREAD

**Issue by Postremus** [smallrye/smallrye-open-api#1089]
For query parameters of type localdatetime and localdate should generate example values, like it is already done for localtime.

For the request body, the example localdatetime should be without 'Z' - e.g. '2022-03-10T16:15:50.487' instead of '2022-03-10T16:15:50.487Z'

I have following resource:
```
    @GET
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.TEXT_PLAIN)
    public SomeData hello(@BeanParam SomeBeanParam object) {
        return new SomeData();
    }

    public static class SomeBeanParam {
        @RestQuery
        public LocalDate date;

        @RestQuery
        public LocalTime localTime;

        @RestQuery
        public LocalDateTime localDateTime;
    }

    public static class SomeData {
        public LocalDate date;

        public LocalTime localTime;

        public LocalDateTime localDateTime;
    }
```

Swagger-ui:
![image](https://user-images.githubusercontent.com/1223135/157707712-4ec91b57-069f-4b8d-9e6b-f925aef0bfa8.png)

example quarkus project: 
[sm-openapi-localdate.zip](https://github.com/smallrye/smallrye-open-api/files/8225188/sm-openapi-localdate.zip)

**Comment by phillip-kruger** [comment]
PRs welcome :)
