### ISSUE TITLE
How to read all Examples and add it to the @ExampleObject without specifying the ref so its visible in SwaggerUI

### ISSUE THREAD

**Issue by Aravinda93** [smallrye/smallrye-open-api#1133]
I am developing a simple application where I would like to read the files from a remote URL and add them to the `@ExampleObject`. I am able to achieve this using CustomClass `SchemaFileReader implements OASFilter` but the only problem is that I need to manually specify the `name` of the file in the ref such as `@ExampleObject(name = "Example1", ref = "Example1.json")`.

Since I am reading the URL there can be many files and I do not know the name of all the files so I need an approach where I can add the `@ExampleObject` dynamically directly without specifying `ref`. Rather it should read all the data from the `examples`. Can someone please specify some logic on how to achieve this?

I have posted my complete code on GitHub: https://github.com/Aravinda93/code-with-quarkus.

As of now, I have added 2 files to my `@ExampleObject` but I need a dynamic approach to add all the 3 files present in the `resourses/jsonfiles` without providing the `ref` for all the files individually.

To run the application, please follow the following steps:
1. Open the terminal for the project and run `mvn compile quarkus:dev`
2. Press `d` in the command line this should open the `Swagger-UI`.
3. Select `swagger-ui` from `SmallRye OpenAPI`
4. Expand `api/generate` and there we will see only 2 files under examples. I need an approach to get all 3 field without specifying the `ref` for all of them.

**Comment by phillip-kruger** [comment]
You can build the model in that same filter and reference that ? (so no ref to remote url, just to the local models)

**Comment by Aravinda93** [comment]
@phillip-kruger Thanks a lot for your response. Sorry,  i am unable to follow your approach completely. If possible can you please explain bit more in detail or provide a small example?

I got to know that I need to create model in "SchemaFileReader implements OASFilter" but could not understand what model and how to reference it.

@phillip-kruger Thanks a lot in advance.

**Comment by phillip-kruger** [comment]
Hi  @Aravinda93 - I checked out your example and it seems to already work as I suggested ? Everything seems fine to me ?? What is the issue ?

Here is the OpenAPI schema document I get:

```
---
openapi: 3.0.3
info:
  title: code-with-quarkus API
  version: 1.0.0-SNAPSHOT
paths:
  /api/generate:
    post:
      tags:
      - Rest Controller Response
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: object
            examples:
              Example1:
                $ref: '#/components/examples/Example1.json'
              Example2:
                $ref: '#/components/examples/Example2.json'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  examples:
    Example1.json:
      value:
        fruit: Apple
        size: Large
        color: Red
    Example2.json:
      value:
        quiz:
          sport:
            q1:
              question: Which one is correct team name in NBA?
              options:
              - New York Bulls
              - Los Angeles Kings
              - Golden State Warriros
              - Huston Rocket
              answer: Huston Rocket
          maths:
            q1:
              question: 5 + 7 = ?
              options:
              - "10"
              - "11"
              - "12"
              - "13"
              answer: "12"
            q2:
              question: 12 - 8 = ?
              options:
              - "1"
              - "2"
              - "3"
              - "4"
              answer: "4"
    Example3.json:
      value:
        firstName: Rack
        lastName: Jackon
        gender: man
        age: 24
        address:
          streetAddress: "126"
          city: San Jone
          state: CA
          postalCode: "394221"
        phoneNumbers:
        - type: home
          number: "7383627627"

```

As you can see everything seems ok there. In swagger-ui you can also see the examples:

![image](https://user-images.githubusercontent.com/6836179/165195291-58643c35-3e24-4903-b718-2984a84494e1.png)
![image](https://user-images.githubusercontent.com/6836179/165195388-8302fc44-3401-46b7-b38c-10f6955d91a7.png)

**Comment by MikeEdgar** [comment]
@Aravinda93 do you still have any questions or concerns on this issue?

**Comment by Aravinda93** [comment]
@MikeEdgar Thanks a lot, I was able to find the answer here: https://stackoverflow.com/q/71964917/7584240
