### ISSUE TITLE
Missing path parameters for JAX-RS subresources declared in locator's `@Path`

### ISSUE THREAD

**Issue by grossws** [smallrye/smallrye-open-api#1155]
When JAX-RS subresource locator use `@Path("some/{id}")` SmallRye OpenAPI doesn't produce relevant parameters in operations in that subresource.

Partial workaround: add `@Parameter(name = "id", in = ParameterIn.PATH, required = true)` to subresource locator. 
But it helps only with methods in the same subresource (without additional `@Path` annotations) like `SubSubResource#getAll` below but not for `SubSubResource#get`.

Env: 
* OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
* SmallRye OpenAPI 2.1.22
* Quarkus 2.9.0.Final with `quarkus-resteasy-reactive-jackson` & `quarkus-smallrye-openapi`

See also https://quarkusio.zulipchat.com/#narrow/stream/294206-smallrye/topic/openapi.20swagger/near/285851533

```
@ApplicationScoped 
@Path("v1") 
@Produces(TEXT_PLAIN)
public class ApiV1 {
  @Inject 
  SubResource sub;

  @Path("a") 
  public SubResource sub() { return sub; }
}

@ApplicationScoped
public class SubResource {
  @Inject 
  SubSubResource subsub;

  @GET 
  @Path("{subId}") 
  public String sub(@PathParam("subId") String subId) { return subId; }

  @Path("{subId}/b") 
  // @Parameter(name = "subId", in = ParameterIn.PATH, required = true)
  public SubSubResource subsub() { return subsub; }
}

@RequestScoped
public class SubSubResource {
  @GET
  public String getAll(@PathParam("subId") String subId) { return subId + "/*"; }

  @GET 
  @Path("{subsubId}") 
  public String get(@PathParam("subId") String subId, @PathParam("subsubId") String subsubId) {
    return subId + "/" + subsubId;
  }
}
```

**Comment by phillip-kruger** [comment]
@MikeEdgar any thoughts ?

**Comment by MikeEdgar** [comment]
Definitely a bug, this should work properly. I'll try to take a look this week.

**Comment by grossws** [comment]
If you need a reproducer with my env feel free to ping me

**Comment by MikeEdgar** [comment]
OpenAPI JSON for the example above. `parameters` missing for `subId` from paths `/v1/a/{subId}/b` and `/v1/a/{subId}/b/{subsubId}`. I'm looking into this...

```json
{
  "openapi" : "3.0.3",
  "paths" : {
    "/v1/a/{subId}" : {
      "get" : {
        "parameters" : [ {
          "name" : "subId",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    },
    "/v1/a/{subId}/b" : {
      "get" : {
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    },
    "/v1/a/{subId}/b/{subsubId}" : {
      "get" : {
        "parameters" : [ {
          "name" : "subsubId",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "*/*" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          }
        }
      }
    }
  }
}

```

**Comment by MikeEdgar** [comment]
@grossws I think I see the issue. The `@PathParam("subId") String subId` argument should be moved from the `SubSubResource` methods to `SubResource#subsub`. Aside from the OpenAPI issue, does it work this way with Resyeasy?

**Comment by grossws** [comment]
@MikeEdgar, yeah sample in the issue works with at least with RestEesy Reactive. I didn't add `subId` parameter to the `SubResource#subsub` locator method since I can't use it there 'cause `SubSubResource` is CDI managed bean for JAX-RS resource. I'll try to add just a dummy parameter tomorrow. IIRC adding a field with `@PathParam` in the `SubSubResource` didn't work either but I don't recall if it caused issues with Resteasy/Arc or just didn't produce anything in the SmallRye OpenAPI context.

**Comment by grossws** [comment]
With additional dummy parameter in the subresource locator produces what seems to be correct schema:

```java
@Path("{subId}/b")
public SubSubResource subsub(@PathParam("subId") String subId) { return subsub; }
```

```yaml
---
openapi: 3.0.3
info:
  title: code-with-quarkus API
  version: 1.0.0-SNAPSHOT
paths:
  /v1/a/{subId}:
    get:
      tags:
      - Sub Resource
      parameters:
      - name: subId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /v1/a/{subId}/b:
    get:
      tags:
      - Sub Sub Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
    parameters:
    - name: subId
      in: path
      required: true
      schema:
        type: string
  /v1/a/{subId}/b/{subsubId}:
    get:
      tags:
      - Sub Sub Resource
      parameters:
      - name: subsubId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
    parameters:
    - name: subId
      in: path
      required: true
      schema:
        type: string
```

**Comment by MikeEdgar** [comment]
> With additional dummy parameter in the subresource locator SmallRye OpenAPI produces what seems to be correct schema:

At the moment, the parameter scanner only looks for a path parameter's schema associated with the method having the `@Path` annotation. Until this issue, I didn't realize the args may not be present until the subresource's endpoint method. Since this is a valid scenario, we can keep this open to update the scanner to handle this case.
