### ISSUE TITLE
Support different encoding in smallrye-open-api-maven-plugin

### ISSUE THREAD

**Issue by ColdanR** [smallrye/smallrye-open-api#1166]
Hello,
I'm currently setting up an automated documentation for OpenAPI, but on Windows 10 the plugin exports the schema files with a different encoding than UTF8. (System Default)

Looking up the code the generated documentation will be transformed to an byte array without usage of encoding.
https://github.com/smallrye/smallrye-open-api/blob/0af0bec05a1fc0c477254c161e54103ac32460f4/tools/maven-plugin/src/main/java/io/smallrye/openapi/mavenplugin/GenerateSchemaMojo.java#L431-L433

So please allow to configure encoding or use utf-8 encoding as default.

```
Charset charset = StandardCharsets.UTF_8;
if (charsetParameter != null) {
try {
    charset = Charset.forName(charsetParameter);
} catch (IllegalArgumentException e) {
    throw new MojoExecutionException("Cannot find charset for " + charsetParameter);
}
}

writeSchemaFile(directory, "yaml", yaml.getBytes(charset));
writeSchemaFile(directory, "json", json.getBytes(charset));
```

Thanks,
Bernd Schmidt

**Comment by phillip-kruger** [comment]
Hi Bernd, thanks for the issue. Are you not keen to do a PR to fix this ?

**Comment by ColdanR** [comment]
Hi Phillip,
currently I don't have the time to do so. I also didn't find any information about contributing. Would be nice, if you can add a code of conduct and contribution.md file für information.
I will try to find some time next week.
