### ISSUE TITLE
Vert.x Route not properly reflected (when regex is used, instead of path)

### ISSUE THREAD

**Issue by JapuDCret** [smallrye/smallrye-open-api#1178]
### Problem
We renamed an endpoint and therefore decided to write a URL rewriter from `/config-params/{config-param-id}` to `/v1.0/config-params/{config-param-id}`.

But then the new endpoint is not properly reflected in the OpenAPI.

### Expected behaviour
The relevant generated OpenAPI is
```json
    "/config-params/{config-param-id}" : {
    }
```

### Observed behaviour
The relevant generated OpenAPI is
```json
    "/configParamRedirector" : {
    }
```

### Current implementation
```java
@ApplicationScoped
public class ConfigParamResourceRedirector {
    @Route(regex = "\\/config-param\\/[^\\/]+\\/", methods = Route.HttpMethod.GET)
    void configParamRedirector(RoutingContext rc) {
        String uri = rc.request().uri();

        String remaining = uri.substring("/config-param/".length());

        rc.reroute("/v1.0/config-param/" + remaining);
    }
}
```

### Misc
I think the relevant code is here and it's related to me using `regex`
https://github.com/smallrye/smallrye-open-api/blob/main/extension-vertx/src/main/java/io/smallrye/openapi/vertx/VertxAnnotationScanner.java#L158-L165

**Comment by JapuDCret** [comment]
I would also be fine, if these cases can be somehow ignored, since the Schema is also not available

**Comment by MikeEdgar** [comment]
> I would also be fine, if these cases can be somehow ignored, since the Schema is also not available

@JapuDCret , try annotating the method with `@Operation(hidden = true)` to ignore it.

**Comment by JapuDCret** [comment]
> @JapuDCret , try annotating the method with `@Operation(hidden = true)` to ignore it.

thanks @MikeEdgar works like a charm :)

though I think the issue could be kept open, but I'll leave it up to you

**Comment by MikeEdgar** [comment]
I suppose the only solution for this would be to automatically hide routes with a regex.
