### ISSUE TITLE
Kotlin value classes not represented correctly.

### ISSUE THREAD

**Issue by dirkbolte** [smallrye/smallrye-open-api#1195]
When adding a kotlind value class to a response, the property name is added twice. I tried different approaches with specifying schema, but wasn't able to correct or hide the additional property.

value class:

```kotlin
@JvmInline
value class IdWithOverwrittenSchema(val value: Long)
```

Response:

```kotlin
data class TestResponse(
    @field:Schema(type = SchemaType.INTEGER, implementation = Long::class, name = "idWithOverwrittenSchema")
)
```

Resource:

```kotlin
@Path("/test")
class TestResource {
    @GET
    fun testMethod(): TestResponse {
        return TestResponse()
    }
}
```

I tried different variations and put some of them in a sample project: https://github.com/dirkbolte/openapi-test

The result looks like this:
<img width="751" alt="value_class_bug" src="https://user-images.githubusercontent.com/1572945/180982585-f19590c1-eb82-4d11-be02-a71ce1634fb8.png">

value classes as method parameters (e.g. on `@GET` with `@PathParam` do not have this issue and are parsed correctly.

Versions:
- smallrye-open-api-core: 2.1.22
- microprofile-openapi-api: 2.0.1
- Quarkus (incl. resteasy): 2.10.3.Final
- Java: 11
- Kotlin: 1.6.21

**Comment by dirkbolte** [comment]
Hit a similar issue with lazy initialisation:

```kotlin
val myId: Int by lazy { }
```

This results in an extra property: `myId$delegate` .

I also found a mitigation - not sure whether it's the desired one or not.

For lazy, the redundant property can be removed with: `@delegate:Schema(hidden = true)` . Along these lines: the original issue can be mitigated by annotating the property with: `@get:Schema(hidden = true)` .

**Comment by phillip-kruger** [comment]
Thanks @dirkbolte - This testing help a lot, we do not have Kotlin tests, and there are some cases that is specific... We will get to this a.s.a.p, but please keep them coming .

**Comment by MikeEdgar** [comment]
@dirkbolte , I've looking at the generated bytecode for the above Kotlin `TestResponse` in the test project and the problem is that Kotlin is creating accessor/getter methods that look like actual properties, but with some generated suffix. The giveaway is that these generated methods have hyphens in the name, which is not a valid Java method name. We could likely modify the scanner to ignore these since it's clear they're not user-provided. Otherwise, for the short term, you could use a filter to prune them from your OpenAPI model - shown below.

```
  // access flags 0x12
  private final LIdWithoutSchema; idWithoutSchema
  @Lorg/jetbrains/annotations/Nullable;() // invisible

  // access flags 0x11
  public final getIdWithoutSchema-_q47Reo()LIdWithoutSchema;
  @Lorg/jetbrains/annotations/Nullable;() // invisible
   L0
    LINENUMBER 10 L0
    ALOAD 0
    GETFIELD TestResponse.idWithoutSchema : LIdWithoutSchema;
    ARETURN
   L1
    LOCALVARIABLE this LTestResponse; L0 L1 0
    MAXSTACK = 1
    MAXLOCALS = 1
```

OAS Filter
```kotlin
import org.eclipse.microprofile.openapi.OASFilter
import org.eclipse.microprofile.openapi.models.media.Schema

/**
 * Configured with `mp.openapi.filter=com.example.GeneratedMethodPropertyFilter`
 */
class GeneratedMethodPropertyFilter : OASFilter {
    override fun filterSchema(schema: Schema): Schema {
        schema.properties?.entries?.removeIf { e -> e.key.contains('-')  }
        return schema;
    }
}
```

**Comment by dirkbolte** [comment]
thanks, that helps mitigating it for the whole project.
