### ISSUE TITLE
Can we Ignore the YAML dependencies available in the Project and get the JSON api doc file

### ISSUE THREAD

**Issue by abrahamp-hv** [smallrye/smallrye-open-api#1200]
Hi Team,

We are using YAML for the config files in my project. Post adding this support, we were able to download the api-docs file in YAML format only.
Is there a way to download the api docs file as a JSON file?

**Comment by phillip-kruger** [comment]
Did you try the content type header ? Or ?format=json at the end of the url ?

**Comment by abrahamp-hv** [comment]
Hi @phillip-kruger ,

?format=json worked for me. Thank for the quick reply.
