### ISSUE TITLE
Include type parameters in generated schema names

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#121]
There was some discussion on generated schema names in #97. The current implementation in the `SchemaRegistry` uses a "name + 1" approach if a name collision occurs. The collision could occur in two scenarios - 1) if the same class name exists in multiple packages or 2) if the class name is a parameterized type. 

This issue is addressing the second scenario. Consider the unit test `ExpectationWithRefsTests#testComplexNestedGenericsWithRefs` which is rooted on a field of type `Fuzz<KustomPair<Fuzz<String, Date>, ?>, Double>`. The current expected is as follows, note the sequential references to different `Fuzz` types.

```javascript
{
  "components": {
    "schemas": {
      "KustomPair": {
        "required": [
          "bar",
          "foo"
        ],
        "type": "object",
        "properties": {
          "bar": {
            "type": "object"
          },
          "foo": {
            "$ref": "#/components/schemas/Fuzz"
          }
        }
      },
      "Fuzz": {
        "maxLength": 123456,
        "type": "object",
        "properties": {
          "qAgain": {
            "format": "date",
            "type": "string"
          },
          "qAgain3": {
            "format": "date",
            "type": "string"
          },
          "qValue": {
            "format": "date",
            "description": "Ah, Q, my favourite variable!",
            "type": "string"
          },
          "tAgain2": {
            "type": "string"
          },
          "tAgain4": {
            "type": "string"
          },
          "tValue": {
            "type": "string"
          }
        }
      },
      "Fuzz1": {
        "type": "object",
        "properties": {
          "qAgain": {
            "format": "double",
            "type": "number"
          },
          "qAgain3": {
            "format": "double",
            "type": "number"
          },
          "qValue": {
            "format": "double",
            "description": "Ah, Q, my favourite variable!",
            "type": "number"
          },
          "tAgain2": {
            "$ref": "#/components/schemas/KustomPair"
          },
          "tAgain4": {
            "$ref": "#/components/schemas/KustomPair"
          },
          "tValue": {
            "$ref": "#/components/schemas/KustomPair"
          }
        }
      }
    }
  }
}
```

Using type parameters would produce a more predictable result.

```javascript
{
  "components" : {
    "schemas" : {
      "FuzzKustomPairDouble" : {
        "type" : "object",
        "properties" : {
          "qAgain" : {
            "format" : "double",
            "type" : "number"
          },
          "qAgain3" : {
            "format" : "double",
            "type" : "number"
          },
          "qValue" : {
            "format" : "double",
            "description" : "Ah, Q, my favourite variable!",
            "type" : "number"
          },
          "tAgain2" : {
            "$ref" : "#/components/schemas/KustomPairFuzzObject"
          },
          "tAgain4" : {
            "$ref" : "#/components/schemas/KustomPairFuzzObject"
          },
          "tValue" : {
            "$ref" : "#/components/schemas/KustomPairFuzzObject"
          }
        }
      },
      "KustomPairFuzzObject" : {
        "required" : [ "bar", "foo" ],
        "type" : "object",
        "properties" : {
          "bar" : {
            "type" : "object"
          },
          "foo" : {
            "$ref" : "#/components/schemas/FuzzStringDate"
          }
        }
      },
      "FuzzStringDate" : {
        "maxLength" : 123456,
        "type" : "object",
        "properties" : {
          "qAgain" : {
            "format" : "date",
            "type" : "string"
          },
          "qAgain3" : {
            "format" : "date",
            "type" : "string"
          },
          "qValue" : {
            "format" : "date",
            "description" : "Ah, Q, my favourite variable!",
            "type" : "string"
          },
          "tAgain2" : {
            "type" : "string"
          },
          "tAgain4" : {
            "type" : "string"
          },
          "tValue" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```

This is probably a less common scenario in real world applications, but it would help with unit tests in this project :-)

**Comment by EricWittmann** [comment]
Brutally honest final sentence. :)

**Comment by EricWittmann** [comment]
@msavy any thoughts?

**Comment by msavy** [comment]
Just to understand, are you saying the current behaviour is wrong, or that we shouldn't test it?

**Comment by MikeEdgar** [comment]
@msavy - I think it definitely should be tested. I don't think it's wrong either, but it is difficult to predict the results. The naming might be more easily followed by swapping the sequential suffix with the type parameters (or something else?) It's difficult to predict which occurrence of a parameterized type will be given which numeric suffix.

**Comment by EricWittmann** [comment]
Any idea how difficult is it to change how the naming works?  I haven't looked at that stuff in awhile.

**Comment by MikeEdgar** [comment]
This should be pretty simple. Right now, this line exists in `SchemaRegistry` (the `schemaName` value is what would have been provided by the client application via `@Schema`)
```java
String nameBase = schemaName != null ? schemaName : key.type.name().local();
```

It could be updated as follows:
```java
String nameBase = schemaName != null ? schemaName : typeName(key.type);

...

String typeName(Type type) {
    StringBuilder name = new StringBuilder(type.name().local());

    if (type.kind() == Type.Kind.PARAMETERIZED_TYPE) {
        for (Type param : type.asParameterizedType().arguments()) {
            name.append(param.name().local());
        }
    }

    return name.toString();
}
```

The change above keeps the sequential logic that happens afterward, but it starts out with a better chance of assigning a unique name in the case of parameterized types.

Of course, with this change there would be some collateral damage in the unit test expectations. While doing some experimentation for another feature I found that the numeric logic can be fickle and is highly dependent on order of scanning, not surprisingly.

**Comment by msavy** [comment]
Interesting idea.

I know the test cases I created are deliberately extreme, but I did it with the intention they encapsulate some of the more reasonable ones.  

Couple of thoughts:

- For the more common cases, your name-with-type suggestions could work okay.
- Are there any edge cases where it might be vague and a reference might actually be less clear (i.e. by implying something is of the same type when it is not). In those cases, perhaps we just leave it as an inline rather than reference? I'm thinking about the more difficult ? cases, or fully/partially unresolved type generics, for example.

**Comment by MikeEdgar** [comment]
I opened a PR (#122) with the changes for review. When updating the tests I found and correct an issue where `Enum` fields were not being generated when schema refs are enabled and the enumeration is the value in a `Map`. 

@msavy , I agree that thing can become vague once wildcards are in the mix. This area probably merits some additional thought on how to handle properly. Some sort of trigger point would need to be defined to determine whether something can be turned into a reference or kept in-line.

It's a separate issue for sure (related to #106), but I wanted to also ask whether the inclusion of the static field in `BazEnum` is correct. It seems that if it should not be included, either Jandex would need to be changed or this library would need to use the reflection API :-/ . Let me know if that merits further discussion and I'll open a separate issue or comment in 106.

**Comment by msavy** [comment]
I will have a think. This is why Eric and I avoided this problem on first
pass! It's definitely trickier than it looks, but it is good to start
delving into solutions now.

**Comment by EricWittmann** [comment]
This is cool - @MikeEdgar is really getting deep into the weeds!  Might need to get a machete. :)

**Comment by msavy** [comment]
> It's a separate issue for sure (related to #106), but I wanted to also ask whether the inclusion of the static field in BazEnum is correct. It seems that if it should not be included, either Jandex would need to be changed or this library would need to use the reflection API :-/ . Let me know if that merits further discussion and I'll open a separate issue or comment in 106.

Hmm, I seem to recall there's an annoying aspect of Enums where the local values defined by the programmer can be difficult to distinguish from the Enums generated by the compiler. I thought I'd fixed it though.

But yes, in general, programmer-defined statics should be ignored.

**Comment by MikeEdgar** [comment]
> Hmm, I seem to recall there's an annoying aspect of Enums where the local values defined by the programmer can be difficult to distinguish from the Enums generated by the compiler. I thought I'd fixed it though.
> 
> But yes, in general, programmer-defined statics should be ignored.

It looks like the field flags should have enough information to distinguish (not sure about compiler-generated ones though).  See the table in the https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.5. The `0x4000` value is defined in `java.lang.reflect.Modifier` but isn't public because it has different meanings depending on whether it's used with a class or a field, but it should work to test the fields.
