### ISSUE TITLE
Cannot ignore resource

### ISSUE THREAD

**Issue by mweber03** [smallrye/smallrye-open-api#1216]
In the Swagger annotations there exists `@Hidden` which allows for a resource or endpoint to be hidden from the OpenAPI documentation. Is this capability available between the smallrye and microprofile openapi functionality?

**Comment by MikeEdgar** [comment]
@mweber03 - you can use `@Operation(hidden = true)` to hide an endpoint method. To exclude the entire class, take a look at the `mp.openapi.scan.exclude.classes` configuration property.

**Comment by mweber03** [comment]
Thank you that worked.
