### ISSUE TITLE
Need equivalent to io.swagger.v3.jaxrs2.ReaderListener

### ISSUE THREAD

**Issue by mweber03** [smallrye/smallrye-open-api#1220]
I am working on migrating my project to use Quarkus SmallRye OpenAPI from Swagger. Something we use currently in Swagger is the [ReaderListener](https://javadoc.io/static/io.swagger.core.v3/swagger-jaxrs2/2.1.0/io/swagger/v3/jaxrs2/ReaderListener.html) to customize the OpenAPI definitions. How can I do this with Quarkus SmallRye OpenAPI?

**Comment by phillip-kruger** [comment]
Maybe a filter? See https://download.eclipse.org/microprofile/microprofile-open-api-1.0/microprofile-openapi-spec.html#_oasfilter

An example https://github.com/phillip-kruger/openapi-example/blob/main/src/main/java/com/github/phillipkruger/openapi/extra/MyFilter.java

Let me know if that works for you

**Comment by MikeEdgar** [comment]
@mweber03 did you get a chance to look at the `OASFilter` as suggested? That should give you full control over the resulting model.

**Comment by MikeEdgar** [comment]
Closing for now, please re-open if the suggestion to use an `OASFilter` does not help.
