### ISSUE TITLE
PathItemImpl should consider multiple methods for same path

### ISSUE THREAD

**Issue by michael-schnell** [smallrye/smallrye-open-api#123]
Currently a second method on the same path simply overrides a previously parsed operation. It should be allowed to have the same path multiple times for different content types. Instead of simply setting the new operation, it should be checked wether it is a different content type.

Consider the following (valid) OpenAPI specification with two different content types ("json" and "x-www-form-urlencoded"):

```yaml
  /offices/create:
    post:
      summary: Creates a new office.
      operationId: createOffice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOfficeCommand'
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - id
                - name
              properties:
                id:
                  type: string
                name:
                  type: string
```

This will be implemented in the same Java resource with two methods:

The first one allows a 'application/json' body:
```java
@POST
@Path("/offices/create")
@Consumes({ MediaType.APPLICATION_JSON })
@Operation(operationId = "createOffice")

public void createOffice(@RequestBody(required = true, 
content = @Content(schema = @Schema(implementation = CreateOfficeCommand.class)))
final CreateOfficeCommand cmd) { ... }
```

The second one allows 'application/x-www-form-urlencoded' parameters:
```Java
@POST
@Path("/offices/create")
@Consumes("application/x-www-form-urlencoded")
@Operation(operationId = "createOffice")

public void createOffice(@FormParam("id") String id, @FormParam("name") String name) { ... }
```

Parsing the resource using the [OpenApiAnnotationScanner](https://github.com/smallrye/smallrye-open-api/blob/master/implementation/src/main/java/io/smallrye/openapi/runtime/scanner/OpenApiAnnotationScanner.java) currently the second "x-www-form-urlencoded" method definition overrides the first 'application/json' one.

Instead the second method for the same path ("/offices/create") should simply be added as another media type for the same operation.

**Comment by EricWittmann** [comment]
You are right - this is a clear bug in the current impl.  Thanks for the report.

**Comment by MikeEdgar** [comment]
There may also be a second bug (really just a new feature) lurking here around the handling of `@FormParam` arguments being used as properties of a requestBody schema.

**Comment by MikeEdgar** [comment]
@michael-schnell - in your example with the annotated `application/json` method, you have specified `required = true`. When the two content types are merged beneath the same path, the `required` flag will apply to BOTH content types, since it lives at a higher level in the OAI document (as a child of `requestBody`). I just want to mention that since it may be an unexpected side effect.

**Comment by michael-schnell** [comment]
OK, thank's for the hint. I think it's not correct in the Java code and has to be removed. The open api YAMl is the correct definition.
