### ISSUE TITLE
Gradle plugin contribution

### ISSUE THREAD

**Issue by snazy** [smallrye/smallrye-open-api#1231]
We have ported the existing Maven plugin to Gradle and are using it for a while now for our build of [projectnessie](https://github.com/projectnessie/nessie). The Gradle port is currently maintained [here](https://github.com/projectnessie/gradle-build-plugins/tree/main/smallrye-openapi), but not published as a Gradle plugin.
Is there interest in having a Gradle plugin in this repository?

If yes, then we would create a pull request, to
* introduce the Gradle plugin incl tests
* unify code that can be shared with the Maven plugin

**Comment by phillip-kruger** [comment]
Yes for sure. It would be great if we also publish it
