### ISSUE TITLE
@ExampleObject with http/https URL should not lead to "#/components/" reference

### ISSUE THREAD

**Issue by michael-schnell** [smallrye/smallrye-open-api#124]
Currently the annotation 
```java
@ExampleObject(ref = "https://bitbucket.org/myaccount/whatever.json")`
```
generates an entry like 
```yaml
$ref: '#/components/examples/https://bitbucket.org/myaccount/whatever.json'
```
A full URL starting with "http://" or "https://" should stay unchanged in the generated open api specification.

**Comment by MikeEdgar** [comment]
`JandexUtil.refValue` currently will append the `#/components/...` prefix for any value passed, unless it already starts with "#/". I wonder if the simplest way to solve this issue would be to only add the prefix if the value passed matches the pattern for component keys given the OAS documentation: `^[a-zA-Z0-9\.\-_]+$`

Reference: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#components-object

> All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.
