### ISSUE TITLE
OperationIdStrategy leads to duplicate operationIds

### ISSUE THREAD

**Issue by renegrob** [smallrye/smallrye-open-api#1276]
Smallrye OpenAPI supports autogenerated operationIds with the following strategies:
```java
    enum OperationIdStrategy {
        METHOD,
        CLASS_METHOD,
        PACKAGE_CLASS_METHOD
    }
```
Depending on the strategy it is more or less likely to end up with duplicate operationIds. If you have an overloaded method in a REST endpoint, all of them will generate duplicate operationIds. The OpenAPI specification clearly states that operationIds must be unique, see https://swagger.io/specification/#operation-object. Duplicate operationIds lead to all kinds of troubles such as misfunctioning Swagger-UI and crashing code generators.
There are multiple ways to fix this:
* Fail on duplicate IDs and force the user to either rename classes or methods or override the clashing operationIds in order to avoid duplicates
* Automatically add a stable suffix to make them unique. (E.g. order of full classname, order of methods in source file)
* Provide other OperationId strategies

I think the most important would be to fail on duplicate operationIds as they violate the OpenAPI specification. There could be a flag to only issue a warning for backwards compatibility.

**Comment by phillip-kruger** [comment]
Are you keen to provide a PR?

**Comment by MikeEdgar** [comment]
@renegrob , I think adding a stable suffix makes sense. As you say, it should be opt-in. Perhaps the method argument names or hash code? It depends if they need to be readable I suppose.

**Comment by renegrob** [comment]
I made a first draft of the implementation here: https://github.com/renegrob/smallrye-open-api/tree/duplicate-operationId (only log or fail)
Tests are still missing and I don't know if I did the changes where they are supposed to be since I don't know the codebase that well.

**Comment by MikeEdgar** [comment]
It looks to be headed in the right direction based on the goal of warning/failing for duplicates. Feel free to open a PR at your convenience and we can add comments/suggestions there.

**Comment by renegrob** [comment]
I opened a PR: Fail or warn on duplicate operationIds #1289
