### ISSUE TITLE
Enhance code quality and JavaDoc

### ISSUE THREAD

**Issue by michael-schnell** [smallrye/smallrye-open-api#128]
While digging into the code for creating my push, I found that there are many types and methods that do not have any JavaDoc comment. This makes it hard for a project newbie to understand what the code is actually doing. Also the code sometimes looks like it could be improved in regard to formatting. At least I wasn't able to find information about things like "line length", "tab policy" or "encoding".

I think it would therefore be a good idea to:

- fix the JavaDoc
- provide Eclipse formatting rules (could be used also in IntelliJ IDEA and Netbeans with a plugin)
- format the code once using the new formatter
- provide suggestions for Eclipse/IntelliJ IDEA/Netbeans on how to configure “Organize Imports”, “Members Sort Order” and "Save Actions" (see [this article](https://blog.exxeta.com/2017/06/13/java-code-formatting-done-right-across-different-ides/))
- add the "jacoco-maven-plugin" to check code coverage
- add the project to [SonarCloud](https://sonarcloud.io) (free for OS projects)
- publish the results of the build at SonarCloud (See cmd snippet below)

I know it is some work, but I think the project will benefit from this very quickly.

Example of args for pushing the build results to SonarCloud:
```
mvn clean deploy jacoco:report sonar:sonar -U -B -P sonatype-oss-release -s settings.xml -Dsonar.organization=xxx -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_LOGIN}"
```

**Comment by EricWittmann** [comment]
Some very good suggestions here, for sure.  I wonder if @kenfinnigan has any thoughts about this based on what other SmallRye projects are currently doing in this area.

I'm usually not too worried about common formatting, as long as developers don't reformat stuff when they submit a PR I'm usually OK. :)  But I'm also not opposed to a set of common formatting rules.  

Certainly at least rules for e.g. Organize Imports is a no-brainer. 

What do others think about these various suggestions?  @msavy @MikeEdgar

**Comment by MikeEdgar** [comment]
I think these are good suggestions also. I have been keeping myself from using organize imports to prevent unnecessary changes :-) Code formatting can sometimes become a holy war (spaces v. tabs, placement of braces, etc.), but I think the project is generally formatted nicely now (probably pretty close to the Eclipse defaults for Java). Whatever rules are chosen shouldn't be TOO different.

I would suggest having a PR with with only the formatting changes, to prevent the messy functional PRs like you mentioned.

**Comment by kenfinnigan** [comment]
There was a thread started a while ago (https://groups.google.com/forum/#!topic/smallrye/14_tXdct0B8) but don't think @sberyozkin has had time to look into it.

Adding formatting, code style, sonar cloud, etc are all things "on the list", but just haven't had time. Ideally I'd want them done in a way that they can be applied to all SmallRye projects

**Comment by michael-schnell** [comment]
Sounds good to have it for all projects the same way.

**Comment by kenfinnigan** [comment]
And I forgot to add, if anyone wants to take on defining the formats, etc and then proposing them to the wider community that would be greatly appreciated

**Comment by michael-schnell** [comment]
The idea of having a separate "smallrye-code-rules" project as mentioned in the discussion group sounds good. Can someone create such a project? I would take the task over to start with it after that.

**Comment by msavy** [comment]
Agree with Michael. There's no point in causing a headache with the git
history by unnecessary cosmetic and formatting changes, or nits like import
order.

But having an overall standard format, especially for new stuff, is good.
As long as it's not too nagging.

**Comment by EricWittmann** [comment]
Yes I agree in general (it's just not something that really keeps me up at night).  So I'm fine with having it, just not willing to put any work into making it happen.  Fortunately @michael-schnell has volunteered to start something, if @kenfinnigan creates the repo.  :)

**Comment by kenfinnigan** [comment]
I've created https://github.com/smallrye/smallrye-code-rules

I know @sberyozkin was looking to do something similar to https://github.com/quarkusio/quarkus whereby the formatting rules are implemented during the build so no formatting is needed to be made directly. Not sure if that needs a separate repo or not, we can always delete it if we find it isn't needed

**Comment by michael-schnell** [comment]
Yes, I will use quarkus as a starting point.

**Comment by michael-schnell** [comment]
OK, I did the initial commit for the formatter: 
https://github.com/smallrye/smallrye-code-rules/pull/1

It's a jar file that can be added as a dependency.

The SmallRye parent pom must be enhanced in the "pluginManagement" section:
```xml
<pluginManagement>
	<plugins>
		<plugin>
			<groupId>net.revelc.code.formatter</groupId>
			<artifactId>formatter-maven-plugin</artifactId>
			<version>2.8.1</version>
			<dependencies>
				<dependency>
					<groupId>io.smallrye</groupId>
					<artifactId>smallrye-code-rules</artifactId>
					<version>1-SNAPSHOT</version>
				</dependency>
			</dependencies>
			<configuration>
				<configFile>io/smallrye/coderules/eclipse-format.xml</configFile>
				<skip>${format.skip}</skip>
			</configuration>
			<executions>
				<execution>
					<phase>process-sources</phase>
					<goals>
						<goal>format</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
		<plugin>
			<groupId>net.revelc.code</groupId>
			<artifactId>impsort-maven-plugin</artifactId>
			<version>1.2.0</version>
			<configuration>
				<groups>java.,javax.,org.,com.</groups>
				<staticGroups>*</staticGroups>
				<skip>${format.skip}</skip>
				<removeUnused>true</removeUnused>
			</configuration>
			<executions>
				<execution>
					<id>sort-imports</id>
					<goals>
						<goal>sort</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
	</plugins>
</pluginManagement>
```
The projects can then add the dependency in their parent pom:
```xml
<plugins>
	<plugin>
	<plugin>
		<groupId>net.revelc.code.formatter</groupId>
		<artifactId>formatter-maven-plugin</artifactId>
	</plugin>
	<plugin>
		<groupId>net.revelc.code</groupId>
		<artifactId>impsort-maven-plugin</artifactId>
	</plugin>
</plugins>
```
This allows a smooth integration in all projects. 

I also added a README.md that is an adapted copy from quarkus. I think it's a good idea to have a general guideline for commiters that also contains something like the Developer Certificate of Origin (DCO).

**Comment by michael-schnell** [comment]
OK, I moved some of the tasks to the new project:
https://github.com/smallrye/smallrye-code-rules/issues/2
https://github.com/smallrye/smallrye-code-rules/issues/3

**Comment by kenfinnigan** [comment]
Thanks for starting this @michael-schnell!

Once we've done a release of the code rules, would you be able to submit a PR to `smallrye-parent` to add the plugin configuration and the two profiles we need for format and validate?

**Comment by michael-schnell** [comment]
No problem. How will the first release for the code rules project be done?

**Comment by michael-schnell** [comment]
How is able to add a token secret to the build server for Sonar Cloud? I can add the necessary Maven build plugins after that, but I will need the variable name for that secret.

See https://github.com/smallrye/smallrye-code-rules/issues/3

**Comment by kenfinnigan** [comment]
I've done a release of the code rules project, `1`.

I've created https://github.com/smallrye/smallrye-parent/issues/15 for adding it into the parent.

I also moved the sonarcloud issue to the parent repo as well.

We don't have a settings.xml or regularly deploy Maven SNAPSHOTs at present. Currently all builds are done on Semaphore, but am looking at alternatives

**Comment by kenfinnigan** [comment]
Setup SonarCloud for this project and running a build of master, so will see what happens

**Comment by michael-schnell** [comment]
OK, will do the parent plugin stuff tomtorrow.

As far as I understood the docs at Semaphore, it should be possible to configure it as with above maven build example. If Maven is configured correctly, the snapshot could easily be deployed to OSS Sonatype.

**Comment by michael-schnell** [comment]
Ok, now we have:
- New SmallRye [parent pom](https://github.com/smallrye/smallrye-parent) with formatter & organize import plugins
- SonarCloud [project](https://sonarcloud.io/dashboard?id=smallrye_smallrye-open-api) for this project

To do when the parent pom is released:
- Add new parent pom to this project's parent pom (will clean the code automatically with next local build)
- Add JaCoCo Maven plugin
     - Must take into account the multi module build to have all tests
- Transfer results of JaCoCo to SonarCloud
    - Should be done after build on server
    - Figure out how this can be done with Semaphore CI (build pipeline file & settings.xml in project root should be possible)

**Comment by kenfinnigan** [comment]
Parent has been released, should start getting Dependabot notifications for updates over next day or so

**Comment by MikeEdgar** [comment]
An additional item needed for this is to enable the tests in the surefire plugin configuration of the implementation project. It's current missing *Test.java and *Tests.java.

```xml
<includes>
    <include>**/*TestCase.java</include>
    <include>**/*Test.java</include>
    <include>**/*Tests.java</include>
</includes>
```

**Comment by kenfinnigan** [comment]
Should this be in parent plugin config for Surefire?

If so, care to open an issue there and maybe a PR?

**Comment by MikeEdgar** [comment]
Possibly, but I believe each project would need to be updated to remove their own overriding configurations. I'll open that issue in the parent later today.

**Comment by MikeEdgar** [comment]
@kenfinnigan, the changes I was proposing are actually the default for surefire: https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html.

Removing the overridden `includes` from this project's `implementation/pom.xml` should do the trick. I'll put in that a PR.

**Comment by EricWittmann** [comment]
Now that the code formatting stuff is in, the maven build results in modified files.  I'm assuming we want to do a single commit with nothing but those formatting changes, yes?  @michael-schnell  @kenfinnigan is that the expectation here?

**Comment by kenfinnigan** [comment]
That’s correct yes.

Best to avoid the dependabot parent update and do it manually with a pr

**Comment by EricWittmann** [comment]
So basically this:  https://github.com/smallrye/smallrye-open-api/pull/140

**Comment by michael-schnell** [comment]
Yes, single commit with only formatting code changes should be the right way to go.

**Comment by MikeEdgar** [comment]
Currently, PRs seem to apply to the main SonarCloud analysis, which doesn't represent the current state of the project. It looks like SonarCloud and the build command can be configured to support branches and pull requests: https://sonarcloud.io/documentation/analysis/pull-request/

**Comment by MikeEdgar** [comment]
I think this issue can probably be closed as well. The only other thing that might be useful that doesn't require a code change would be to figure out SonarCloud branching/PR analysis. Currently, PRs overwrite the "master" analysis report. Thoughts @kenfinnigan ?

**Comment by michael-schnell** [comment]
> I think this issue can probably be closed as well. The only other thing that might be useful that doesn't require a code change would be to figure out SonarCloud branching/PR analysis. Currently, PRs overwrite the "master" analysis report. Thoughts @kenfinnigan ?

+1

**Comment by kenfinnigan** [comment]
Agree it needs to be figured out, as it's not ideal

**Comment by MikeEdgar** [comment]
@kenfinnigan - take a look at the [option for `sonar.branch.name`](https://sonarcloud.io/documentation/branches/overview/#analysis) in Sonar and the [BRANCH_NAME environement variable](https://semaphoreci.com/docs/available-environment-variables.html#variables-exported-in-builds-and-deploys) in Semphore.

I think adding this to the Semaphore builds should give us what we're looking for: `-Dsonar.branch.name=$BRANCH_NAME`

**Comment by kenfinnigan** [comment]
That's an option I wasn't aware of.

It could be looked at as part of https://github.com/smallrye/smallrye-parent/issues/79, as that will likely result in a different CI environment

**Comment by MikeEdgar** [comment]
That sounds good. It's even low-hanging fruit currently to stop the overlay of `master` branch analysis reports by PRs. Pull requests create a separate page highlighting the analysis on changes, which is nice.

**Comment by MikeEdgar** [comment]
This can be closed now that GitHub actions are in use for Sonar.
