### ISSUE TITLE
"@RolesAllowed" generates scopes with a basic authentication

### ISSUE THREAD

**Issue by MikelAlejoBR** [smallrye/smallrye-open-api#1280]
## Description

Scopes are used in `oauth2` and `openIdConnect` authentications. However, when a `@RolesAllowed` annotation is set on a method, `smallrye` automatically generates a basic authentication security scheme and it applies it with roles to the operation.

## Minimal sample project

- https://github.com/MikelAlejoBR/quarkus-smallrye-openapi-issue

## OpenApi JSON output

```json
{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "code-with-quarkus API",
    "version" : "1.0.0-SNAPSHOT"
  },
  "paths" : {
    "/hello" : {
      "get" : {
        "tags" : [ "Greeting Resource" ],
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "text/plain" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          },
          "401" : {
            "description" : "Not Authorized"
          },
          "403" : {
            "description" : "Not Allowed"
          }
        },
        "security" : [ {
          "SecurityScheme" : [ "events:read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "SecurityScheme" : {
        "type" : "http",
        "description" : "Authentication",
        "scheme" : "basic"
      }
    }
  }
}
```

## Expected behaviour

* Don't generate the scopes for the operations unless there is an `oauth2` or an `openIdConnect` security scheme defined.
* Or, don't generate the scopes inside the default security scheme in the operations.

**Comment by MikeEdgar** [comment]
@MikelAlejoBR I think this is the same as https://github.com/quarkusio/quarkus/issues/27373 . Since it's actually Quarkus code that is doing this, we can go ahead and close this one and get it fixed via the Quarkus issue instead.
