### ISSUE TITLE
smallrye-open-api-maven-plugin with Quarkus does not add @Operation data

### ISSUE THREAD

**Issue by RomainWilbert** [smallrye/smallrye-open-api#1283]
Hi !

I am using smallrye-open-api-maven-plugin with Quarkus, and in my schema generated file, I only have @OpenAPIDefinition data.

[See sample projet here](https://github.com/RomainWilbert/openapi-maven-plugin.git)

**Comment by MikeEdgar** [comment]
Hi @RomainWilbert , the scanner only adds paths/operations from interfaces if an implementation is present. Also, `@OpenAPIDefinition` is only used if it is found on a JAX-RS `Application` class or a `package-info`.

**Comment by RomainWilbert** [comment]
Thanks. BTW could the plugin be compiled with Java8 ?
