### ISSUE TITLE
RC5 uses dependency (OpenAPI 3.1) that is not available in public repos

### ISSUE THREAD

**Issue by rikard-swahn** [smallrye/smallrye-open-api#1299]
RC5 uses dependency (OpenAPI 3.1) that is not available in public repos

See this https://github.com/smallrye/smallrye-open-api/commit/755f0169797de2fcf61383a8bed5a1c3d6aff017

**Comment by MikeEdgar** [comment]
@rikard-swahn , this is intentional. The MicroProfile OpenAPI 3.1 specification requires at least one compliant implementation before releasing. This is part of the process of releasing the spec. Once it's available in Maven Central, the temporary repo will be removed and we'll release 3.1.0 here.

**Comment by MikeEdgar** [comment]
Resolved via #1322
