### ISSUE TITLE
Processing of classes for JSON schema generation should obey @JsonIgnore

### ISSUE THREAD

**Issue by EricWittmann** [smallrye/smallrye-open-api#13]
When processing a class for the purpose of creating a JSON schema, the class MAY be annotated with `@JsonIgnore`.  We should do our best to support the semantics of that annotation.

**Comment by EricWittmann** [comment]
The original bug report can be found here:  https://issues.jboss.org/browse/THORN-2098

**Comment by EricWittmann** [comment]
Yeah I think whatever common Jackson annotations are easy to support and make sense, we should try to support them.

**Comment by EricWittmann** [comment]
I don't know offhand what they all are. :)

**Comment by EricWittmann** [comment]
But we can at least **start** with these two and go from there.  No need to go crazy right away.

**Comment by msavy** [comment]
Agreed.

**Comment by msavy** [comment]
Starting on this now.

**Comment by msavy** [comment]
To nobody in particular: Please feel to reopen (or file new ticket) if you find cases where the Jackson ignore annotations don't work as expected.
