### ISSUE TITLE
U/I fails to render when `options` is passed to `IndexHtmlCreator#createIndexHtml`

### ISSUE THREAD

**Issue by tjquinno** [smallrye/smallrye-open-api#1304]
@phillip-kruger and @MikeEdgar 

Hi, gents. 

I'm creating a Helidon Maven artifact that depends on the SmallRye OpenAPI U/I component. 

When I let the U/I use the default `index.html`, the U/I renders just right.

But, if I invoke `IndexHtmlCreator.createIndexHtml(options)`--even with a null `options` which defaults everything--the browser shows an empty screen (Safari and Firefox). Using Safari's developer mode, I see 
```
ReferenceError: Can't find variable: oar
```
And, in fact, the generated `index.html` contains the code below, referring to `oar` without declaring it.

I believe the problem is at https://github.com/smallrye/smallrye-open-api/blob/ab0d9912fbb4c7998cea713f62cc145ec17c6117/ui/open-api-ui/src/main/java/io/smallrye/openapi/ui/IndexHtmlCreator.java#L71-L73  `variableOption` is an `Option` but that line uses `.equals` against a string which never matches. It looks as if the comparison should be against `Option.oauth2RedirectUrl`.

But that change alone is not enough. I think instead of returning "-" perhaps the code should assign `replacement = "-"` and then continue on with the rest of the method, returning `null` at that point only if the replacement is null and the option in play is not `oauth2RedirectUrl`.

I tried these changes locally and it seems to work better, but I certainly haven't tested the change thoroughly.

Here's the full `index.html` delivered to the browser:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Helidon OpenAPI U/I</title>
        <link rel="stylesheet" type="text/css" href="swagger-ui.css" >
        <link rel="stylesheet" type="text/css" href="theme-feeling-blue.css" >

        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
        <link rel="icon" href="favicon.ico" type="image/x-icon">
        <link rel="stylesheet" type="text/css" href="style.css" >
    </head>

    <body>
        <div id="swagger-ui"></div>
        <script src="swagger-ui-bundle.js" charset="UTF-8"></script>
        <script src="swagger-ui-standalone-preset.js" charset="UTF-8"> </script>
        <script>

            window.onload = function() {
                
                // If Url is relative, append the host and port
                if(oar.startsWith("/")){
                    oar = window.location.protocol + "//" + window.location.host + oar;   
                }
                
                console.log(oar);
                
                var ui = SwaggerUIBundle({
                            url: '/openapi',
                            dom_id: '#swagger-ui',
                            deepLinking: true,
                            presets: [SwaggerUIBundle.presets.apis,SwaggerUIStandalonePreset],
                            plugins: [SwaggerUIBundle.plugins.DownloadUrl],
                            layout: 'StandaloneLayout',
                            oauth2RedirectUrl: oar,
                          })
                
                
                window.ui = ui;

                document.getElementsByClassName("link")[0].innerHTML = "<a id='swaggerUiLogoLink' href='/openapi-ui'><img src='/frank.svg' alt='Helidon OpenAPI U/I' height='44' align='middle'></a><a id='swaggerUiTitleLink' href='/openapi-ui'></a>";
            }
        </script>
    </body>
</html>
```

**Comment by phillip-kruger** [comment]
Hi @tjquinno . We do set that in Quarkus here: https://github.com/quarkusio/quarkus/blob/17796c95e7a3346c924caaecf7b2207f44f252b7/extensions/swagger-ui/deployment/src/main/java/io/quarkus/swaggerui/deployment/SwaggerUiProcessor.java#L290

I'll have to look into more detail on why you get this issue. A reproducer will help, if you can share one

You are also welcome to contribute the maven plugin (that generates the swagger-ui) to this project ? We already have a plugin that generates the openapi...

**Comment by tjquinno** [comment]
Thanks, @phillip-kruger.

Here's a reproducer. It's layered on several other Helidon components but the interesting parts are in the zip.

Run `mvn test` to see it working, using the default `index.html` that's in `smallrye-open-api-ui`. 

Run  `mvn -DargLine="-DshowError=true" test` to see the blank page failure. 

Each way you have 5 minutes to browse to `http://localhost:8080/openapi-ui/index.html`.

The `Reproducer` constructor invokes `IndexHtmlCreator.createIndexHtml` with an empty map and saves the resulting `byte[]`.

`Reproducer::update` contains the key difference, serving the customized byte array in the error case and just defaulting through to the U/I component's default `index.html` in the success case.

[openapi-ui-reproducer.zip](https://github.com/smallrye/smallrye-open-api/files/9916540/openapi-ui-reproducer.zip)

**Comment by phillip-kruger** [comment]
Hi @tjquinno - Thanks for the reproducer. I can see that it happens, but I am not sure where the code it that create the index.html ? Can you create or share the code that create the html that cause the issue ?

**Comment by phillip-kruger** [comment]
@tjquinno - it might also be a version things. If I look at the latest template it seems correct: https://github.com/smallrye/smallrye-open-api/blob/64f2874a2e9139b04dfebacd35a99421bbde4afc/ui/open-api-ui/src/main/resources/template/index.html#L24

**Comment by tjquinno** [comment]
Hi, @phillip-kruger 

In the zip, JUnit runs `MainTest#tryIt` which first triggers `MainTest#init` which invokes `startServer` which invokes `creatRouting` which instantiates the `Reproducer` class and its constructor invokes `IndexHtmlCreator#createIndexHtml`.

In any event, if you run the reproducer this way
```
mvn test -Dmaven.surefire.debug
```
and set a breakpoint in your IDE at `IndexHtmlCreator:71` you should see that the comparison does not work because it compares `variableOption` which is an `Option` instance to the `String` constant `"oauth2RedirectUrl"`. 

It seems that the comparison should be `if (variableOption.equals(Option.oauth2RedirectUrl))` (or, given it's an `enum`, it could use `==` if you're into that).

Beyond that, I also think the code needs to not return `"-"` immediately there but instead assign `replacement = "-"` and then find its way to the rest of the code--at least to line 101 to replace the token in the `line` with the replacement value.

**Comment by phillip-kruger** [comment]
So it seems like we can just safely remove that whole block, since it's not working at the moment, because it will never return true. (String vs enum comparison)

Agree? I am not sure what I wat trying to do there anyway

**Comment by tjquinno** [comment]
No, I do not think removing the block is the right change. 

I am no mind-reader, but here's my theory about what the intent _might_ have been!

In almost all cases, if a line contains a token that is not defined, then discard the line. 

Given the current template, the one exception to this rule is the `oauth2RedirectUrl` token because its indirect impact (that `oar` variable) is not limited to just one line but spans multiple lines.

So, before returning `null` when we find an undefined token, check to make sure the token is not `oauth2Redirect` and use a harmless default replacement value for that token _and continue processing that line_.

Problem 1: The comparison to check for `oauth2Redirect` is flawed so it never returns true.
Fix 1: Change the comparison as discussed in earlier comments.

Problem 2: Even with the comparison fixed, the code does not adopt the default replacement value and continue processing but instead immediately returns.
Fix 2:
Apply the attached patch or its equivalent. (There's also some whitespace reformatting which I suppressed in the patch file for clarity).

This assigns `replacement` to the harmless default value in the `oauth2Redirect` case and then continues on processing that replacement value,  taking the `return null` path in all _other_ cases of undefined tokens.

[patch.txt](https://github.com/smallrye/smallrye-open-api/files/9975755/patch.txt)

**Comment by phillip-kruger** [comment]
@tjquinno - how about a PR, then we can discuss there ? I think what you describe sounds good.

**Comment by tjquinno** [comment]
@phillip-kruger @MikeEdgar Is there a contributor agreement or anything like that I need to execute to contribute?

**Comment by tjquinno** [comment]
The link from https://github.com/smallrye/smallrye to the committer nomination process is broken. I'm can work through the necessary steps to become a committer as long as I know what they are :-) .

**Comment by MikeEdgar** [comment]
@tjquinno we don't have a contribution agreement at the moment. You just want to open a PR right?

**Comment by tjquinno** [comment]
@MikeEdgar Yes, Mike, that's exactly right. (Apologies for using this issue as a message board.)

**Comment by phillip-kruger** [comment]
Yes, just open a PR, no need to become a committee (for now)

**Comment by tjquinno** [comment]
@MikeEdgar @phillip-kruger PR created. Workflows are stalled awaiting maintainer approval since I'm a first-time committer.
