### ISSUE TITLE
Schemas for classes in dependency JARs never generated

### ISSUE THREAD

**Issue by sidohin-felix** [smallrye/smallrye-open-api#1321]
Hello,

Not sure if this is a bug or a configuration issue, but I am trying to use the gradle plugin with a vanilla microprofile project (simple WAR generated and loaded into a TomEE instance). I have run into the following issue:

Let's assume a library A is included as compileOnly and some object MyObject from A is used either as a request body or response. Basically:

```
public Response appendNetwork(@RequestBody MyObject myObject) throws Exception {
        //do stuff with my object here.
        return Response.ok().build();
    }
```     

When I run the gradle task below everything gets generated correctly except the schema for MyObject which results in the following errors in the debug ``` [io.smallrye.openapi.runtime.scanner] SROAP04005: Could not find schema class in index: MyObject``` (assume that MyObject is included correctly as some ```com.mypackage.whatever.MyObject```)

```
generateOpenApiSpec {
    outputDirectory = new File(this.getProjectDir().toString() + "/src/main/resources/openapi")
    scanDependenciesDisable = false
}
```
Is this a limitation or am I missing some configuration here?

As a possible hint when using the 'io.swagger.core.v3.swagger-gradle-plugin' version '2.1.11' the same problem surfaces but it can be mitigated with the following configuration of the plugin, in which case MyObject is indeed found and correctly included as a schema in the OpenAPI specification:

```
resolve {
    outputFileName = 'api'
    outputFormat = 'YAML'
    prettyPrint = 'TRUE'
    classpath = sourceSets.main.output + configurations.compileClasspath
    buildClasspath = classpath
}
```

**Comment by Hes-Siemelink** [comment]
Having a similar problem in gradle 7.5.1 when declaring dependencies like this:

```
dependencies {
  api project(":core:domain-classes")
```

where `core/domain-classes` is a source directory in the same repo.

The plugin can't find the domain classes and doesn't generate JSON schema for them. It only works if start copying the domain classes into the API project that has the plugin configured on it.

**Comment by sidohin-felix** [comment]
Confirmed for me as well. Indeed all the objects are now generated!
