### ISSUE TITLE
Don't require the pom.properties file to be present on the classpath

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-open-api#1333]
When we implement MP OpenAPI in open liberty, we repackage the org.eclipse.microprofile.openapi jar and generate new maven metadata so it does not contain the pom.properties file in the expected location.

Can we adapt the code added in #1269 to default to the latest version if this file is not found? (A different solution would also be fine, but this one seems the most straightforward.)

**Comment by MikeEdgar** [comment]
> we repackage the org.eclipse.microprofile.openapi jar and generate new maven metadata so it does not contain the pom.properties file in the expected location

Is your process flexible enough to drop a pom.properties in the expected location? Otherwise, maybe this could be a config property that isn't user-facing. Would that work?

**Comment by Azquelt** [comment]
> Is your process flexible enough to drop a pom.properties in the expected location?

It is, but one of the uses of the maven metadata is to help someone looking at the jar understand what it is and where it came from. I don't want to drop in a second pom.properties with different information when the jar we build already has one.

> Otherwise, maybe this could be a config property that isn't user-facing. Would that work?

This is a possibility. It would also be fine if it was read from a properties file on the classpath with a different name. I'd just like some way of overriding it which doesn't involve adding incorrect maven metadata to my jar.
