### ISSUE TITLE
Ignore root path in OpenApi

### ISSUE THREAD

**Issue by Podnevar** [smallrye/smallrye-open-api#1334]
In company we started using Quarkus and in order to distinguish each web service, every webservice contains root path: "/webservice-name/rest". Now problem is that every endpoint in openapi document has this prefix of root path. Is it possible to somehow move that root path which is repeating across endpoints to server section?

For example
localhost:8080/webservice-name/rest

**Comment by MikeEdgar** [comment]
@Podnevar, you could try using an `OASFilter` for this:
```java
class PathFilter implements OASFilter {
    public void filterOpenAPI(OpenAPI openAPI) {
        Map<String, PathItem> pathItems = openAPI.getPaths()
            .getPathItems()
            .entrySet()
            .stream()
            .collect(Collectors.toMap(this::formatKey, Map.Entry::getValue));

        openAPI.getPaths().setPathItems(pathItems);
        // TODO: modify server if necessary
    }

    String formatKey(Map.Entry<String, PathItem> entry) {
        return entry.getKey().substring("/webservice-name/rest".length());
    }
}
```
Then add it to your configuration:
```properties
mp.openapi.filter=fully.qualified.classname.PathFilter
```

**Comment by MikeEdgar** [comment]
@Podnevar did you solve this one?

**Comment by MikeEdgar** [comment]
The approach listed earlier is one way to solve this. Please re-open if there are any other concerns on how to do it or it isn't working for you.
