### ISSUE TITLE
Gradle Plugin: Circular Dependency

### ISSUE THREAD

**Issue by wabuMike** [smallrye/smallrye-open-api#1335]
### How to reproduce

1. Include the Gradle Plugin in an existing Quarkus Gradle project as described in https://github.com/smallrye/smallrye-open-api/blob/main/tools/gradle-plugin/README.md#via-gradle-includebuild 
1.  On the existing project, execute the Gradle task "generateOpenApiSpec" with `./gradlew generateOpenApiSpec`. Gradle will give you the error: 

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Circular dependency between the following tasks:
> :compileJava
> +--- :quarkusGenerateCode
> |    \--- :processResources
> |         \--- :generateOpenApiSpec
> |              +--- :compileJava (*)
> |              +--- :quarkusGenerateCode (*)
> |              \--- :quarkusGenerateCodeDev
> |                   \--- :processResources (*)
> \--- :quarkusGenerateCodeDev (*)
> 
> (*) - details omitted (listed previously)
> 
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s

### Solution

The problem is with those lines in [SmallryeOpenApiPlugin.java](https://github.com/smallrye/smallrye-open-api/blob/main/tools/gradle-plugin/src/main/java/io/smallrye/openapi/gradleplugin/SmallryeOpenApiPlugin.java): 

```java
project.getTasks().named(sourceSet.getProcessResourcesTaskName(), ProcessResources.class)
                .configure(t -> {
                    t.dependsOn(genTaskName);
                    t.from(project.getTasks().getByName(genTaskName).getOutputs().getFiles());
                });
```

When I remove those lines, the task runs as expected. I suppose those lines have their purpose and although removing them works for my use case, it might break other use cases.

**Comment by MikeEdgar** [comment]
@snazy, do you have any ideas on this one? My Gradle expertise isn't quite up to par :-)

**Comment by snazy** [comment]
Looking...
