### ISSUE TITLE
@BeanParam parameters are apparently ignored

### ISSUE THREAD

**Issue by gsmet** [smallrye/smallrye-open-api#135]
We just had this report in the Quarkus bugtracker:

**Describe the bug**
The openapi does not support @BeanParam.
If the rest service method uses the @BeanParam this attribute is ignored in the generated openapi.yaml file.

**Expected behavior**
The openapi.yaml contains also the information from the @BeanParam parameter object.

**Actual behavior**
The @BeanParam is ignored and not generated in the openapi.yaml

**To Reproduce**
1. Create rest method with a @BeanParam parameter
2. Download openapi http://localhost:8080/openapi

Could you take a look?

Once it's fixed, we need to upgrade SmallRye OpenAPI in Quarkus: https://github.com/quarkusio/quarkus/issues/2819

**Comment by MikeEdgar** [comment]
@gsmet - this should be covered with the fix for #129
