### ISSUE TITLE
Schema default value is not working

### ISSUE THREAD

**Issue by Katakurinna** [smallrye/smallrye-open-api#1368]
Hello there! 
Im trying to use defaultValue in a Schema.

![image](https://user-images.githubusercontent.com/43810296/216569190-16a9d1a1-79a0-4ad7-aefd-fc9dd987875f.png)

But when I send the request, the body have null in value (if I use primitive boolean, its the default value of primitiva, a false)
![image](https://user-images.githubusercontent.com/43810296/216569704-0bba591f-a154-4dfc-a213-eb3ece411a01.png)

Quarkus Version: 2.15.1.Final
Java version: graalvm-ce-17

**Comment by phillip-kruger** [comment]
How do you send the request ? The default value should show in the schema (you can share that and we can see). How the schema gets used is up to how you call it. If you look in Swagger UI what do you see ?

**Comment by phillip-kruger** [comment]
(Swagger UI interoperate the schema and should pre-populate the value)

**Comment by Katakurinna** [comment]
I send the request from postman, its only work from swagger?

**Comment by phillip-kruger** [comment]
Well, postman does not look at the schema at all. If you want a default value for the request, the that is a case for REST (JAX-RS). A quick google give me this: https://www.logicbig.com/tutorials/java-ee-tutorial/jax-rs/default-value.html

**Comment by phillip-kruger** [comment]
(Remember the schema only document the endpoint)

**Comment by Katakurinna** [comment]
Sorry to have bothered then.
@DevaultValue is not working for me, but I'll look for some other way. 
Thank you very much for your quick response
Have a nice day and good friday!

**Comment by phillip-kruger** [comment]
You did not bother at all :)

**Comment by phillip-kruger** [comment]
B.t.w, `@DefaultValue` will not change the request in postman, but rather the value on the server side when nothing is provided

**Comment by Katakurinna** [comment]
Hello there Phillip!
Yes I know, but It only works in path param, or else, not in a body.
And I need the default value in inside the body.
Thank you btw.
Have a good weekend! 😁

**Comment by phillip-kruger** [comment]
Ok, I guess you can then code the default value in the POJO representing the body ?

**Comment by Katakurinna** [comment]
Yes, only if I don’t send the param in the request. 
if eg I send “potato”:null
This remove the value presented in the class

**Comment by phillip-kruger** [comment]
Ok I am closing here. Please reopen if you think this is an OpenAPI discussion. Cheers
