### ISSUE TITLE
Reintroduce logging

### ISSUE THREAD

**Issue by msavy** [smallrye/smallrye-open-api#14]
It'd be great to be able to reintroduce (currently commented out) logging somehow that has been commented out. I've had to temporarily hack it back in for my development -- annoying subtle bug that I couldn't figure out from debugging alone -- and was clear once logging was back in. 

Also, I think the logging will add a lot of value when support cases start arriving, etc. 

What are people's thoughts about how best to do this?

**Comment by msavy** [comment]
Hey, @kenfinnigan Any thoughts on this?

**Comment by EricWittmann** [comment]
I asked for guidance on this issue on the thorntail mailing list but I don't think there was a response. :)

**Comment by msavy** [comment]
Ken is on hols it turns out, so might not get a reply for a while

**Comment by kenfinnigan** [comment]
Based on https://groups.google.com/forum/#!topic/smallrye/W-6D2pfnTeE I think JBoss Logging is fine, and then an implementation provided by an app

**Comment by EricWittmann** [comment]
TIL that JBoss Logging supports custom message interfaces that can be easily internationalized. :)

**Comment by msavy** [comment]
I guess the other option would be something like slf4j or whatever. If anyone has strong feelings, feel free to weigh in here or on the thread...

**Comment by kenfinnigan** [comment]
I'd lean towards JBoss Logging, as the user can still choose slf4j as the implementation

**Comment by msavy** [comment]
@EricWittmann @kenfinnigan I guess I should just need to add: 

```xml
<dependency>
    <groupId>org.jboss.logging</groupId>
    <artifactId>jboss-logging</artifactId>
    <version>3.3.2.Final</version>
</dependency>
```
Any preference for a version? I notice Thorntail just uses provided -- https://github.com/thorntail/thorntail/blob/master/fractions/wildfly/logging/pom.xml#L73-L82. 

Not sure whether this might cause some side-effects if we include a jboss-logging artifact.

**Comment by msavy** [comment]
Oh, I see jboss logging 2.0.1.Final in smallrye-open-api-parent already :-).

**Comment by msavy** [comment]
This is quite confusing, but it seems `jboss-logging` didn't release their project artifacts in lockstep during the 2.x era? 

Hence, `2.0.1.Final`, as far as I can determine, has no release of the actual logging interfaces  https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.jboss.logging%22%20AND%20v%3A%222.1.0.Final%22

@thejamezp is this correct? Would you suggest we just update to 3.x?

**Comment by jamezp** [comment]
@msavy There are two (three deps) separate projects. There's `org.jboss.logging:jboss-logging` which is a logging facade similar to slf4j. Then there's `org.jboss.logging:jboss-logging-annotations` and `org.jboss.logging:jboss-logging-processor`. The later two are used for the logger/message bundle interfaces. 

So for the logging facade, `org.jboss.logging:jboss-logging`, the latest release is 3.3.2.Final which is what I would suggest.

For the annotation processor, `org.jboss.logging:jboss-logging-annotations` and `org.jboss.logging:jboss-logging-processor`, those are compile time only tools. Generally they should be marked as `<scope>provided</scope>`. Neither of them are needed at runtime. I also don't seem them being used in the project at all so those deps can probably be removed unless there is a plan to introduce message bundle and/or logger interfaces.

**Comment by msavy** [comment]
Aha, using what you've written I Googled a bit and found these docs https://jboss-logging.github.io/jboss-logging-tools/ (by none other than yourself).

**Comment by jamezp** [comment]
Yup. I almost forgot about that haha. I really need to get documentation for jboss-logging (facade) as well with explanations of all this. It's understandably confusing.

**Comment by msavy** [comment]
@jamezp Thanks! Which version of jboss-logging (facade) is being used in the latest WF? I can't find an explicit version in the parent pom 🤔, but I might be missing something.

**Comment by jamezp** [comment]
Looks like [3.3.1.Final](https://github.com/wildfly/wildfly-core/blob/master/pom.xml#L165), it's part of WildFly Core. Though I think I'll file an issue and upgrade to 3.3.2.Final today. The only change is for better Java 9+ support so I'd suggest 3.3.2.Final. Here's the diff between 3.3.1.Final and 3.3.2.Final https://github.com/jboss-logging/jboss-logging/compare/3.3.1.Final...3.3.2.Final.

**Comment by msavy** [comment]
Thanks a bunch for the useful info! It's much appreciated.

**Comment by jamezp** [comment]
And just for completeness here's the WildFly Core JIRA for the upgrade https://issues.jboss.org/browse/WFCORE-3981
