### ISSUE TITLE
`SchemaRegistry` depends on Jackson

### ISSUE THREAD

**Issue by tjquinno** [smallrye/smallrye-open-api#1417]
The earlier addition of `AnnotationScannerExtension` and delegation to it from key points allows the use of parsers other than Jackson in multiple places.

`SchemaRegistry` is one place that still has a hard dependency on Jackson: https://github.com/smallrye/smallrye-open-api/blob/9a2013f8a385b488b3fc3db4fe946c44ff9551e3/core/src/main/java/io/smallrye/openapi/runtime/scanner/SchemaRegistry.java#L251

It would be great for `SchemaRegistry` also to delegate to an extension for schema parsing. 

I know that `OpenApiConfig` allows me to pass my own custom schema registry, but I don't really want to re-implement `SchemaRegistry` or change its behavior _except_ for its choice of parser.

(I have not looked through the codebase for other lingering direct reliance on Jackson's parsing.)

**Comment by MikeEdgar** [comment]
It looks like we'll need to add a `Schema parseSchema(String value)` to `AnnotationScannerExtension`
