### ISSUE TITLE
Token for Sonar Cloud is visible for the public in the build

### ISSUE THREAD

**Issue by michael-schnell** [smallrye/smallrye-open-api#142]
There is a security problem with the build configuration: The private key for Sonar Cloud is visible in the build output. There should be some option in the build server to hide this information in the log output. And of course the password should be changed immediately.

`mvn clean verify sonar:sonar -Dsonar.projectKey=smallrye_smallrye-open-api -Dsonar.projectName="SmallRye Open API" -Dsonar.organization=smallrye -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=977e5673bd92xxxxxxxxxx849e6f3c7500c4
`

**Comment by kenfinnigan** [comment]
It's the fact that the command is shown right, as opposed to the console output of the build?

**Comment by kenfinnigan** [comment]
Should now be fixed

**Comment by kenfinnigan** [comment]
Thanks for reporting it!
