### ISSUE TITLE
RESTEasy body extensions are not supported

### ISSUE THREAD

**Issue by FroMage** [smallrye/smallrye-open-api#144]
We've had reports from Quarkus users that RESTEasy body param types/annotations as declared in https://docs.jboss.org/resteasy/docs/1.1.GA/userguide/html/Multipart.html which SmallRye-OpenAPI did not properly read.

Would you be willing to consider them (like the RESTEasy param annotations), or provide extension points so that we can support them in Quarkus?

**Comment by MikeEdgar** [comment]
It seems reasonable to me. I think there is a high likelihood that smallrye-open-api and Resteasy will be running together in most cases. Are there any issues open documenting the user expectations for the OpenAPI output?

**Comment by EricWittmann** [comment]
There are no guidelines that I'm aware of. The specification is notably vague on this subject, which I think is mostly good.  I think we should support as many resteasy use cases as possible/reasonable. So +1 from me.

**Comment by MikeEdgar** [comment]
@FroMage - please review PR #148 and let me know if the test case expectations cover the reports that you're aware of.
