### ISSUE TITLE
Generated yaml document is in wrong format when the path length reach 128+ bytes

### ISSUE THREAD

**Issue by Neo2796** [smallrye/smallrye-open-api#1456]
I have a simple resource class with a simple POST api.
I try to generate openapi documentation and download it as a yaml file.
When the path length doesn't reach 128 byte, the generated file is ok,
but, if the path length reach the 128+ bytes, the generated file is in an wrong format.

below is an example:

`@Path("/api/v1/internal/export/{aaaa_id}/customers/{bbbbbbbb_id}/xxxxxxxxxxxxxxxxxxxxxxxy/{ccccccccccccccc_id}/{ddddddddddddddddddd_id}")` (length: 128) --> the generated openapi yaml file is in a wrong format

Generated file: ![generated_file_wrong_format](https://user-images.githubusercontent.com/24981355/236244235-a5ecc978-7e82-4c86-9e1b-9a1644edafef.png)

`@Path("/api/v1/internal/export/{aaaa_id}/customers/{bbbbbbbb_id}/xxxxxxxxxxxxxxxxxxxxxxx/{ccccccccccccccc_id}/{ddddddddddddddddddd_id}")` (length: 127) --> the generated openapi yaml file is ok

Generated file: ![generated_file_format_ok](https://user-images.githubusercontent.com/24981355/236244220-d78a59b3-6ae9-453c-9c40-19a9347407c3.png)

**Comment by MikeEdgar** [comment]
Reference why this is happening: https://yaml.org/spec/1.1/#id934761

The default value in snakeyaml to use explicit keys is length of 128. We can increase this or make it configurable perhaps.
