### ISSUE TITLE
Memory leak via thread locals

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-open-api#1462]
Several classes appear to store the "current" instance of the class in a thread local: `SchemaRegistry`, `JavaSecurityProcessor` and `CurrentScannerInfo` and I can't see anywhere where these fields are cleared.

In an application server where several applications may be deployed and removed, this can cause a memory leak as the objects stored in the thread locals do not get cleaned up at the end of generating the OpenAPI document.

`SchemaRegistry` in particular holds a reference to the application classloader (via the `AnnotationScannerContext`) which prevents the application classes from being garbage collected when the application is removed. Open Liberty has a defect open for this issue: OpenLiberty/open-liberty#24577

The most obvious way to resolve this issue would be to clear these thread locals at the end of `OpenApiProcessor.bootstrap`, though it might also be helpful to have a single method which clears all the context in case more thread locals are added in the future.

Alternatively, the code could be reworked to reduce dependence on thread locals, but that would be a much larger change.

**Comment by MikeEdgar** [comment]
Thanks for reporting this @Azquelt . The `SchemaRegistry` used to be cleaned up via its `remove` method, but it looks like that was dropped somewhere inadvertently. I think we probably want to do this a a `finally` in `OpenApiAnnotationScanner#scan`
