### ISSUE TITLE
Change Java Date type format to DATE_TIME

### ISSUE THREAD

**Issue by neon-dev** [smallrye/smallrye-open-api#147]
java.util.Date is set to be a simple date without time:
https://github.com/smallrye/smallrye-open-api/blob/ca9c8b35c35d18fd119e4031ffa7033f66e78a91/implementation/src/main/java/io/smallrye/openapi/runtime/util/TypeUtil.java#L110

Any (de)serializer that I know maps them to dates with time, never only the date part. Because of the definition of type `date`, Swagger-UI for example generates bad example values like "2019-07-01".

`DATE_FORMAT` should therefore be changed to `DATE_TIME_FORMAT` for both mentioned Java Date types.

**Comment by msavy** [comment]
I implemented it that way because of the spec requirements:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#dataTypeFormat

I *think* I interpreted it correctly, but would be very glad to double
check and hear your view.

Also open to discussing this at the spec level if necessary, as I'm
involved there also.

**Comment by neon-dev** [comment]
I'm not sure I understand the what requirements you mean. From what I've read it looks like there are no rules which internal data types are tied to what formats (which makes sense). Only how `date` and `date-time` formats should look like.
So I currently don't see a restriction that would prevent proposed change. And I think if a Java type contains info for both date and time, it should be handled as such.

Another thing is that every framework handles de-/serialization differently. For instance, Jackson by default serializes dates as epoch millis instead of strings. Here dates would be better defined as integer and not string. Is there a way to configure this? Wouldn't be a bad idea now that I thank about it.

**Comment by MikeEdgar** [comment]
I think the mapping for `java.sql.Date` is correct based on the semantics of that type but there may be room for debate around `java.util.Date`. In any case, providing a way for applications to specify a global override for types might make sense (without changing any current defaults).

Perhaps a configuration extension such as the following that would be used by `TypeUtil`?
`mp.openapi.extensions.type-format.FQCN=SchemaType,DataFormat`

**Comment by neon-dev** [comment]
You're totally right regarding java.sql.Date, @MikeEdgar. I removed it from the initial post of this issue.

**Comment by msavy** [comment]
Was just discussing this with @EricWittmann 

I think I was interpreting the spec incorrectly by mapping `date` in the OAI sense strictly to `Date` in Java. 

My thinking is now: change `java.util.Date`,  and @MikeEdgar's idea to allow people to change it back and/or provide their own mappings.

WDYT?

I'll have a look at it and check it doesn't break anything.

**Comment by MikeEdgar** [comment]
Is this another one that should be raised to the spec level? I.e. configurable support for global type mappings?

**Comment by EricWittmann** [comment]
It can't hurt to have the discussion there!

**Comment by msavy** [comment]
I think this is a great idea because at the moment it's a guessing game and
whack-a-mole.

We could even add add annotations and/or API registration points to allow
users and runtimes to say a particular type should be a primitive

**Comment by msavy** [comment]
I've sketched out an initial implementation of this and look forwards to discussing at the next meeting (today, I believe).

**Comment by msavy** [comment]
@MikeEdgar -- Have created a topic/ticket regarding this. Not sure if GH will notify you about the reference, so just letting you know: https://github.com/eclipse/microprofile-open-api/issues/364

**Comment by msavy** [comment]
@MikeEdgar @EricWittmann appreciate your opinion on this. Which of the following impls do you prefer (all are annoying as I need to add config state where stuff was fully static before)?

Solution 1: pass the config to static methods. https://github.com/msavy/smallrye-open-api/commit/4a15bf036e6d2979b3f116e8da0b45f13dbf3d68

Solution 2: add a callback mechanism that allows things statically interested in config to receive it when the project receives it from the container.  https://github.com/msavy/smallrye-open-api/commit/b9d4a886bbdccb6e3033bd9abad3421887df1889

Solution 3: statically initialise/pass config somewhere during startup (i.e. opposite direction to Solution 2)

I have my own thoughts, but don't want to bias feedback.

p.s. what should `java.time.LocalDate` be?

**Comment by MikeEdgar** [comment]
To start, I think `java.time.LocalDate` is definitely a plain date (without time).

Solution 3 seems interesting, depending on how coupled the configuration is with the components that use it. It might be handy to add a couple of factory methods to `OpenApiConfig` - one with a `Config` argument (e.g. `newInstance(Config config)` for unit tests to initialize an instance), and one with no arguments (used within the implementation code) that would load the `Config` from the `ConfigProvider` if no singleton instance already exists.

Solution 2 is pretty cool, but it might be a problem for unit tests (not sure). What I mean is - if a config consumer registers itself in a static block, what happens in the second or third unit test where a different config is set? I don't believe that static block would always run again for the consumer to be updated via the callback. Different configuration settings might bleed into other unit tests also if values are added to the `TYPE_MAP` as they are discovered.

For solution 1, I would suggest instead having some sort of "context" class that is passed around that holds (at least) the config and the Jandex index. Those two are used, or may be used, in many places.

--

All said, I think I might like solution 3 the best - using some static method to get a config (non-final) static single instance.

**Comment by msavy** [comment]
Mike -- Solution 2 works with all unit tests (all green). It uses the same global initialiser as the main test-suite already does (i.e. OpenAPIDocument is initialised and passed in a config before the tests start) -- I just copied it over.

Good point you might want to re-initialise/change config: we can easily change that by using a list of callbacks instead of a stack, and calling them whenever someone calls the global init method (as already happens in the non-schema tests). That would enable config changes to be distributed.

That's already going to be weird one edge-case situation: we cache the lookups (recommended by the MP config docs), so if you flip-flopped on definitions of the same item you'd need to clear out the static cache. The answer to that could be the same as above -- reset the cache to default if a new config is passed in.

**Comment by msavy** [comment]
Also great feedback on the other 2 items -- thanks. Will wait for other comments before weighing in myself.

**Comment by EricWittmann** [comment]
I was prepared to prefer solution (1) as that is what Marc and I talked about and I didn't think it would be quite as impactful as it is.  After seeing the scope of the changes, I definitely think that either (2) or (3) are much better.  I don't have a strong opinion between the two, although I'm not sure I see the benefit of a callback mechanism vs. just having a static holder of some kind.  The latter seems a little bit easier all around...

**Comment by msavy** [comment]
@EricWittmann The reason I went for the callback is that I found the platform statically sets the `OpenApiDocument.INSTANCE.config()` config at some arbitrary time after startup; so from the TypeUtil's static{} initialiser's perspective, the global config was still null at when it was run. So I inverted the call such that config is injected when it is finally injected.

However, your idea of having an additional wrapper/holder indirection for config doesn't seem unreasonable to me. Perhaps I've used too much vert.x and everything looks like a callback ;-)!

**Comment by EricWittmann** [comment]
Right - I get why the callback is needed to solve the static initializer issue - but yeah I was thinking it's probably even a little simpler to just have a single static instance of the config somewhere and just always reference that.

**Comment by EricWittmann** [comment]
@msavy @MikeEdgar We can probably finish this up, right?

**Comment by msavy** [comment]
I was going to alter my solution to use the pattern that Mike recommend,
unless my solution is now redundant?

**Comment by EricWittmann** [comment]
Nope - I was just verifying that we had reached a consensus and the work could be completed.  I think that's true, yes?

**Comment by MikeEdgar** [comment]
Depending on the direction in eclipse/microprofile-open-api#364 I think the content of the property would be impacted here too - unless there are two properties. My reasoning for bringing up the JSON concept in the MP issue is to not limit things to just these two schema attributes.
