### ISSUE TITLE
OpenApiDataObjectScanner doesn't handle methods

### ISSUE THREAD

**Issue by atzoum** [smallrye/smallrye-open-api#149]
There is already a relevant TODO in the source code, wondering if this is planned to be implemented at some point. I consider it to be a common use case to have to add OpenAPI schema annotation on a getter method (e.g. when dealing with interfaces) and swagger's scanner seems to support it as well.
 
https://github.com/smallrye/smallrye-open-api/blob/a87b278e7abe93eada7028a56c494c848f8496de/implementation/src/main/java/io/smallrye/openapi/runtime/scanner/OpenApiDataObjectScanner.java#L229-L230

**Comment by MikeEdgar** [comment]
This request dovetails nicely with the usage of annotations for sorting schema properties (#87). @atzoum, would you mind leaving an example model and expected output?

**Comment by msavy** [comment]
One complication to keep on mind is that you generally don't know the name
of method arguments (without additional compiler flags). That was one of
the reasons I didn't do this on first pass.

I know some other frameworks use secondary annotations and similar to
provide this. It's always a bit messy though and I don't think there's a
standard for this in the spec.

**Comment by MikeEdgar** [comment]
The way I'm thinking about this one is to use the methods based on the method name, in alignment with the bean property convention. E.g., all three of the elements below should be considered together.

```java
private String field;
// return type == type of field, zero arguments
public String getField() {
    return this.field;
}
// void return type, single argument with type == type of field
public void setField(String field) {
    this.field = field;
}
```
Jsonb also requires that getters/setters without an associated field be serialized/de-serialized, so it seems none of the elements are required in all cases.

**Comment by atzoum** [comment]
@msavy why are method argument names important in this context? Getters don't have arguments. 

The following interface
```
public interface MySchema {
    @Schema(required=true)
    String getField1();
    @Schema(name="anotherField", required=true)
    String getField2();
}
```
Should produce something like
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MySchema",
  "type": "object",
  "required": [
    "anotherField"
  ],
  "properties": {
    "field1": {
      "type": "string"
    },
    "anotherField": {
      "type": "string",
      "description": "The person's last name."
    }
  }
}
```

**Comment by EricWittmann** [comment]
!! I was just reading @atzoum's comment and wondering where the description for `anotherField` came from when the comment was edited, GitHub auto-updated the content, and the description disappeared.  That was fantastic timing.

In any case, I agree about standard java bean methods - those should be handled as expected based on bean semantics.  That seems pretty straightforward.

**Comment by msavy** [comment]
Okay, that sounds good! Was thinking of more complex cases that probably
aren't necessary if we just use that pattern.

**Comment by atzoum** [comment]
@MikeEdgar thanks for instantly picking this task up! Ι did some comments in your PR, its good to see that you are now taking into consideration both Jsonb and Jackson annotations.
