### ISSUE TITLE
Process @RolesAllowed while generating OpenAPI doc from annotations

### ISSUE THREAD

**Issue by dvddhln** [smallrye/smallrye-open-api#15]
Hello,
I raised a discussion whether this would be possible to support. Would be interesting to investigate any future support or enhancement of this kind. Let me know if I am out of line though :)

https://github.com/eclipse/microprofile-open-api/issues/244

BR

David

**Comment by EricWittmann** [comment]
I think this might be a nice addition to the annotation scanner.  If we see `@RolesAllowed` perhaps we can use that information to add a Security Requirement to the OAI Operation being generated.

**Comment by dvddhln** [comment]
I thought about this a little more and wondered about if `@DeclaredRoles` could be picked up aswell. This plays well with the `@RolesAllowed` set on the operation. For instance if you are filtering the security scheme this would be the example. Just a suggestion though :)

```
public SecurityScheme filterSecurityScheme(SecurityScheme securityScheme) {

        OAuthFlows flows = OASFactory.createObject(OAuthFlows.class);
        OAuthFlow flow = OASFactory.createObject(OAuthFlow.class);

        DeclareRoles declareRoles = getDeclaredAnnotation(DeclareRoles.class);

            for (String role : declareRoles.value()) {

                Scopes scope = OASFactory.createObject(Scopes.class);
                scope.addScope(role,"");
                flow.setScopes(scope);
            }
        
        flows.setImplicit(flow);
        securityScheme.setFlows(flows);

        return securityScheme;
    }
```

**Comment by MikeEdgar** [comment]
I was thinking about this enhancement and I was wondering if anyone with MP JWT history knows why `groups` was chosen instead of `scope` as the claim to hold user "roles"? It seems out of alignment with the OpenAPI document  format. That is, the runtime requires (by default) that the roles be located in `groups`, but broadcasts in the OAI that they should be scopes.

@sberyozkin, any thoughts?

**Comment by MikeEdgar** [comment]
Regardless of the naming differences, this would be very useful. I think a reasonable approach to this is to only use the information from `@DeclaredRoles` and/or `@RolesAllowed` when a `@SecurityScheme` has been provided in the annotation model where the `type` is `OPENIDCONNECT` or `OAUTH2`. There may be too many required/context sensitive values in the security model to generate it without additional input from the application.

1) Add `@DeclaredRoles` values to flows already defined by the `@SecurityScheme`
2) Add `@RolesAllowed` values to the scopes of any existing `SecurityRequirement` for an operation or generate a `SecurityRequirement` if only a single `@SecurityScheme` has been declared.
3) Add `@RolesAllowed` values to flows already defined by the `@SecurityScheme` if no `@DeclaredRoles` is present, or the allowed roles were not present in the `@DeclaredRoles`.
4) Information from the static file or `OASModelReader` would not be considered for activating the logic above.

**Comment by EricWittmann** [comment]
I think that's a very good approach, and if anything is missing (I can't think of anything) then can be added later.

**Comment by sberyozkin** [comment]
@MikeEdgar, I'm not aware why. But we can map pretty much any claims now to the `groups`claim in `smallrye-jwt`
