### ISSUE TITLE
@Schema type doesn't override return type

### ISSUE THREAD

**Issue by cylinder47** [smallrye/smallrye-open-api#1507]
The following resource:

```java
@Path("/hello")
public class ExampleResource {

    @GET
    @Schema(type = SchemaType.STRING)
    public Object hello() {
        return "Hello world";

    }
    
    record Greeting(@JsonValue String value) {}

}
```

generates:

```yaml
---
openapi: 3.0.3
info:
  title: demo API
  version: 1.0-SNAPSHOT
paths:
  /hello:
    get:
      tags:
      - Example Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
components:
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
```

Is this behavior expected? I'd expect that that the return type would be: 

```yaml
application/json:
   schema:
      type: string
```

What I would like be able to do in the end is to override the type as:
```java
@Schema(description = "A greeting", type= STRING)
record Greeting(@JsonValue String value) {}
```
which doesn't work either.

I use quarkus and have imported `smallyrye-open-api` with:
```xml
<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
</dependency>
```

**Comment by MikeEdgar** [comment]
@cylinder47 using `@Schema` directly on the REST method isn't support. You can try to place one of the following directly on the REST method instead:
```java
@APIResponseSchema(String.class)
```
or
```java
@APIResponse(content = @Content(schema = @Schema(type = SchemaType.STRING)))
```

**Comment by cylinder47** [comment]
I see, reasonable since the response has more states than just the response body. I tried to condense the issue I had to make it simpler to describe but apparently I took it too far...

What I'm really after is that I want to unwrap the value object's type in the openapi-definition.

From the following: 

```
@Path("/hello")
public class ExampleResource {
    @GET
    public HelloResponse hello() {
        return new HelloResponse(new Greeting("Hello world"));
    }

    record HelloResponse(Greeting greeting){}

    @Schema(description = "A greeting", type = STRING)
    record Greeting(@JsonValue String value) {
    }
}
```

I receive the openapi.yaml file:

```
---
openapi: 3.0.3
info:
  title: demo API
  version: 1.0-SNAPSHOT
paths:
  /hello:
    get:
      tags:
      - Example Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
components:
  schemas:
    Greeting:
      $ref: '#/components/schemas/Greeting'
    HelloResponse:
      type: object
      properties:
        greeting:
          $ref: '#/components/schemas/Greeting'
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic

```

Note that the `Greeting` component is empty and refers to itself (?).  I am not sure what I expect here, either that `Greeting` simply is an alias for `type: string` or that `Greeting` doesn't appear in the schema at all but is replaced by a `type: string` all together.

**Comment by MikeEdgar** [comment]
> Note that the `Greeting` component is empty and refers to itself (?)

This was a recent bug that should be fixed in the newest Quarkus version. What version of smallrye-open-api is in your dependency tree?

**Comment by cylinder47** [comment]
The included version of smallrye-open-api-core in the example is 3.3.4. The quarkus version is 3.1.3.Final

**Comment by cylinder47** [comment]
I guess this is the issue you refer to https://github.com/quarkusio/quarkus/issues/34233?

**Comment by cylinder47** [comment]
It worked with the most recent quarkus update. :) I'll close this issue. Thanks @MikeEdgar
