### ISSUE TITLE
Gradle task writes out JSON in the YAML file

### ISSUE THREAD

**Issue by dimurgos** [smallrye/smallrye-open-api#1532]
The following line writes out the json serialized value instead of the serialized yaml that is generated at the top of this method. 

https://github.com/smallrye/smallrye-open-api/blob/7abb44784ba4d9bda5e90188e40f8a600d850a0d/tools/gradle-plugin/src/main/java/io/smallrye/openapi/gradleplugin/SmallryeOpenApiTask.java#L319

**Comment by phillip-kruger** [comment]
Do you want to provide a PR with the fix ?
