### ISSUE TITLE
Swagger annotations OAS 3

### ISSUE THREAD

**Issue by darkmoonbzh** [smallrye/smallrye-open-api#1545]
Hi,

is it planned to upgrade in order to take into account the swagger annotations?  for example for this imports

`import io.swagger.v3.oas.annotations.Operation;`
`import io.swagger.v3.oas.annotations.media.Content;`
`import io.swagger.v3.oas.annotations.media.Schema;`
`import io.swagger.v3.oas.annotations.responses.ApiResponse;`
`import io.swagger.v3.oas.annotations.responses.ApiResponses;`
`import io.swagger.v3.oas.annotations.tags.Tag;`

Sincerely

**Comment by phillip-kruger** [comment]
We do not support swagger annotations at the moment. There is an issue for an enhancement to add support (see #752)

For now you need to use the microprofile annotations.

**Comment by phillip-kruger** [comment]
Duplicate of #752
