### ISSUE TITLE
@Schema causes self-reference on field's type 

### ISSUE THREAD

**Issue by cylinder47** [smallrye/smallrye-open-api#1565]
## Problem

The addition of `@Schema` on a class with value object members randomly causes a self-reference on the value object's open API definition. 

This problem is different from https://github.com/smallrye/smallrye-open-api/issues/1466 and https://github.com/smallrye/smallrye-open-api/issues/1507 in that the owning class's `@Schema` annotation causes this issue.

## How to replicate

The following code 
```java
@ApplicationScoped
@Path("/")
public class Resource {
    @GET
    public MyClass getMyClass(){
       return new MyClass(new MyValueClass());
    }

    @Schema(description = "some description") // <-- Removal of this schema annotation yields expected type of value the object.
    public record MyClass(MyValueClass alongerRecord1) {
    }

    @Schema(type = SchemaType.STRING)
    public record MyValueClass() {
    }
}
```

yields the `openapi.yaml`:

```yaml
---
openapi: 3.0.3
info:
  title: openapi-swaggerui-quickstart API
  version: 1.0.0-SNAPSHOT
paths:
  /:
    get:
      tags:
      - Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyClass'
components:
  schemas:
    MyClass:
      description: some description
      type: object
      properties:
        alongerRecord1:
          $ref: '#/components/schemas/MyValueClass'
    MyValueClass:
      $ref: '#/components/schemas/MyValueClass'  # <--- self-reference
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
```

There seems to be some randomness  to the presence of the self-reference dependent on the classes' names. Most of the times there is a self reference but I have received the expected string type of the value class. Changing a value object's class name may cause the correct schema to appear on the value-object type.

We use quarkus version 3.3.1 and the example above is based on https://quarkus.io/guides/openapi-swaggerui.

**Comment by pe-st** [comment]
I've "discovered" this bug as well in a Quarkus 3.4.x project (with smallrye-open-api 3.5.2). In my case the generated openapi was correct on Windows and Ubuntu, but wrong on macOS. Only when I could reproduce the problem (i.e. when I knew where to look) I discovered that the issue was already reported and fixed.

@MikeEdgar Would you be interested in a PR with the test case? See https://github.com/pe-st/smallrye-open-api/commit/fd05651c8cfcfe0304f6203c4ca19406925f4a84

**Comment by MikeEdgar** [comment]
Hi @pe-st , yes that would be good to have, I commented on the commit as well. If you don't mind, the test method might be better named to describe how it's checking that self-referencing schemas are not generated, regardless of scan order.

**Comment by pe-st** [comment]
Thanks for your feedback @MikeEdgar , I improved the test and opened PR 1636
