### ISSUE TITLE
Snapshot repo & Release of "smallrye-open-api-1.1"

### ISSUE THREAD

**Issue by michael-schnell** [smallrye/smallrye-open-api#157]
Is there any Maven snapshot repository available that has "smallrye-open-api-1.1" and when will this code officially be released?

**Comment by kenfinnigan** [comment]
1.0.2 of `smallrye-open-api-1.1` is already available in Central: https://mvnrepository.com/artifact/io.smallrye/smallrye-open-api-1.1

**Comment by michael-schnell** [comment]
Cool. Didn't find it via the Maven Central Search...
