### ISSUE TITLE
Add support for new Jakarta EE RESTful Web Services multi-part form 

### ISSUE THREAD

**Issue by tjquinno** [smallrye/smallrye-open-api#1571]
Jakarta REST 3.1 now supports multipart form data https://github.com/jakartaee/rest/issues/418 

It would be great if SmallRye OpenAPI added support for this.

**Comment by MikeEdgar** [comment]
@tjquinno I checked this again and I don't think there are any scanner changes to support this. Using the existing annotations to document multipart form properties is the way to go. If this appears to not be the case, we can revisit/reopen this issue.
