### ISSUE TITLE
Incorrect open api document generation when a resource uses an array of ZonedDateTime

### ISSUE THREAD

**Issue by mrickly** [smallrye/smallrye-open-api#1573]
Given 
```
@ApplicationScoped
@Path("a")
public class ARestResource {

    @GET
    @Operation(summary = "a")
    @Produces(MediaType.APPLICATION_JSON)
    public ZonedDateTimeArrayWrapper get() {
        return new ZonedDateTimeArrayWrapper();
    }

}
```
with 

```
public class ZonedDateTimeArrayWrapper {

    ZonedDateTime[] now;

    public ZonedDateTime[] getNow() {
        return now;
    }

    public void setNow(ZonedDateTime[] now) {
        this.now = now;
    }

}
```

Then the generated open api yaml file does not contain the schema for ZonedDateTime. Worse, since the schema is registered in the schema registry (but not in the open api document), if another resource which also uses a ZonedDateTime is processed afterwards (e.g. BRestResource), then the type will not be reprocessed. In the end, you get an invalid open api yaml file.

Tested with smallrye-open-api version 3.5.1 via quarkus-smallrye-openapi version 3.3.3

**Comment by MikeEdgar** [comment]
Thanks for reporting this, I was able to reproduce it locally.
