### ISSUE TITLE
Wrong example and dead link in description for Time

### ISSUE THREAD

**Issue by ChMThiel** [smallrye/smallrye-open-api#1587]
There are two little bugs in in [TypeUtil](https://github.com/smallrye/smallrye-open-api/blob/13fdf1e79ca467f6e0d286da938113c27287b6e3/core/src/main/java/io/smallrye/openapi/runtime/util/TypeUtil.java#L94):

- The example-value has a typo: Instead of 13:45.30.123456789 it should be 13:45:30.123456789 (colon instead of dot)
- The link  to the RFC of LocalTime  https://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14 is dead.
Better use https://www.rfc-editor.org/rfc/rfc3339.html#page-4.

**Comment by MikeEdgar** [comment]
Thanks for the report @ChMThiel . Let's go with the link of `https://www.rfc-editor.org/rfc/rfc3339.html#section-5.6` . I think the `#section-5.6` fragment is the same section previously referenced by the old link.

Do you have any interest/time in preparing a PR with the fix?

**Comment by phillip-kruger** [comment]
I'll fix this for the next release

**Comment by ChMThiel** [comment]
Thanks @phillip-kruger.
I'd have done it myself, but we had a holiday here in germany and now i'm to late ;)

**Comment by phillip-kruger** [comment]
Sorry...
