### ISSUE TITLE
Quarkus: Custom ObjectMapper 

### ISSUE THREAD

**Issue by melloware** [smallrye/smallrye-open-api#1600]
cc @phillip-kruger cc @MikeEdgar 

Phillip asked me to open this from a Quarkus Zulip conversation.   Let me explain what is happening.

1. I have a JAR of already generated POJO's from OpenAPI Generator I am re-using.  It has fields declared like this.

```java
private JsonNullable<String> directorySize = JsonNullable.<String>undefined();
```

2. When I generate using Microprofile automatic generation in Quarkus it generates the spec like this.

```json
 "directorySize" : {
            "$ref" : "#/components/schemas/JsonNullableString"
},

"JsonNullableString" : {
        "type" : "object",
        "properties" : {
          "value" : {
            "type" : "string"
          },
          "isPresent" : {
            "type" : "boolean"
          },
          "present" : {
            "type" : "boolean"
          }
        }
},
```

3. What I expected was my custom ObjectMapper which is produced uses the `JsonNullable` module to decode these.

```java
import com.fasterxml.jackson.databind.ObjectMapper;
import io.quarkus.jackson.ObjectMapperCustomizer;
import jakarta.inject.Singleton;
import org.openapitools.jackson.nullable.JsonNullableModule;

@Singleton
public class JacksonModuleCustomizer implements ObjectMapperCustomizer {

    public void customize(ObjectMapper mapper) {
        mapper.registerModule(new JsonNullableModule());
    }
}
```

4. I was expecting this to be used and it to deserialize properly to:

```json
"directorySize" : {
       "type" : "string"
},
```

5. However https://github.com/smallrye/smallrye-open-api/blob/main/core/src/main/java/io/smallrye/openapi/runtime/io/OpenApiSerializer.java#L41
Smallrye OpenApi always creates a `new ObjectMapper()` for each schema that should be written to disk.
This new ObjectMapper does not take any settings from the Quarkus ObjectMapper into account.

**Comment by MikeEdgar** [comment]
As mentioned in #1603, I think the `ObjectMapper` used to serialize the OpenAPI model is separate from how the model itself is constructed. The latter is the issue here. My understanding of `JsonNullable` is that it should function basically the same way as an `Optional`. Does that match your expectation?

**Comment by melloware** [comment]
I think yes.  All of the JsonNullable types could be treated as Optional by the scanner.

**Comment by melloware** [comment]
@MikeEdgar do you need me to create a small Quarkus reproducer for you?

**Comment by MikeEdgar** [comment]
Thanks @melloware , usually I'd say yes, but this one is pretty straight-forward. I'm now thinking about whether this would be better as a configurable option versus coding direct support for `JsonNullable`.
