### ISSUE TITLE
maven-plugin: @ApplicationPath JAX-RS annotation does not work sporadically

### ISSUE THREAD

**Issue by tuffnatty** [smallrye/smallrye-open-api#1607]
A related discussion is #1085. But here is a small self-contained example where there are no multiple `Application` classes, still the generated spec contains no traces of the value specified with `@ApplicationPath`: https://github.com/tuffnatty/smallrye-openapi-appath-example .

Actually I started making the example while chasing the bug where in my app, `@ApplicationPath` works when Maven is called from command-line but breaks when called using m2e Eclipse integration. But I was unable to make the simple example work even from command-line.

**Comment by MikeEdgar** [comment]
@tuffnatty how are you invoking the Maven command? It works for me with `mvn package`

**Comment by tuffnatty** [comment]
@MikeEdgar  `mvn package` it is. 
```
MacBook-Pro% echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/openjdk8-openj9/Contents/Home
MacBook-Pro% mvn --version
Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Maven home: /opt/local/share/java/maven3
Java version: 1.8.0_382, vendor: IBM Corporation, runtime: /mpool/opt/local18/Library/Java/JavaVirtualMachines/openjdk8-openj9/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

**Comment by tuffnatty** [comment]
The generated YAML:
```
cat target/generated/openapi.yaml
---
openapi: 3.0.3
info:
  title: My API
  description: Here is a very long API description in Markdown format.
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "0.1"
servers:
- url: /appath-example/
paths:
  /application.wadl:
    get:
      responses:
        "200":
          description: OK
  /application.wadl/{path}:
    get:
      parameters:
      - name: path
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
```

**Comment by tuffnatty** [comment]
@MikeEdgar With the example app, I always get wrong results when using JDK 1.8 or 17, and always get right results when using JDK 11.

**Comment by tuffnatty** [comment]
@MikeEdgar I've added a Github workflow for the example. At first, it worked correctly in JDK 1.8, but failed to build with JDK 11/17 due to missing `maven.compiler.source|target` properties. After I have added these (with 1.8 hardwired for all JDK versions in the build matrix):
- the JDK 1.8 build started producing wrong results again
- the JDK 11 build started to build and is producing wrong results
- the JDK 17 stilll does not build, probably wants a fresher war plugin

**Comment by tuffnatty** [comment]
@MikeEdgar I've updated `maven-war-plugin` to current version in the example. Now JDK 1.8 and 17 work as they should, but JDK 11 drops `ApplicationPath`: https://github.com/tuffnatty/smallrye-openapi-appath-example/actions/runs/6468566009/job/17560848629

**Comment by tuffnatty** [comment]
And then, when I also update maven-compiler-plugin, things are inverted: only JDK 11 works, JDK 1.8 and 17 are broken:
https://github.com/tuffnatty/smallrye-openapi-appath-example/actions/runs/6468695426

**Comment by MikeEdgar** [comment]
@tuffnatty do you need/want the WADL endpoints included in the OpenAPI? It looks like Jersey packages a few other `Application` classes and they are overriding the one in your code.

You can ignore them with this property configured on the plugin, but it also removes the WADL endpoints.
```xml
<scanExcludePackages>org.glassfish.jersey.server</scanExcludePackages>
```

**Comment by tuffnatty** [comment]
@MikeEdgar Thank you! Yes, adding this property fixes the generated spec but removes the WADL endpoints.
I do not care much for the inclusion of WADL endpoints in OpenAPI, I can live with this workaround.

But it does not seem my `Application` was exactly ignored, as the spec carries `info` and `title` from my `Application`. It looks like annotations from all `Application` classes are taken but then selectively (or randomly) ignored. It's an unexpected behaviour which probably could be prevented.

**Comment by MikeEdgar** [comment]
The OpenAPI annotations on the `Application` are merged, but the last-encountered one is the one that determines the path. That explains the difference between the JDKs versions as the order those classes are processed is not defined.

**Comment by MikeEdgar** [comment]
@tuffnatty , let me know if there's anything else to discuss on this one or please feel free to close when you're ready.

**Comment by MikeEdgar** [comment]
Closing for now since the suggested configuration option resolved the issue. Please re-open if you'd like to discuss further or believe this hasn't been resolved.

**Comment by tuffnatty** [comment]
Thanks! I do still encounter weird behaviour on another PC in Eclipse vs. CLI building where the generated API is completely empty when built with Eclipse, but I have to collect more data on this. Probably it's also worth another issue.
