### ISSUE TITLE
Unable to apply OASFilter to smallryeAPI extension

### ISSUE THREAD

**Issue by pradeepbavirisetty** [smallrye/smallrye-open-api#1610]
Hi Team,

i am getting  below error while applying CustomFilter to smallryeOpenApi and i tried to configured the filter class from configproperties and directly set to filters as well . I am sending the configurations which used in my application. 

: io.smallrye.openapi.runtime.OpenApiRuntimeException: java.lang.ClassNotFoundException: com.test.utils.OASInternalAPIFilter
        at io.smallrye.openapi.runtime.OpenApiProcessor.uncheckedCall(OpenApiProcessor.java:293)
        at io.smallrye.openapi.runtime.OpenApiProcessor.newInstance(OpenApiProcessor.java:276)
        at io.smallrye.openapi.runtime.OpenApiProcessor.getFilter(OpenApiProcessor.java:267)
        at io.smallrye.openapi.runtime.OpenApiProcessor.getFilter(OpenApiProcessor.java:255)

**configurations which i was set in build.gradle**

plugins {
 id('io.smallrye.openapi') version('3.6.2')
}

smallryeOpenApi {
    //filter.set("com.test.utils.OASInternalAPIFilter")
    infoTitle.set("Test Application")
    schemaFilename.set("testswagger")
    configProperties.set(file("src/main/resources/openapi.properties"))
} 

**src/main/resources/openapi.properties**

mp.openapi.servers=/test
mp.openapi.scan.packages=com.test.controller
mp.openapi.filter=com.test.utils.OASInternalAPIFilter

**Comment by MikeEdgar** [comment]
Hi @pradeepbavirisetty , can you share a small project that reproduces the issue?

**Comment by bhanupriya123** [comment]
Hello @MikeEdgar , On behalf of @pradeepbavirisetty , we would like to know when this fix will be available?
