### ISSUE TITLE
Subresource Paths are not grouped under Resource Tags

### ISSUE THREAD

**Issue by jbuvv** [smallrye/smallrye-open-api#1618]
Hello!

We are using the following Pattern in our Application:

```java
@Tag("My Tag")
@Path("/myparent")
@ApplicationScoped
class MyResource {
  @Inject MySubResource r;
  @Path("/mysub")
  public MySubResource getMySubResource() { return r; }
}
```

```java
@ApplicationScoped
class MySubResource {
  @GET
  @Path("/hello")
  @Operation(summary = "myop")
  public String getHello() { return "hi"; }
}
```

So we have just a single Endpoint '/myparent/mysub/hello'.
I would expect the EP to have the "My Tag"-Tag but instead it has none.

I suspect the Tag is missing because the Tags are not forwarded to the function that processes the subresources:
https://github.com/smallrye/smallrye-open-api/blob/2f9273551c90825f50700f2a6e9290e25886e364/extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java#L294

Is that the intended behavior?

**Comment by MikeEdgar** [comment]
I'd say this is a bug, also discussed in #1546. Just like a `@Tag` on a resource method overrides a `@Tag` on the parent resource class, it would probably make sense to a `@Tag` on the subresource producer method to override a `@Tag` present on the sub-resource class.

`@Tag` order of priority:
1. Directly on resource method
2. On nearest subresource producer method (when operation is in a subresource)
3. On nearest subresource class (when operation is in a subresource)
4. On root resource class
