### ISSUE TITLE
Support for kotlin.Deprecated annotation while degenrating the Open API

### ISSUE THREAD

**Issue by lmouline** [smallrye/smallrye-open-api#1661]
**Description**
While using the Kotlin `@Deprecated` annotation, the endpoint is not marked as deprecated in the OpenAPI specification. 
It works fine though while using the `java.lang.Deprecated` annotation. Issue is that this annotation is marked as depracted by Kotlin.

**How to reproduce**
- Generate a Quarkus project with `Kotlin` and `smallrye-openapi` dependencies
- Add the Kotlin `@Deprecated` tag to a resource or endpoint definition

**Expected result**
Endpoint is marked as deprecated

**Observed result**
No changes on the endpoint specification 

**Example using only Kotlin**
```kotlin
@GET
@Path("/kotlin")
@Produces(MediaType.TEXT_PLAIN)
@Deprecated("Deprecated")
fun helloDeprecatedKotlin() = "Hello from RESTEasy Reactive"
```

Generates the following specification:
```yaml
/hello/kotlin:
    get:
      tags:
      - Greeting Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
```

**Example using only Java**
```kotlin
@GET
@Path("/java")
@Produces(MediaType.TEXT_PLAIN)
@java.lang.Deprecated(since="Deprecated")
fun helloDeprecatedJava() = "Hello from RESTEasy Reactive"
```

Generates the following specification:
```yaml
/hello/java:
    get:
      tags:
      - Greeting Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
      deprecated: true
```

Here the project used for that: https://github.com/lmouline/quarkus-smallrye-open-api-kotlin-deprecated-issue

**Comment by MikeEdgar** [comment]
Hi @lmouline , thanks for the issue. I took a quick look at this and it should be simple to implement. Do you have any interested in submitting a PR with the change?

1. Add a new constant for the Kotlin deprecated annotation to `io.smallrye.openapi.api.constants.KotlinConstants` in the `core` module.
2. Again in the `core` module, update `io.smallrye.openapi.runtime.util.TypeUtil`'s `mapDeprecated` method to find either annotation.
   ```java
   ...
   AnnotationInstance deprecated = Annotations.getAnnotation(target,
       Arrays.asList(
           JDKConstants.DOTNAME_DEPRECATED,
           KotlinConstants.DOTNAME_DEPRECATED));
   ...
   ```

**Comment by lmouline** [comment]
Sure with pleasure!   
Will do that tomorrow ;)

**Comment by MikeEdgar** [comment]
Thanks @lmouline ! It would probably be good to adjust one of the current Kotlin test cases to check it as well. The `testsuite/data` module has a few Kotlin classes where you can add a deprecated field and adjust the associated expected JSON (probably in `core`) accordingly.

**Comment by lmouline** [comment]
Many thanks @MikeEdgar for having given me this opportunity! :)
