### ISSUE TITLE
Conflicting small rye jandex libraries 

### ISSUE THREAD

**Issue by pradeepbavirisetty** [smallrye/smallrye-open-api#1664]
Hi Team,

plugins {
   id ("io.smallrye.openapi") , version ("3.7.0")
}

dependencies {
    implementation "io.smallrye:smallrye-open-api-core:2.1.16" // this must be required for openapi ui build
}

While running the project, I am  getting error "org.jboss.jandex.UnsupportedVersion: Can't read index version 11; this IndexReader only supports index versions 2-3,6-10" 

In run time i required 2.4.3.Final generated jandex file but in some reason io.smallrye:jandex:3.1.5 generated file is getting added to my jar file under META-INF/jandex.idx. due to this i am getting above error. if i skip generateopenapiSpec task in my build time its working fine. 

Thanks,
Pradeep

**Comment by MikeEdgar** [comment]
Thanks for reporting @pradeepbavirisetty . I'll try to take a look at this soon.

**Comment by MikeEdgar** [comment]
@pradeepbavirisetty can you provide a small reproducer project that demonstrates the issue?

**Comment by ruchi-rani** [comment]
[helidon-quickstart-mp (2).zip](https://github.com/smallrye/smallrye-open-api/files/13673209/helidon-quickstart-mp.2.zip)

**Comment by MikeEdgar** [comment]
@pradeepbavirisetty , running a build with that project results in a Jandex index with format version v6 (compatible with 2.0.x [1]) and the OpenAPI document generates. What steps are you taking to build/run the project?

[1] https://smallrye.io/jandex/jandex/3.1.6/index.html#persistent_index_format_versions

**Comment by ruchi-rani** [comment]
@MikeEdgar ,
using id('io.smallrye.openapi') version('3.7.0') for smallrye plugin. 
for running the project ->     java -jar <jar_name>

**Comment by MikeEdgar** [comment]
@ruchi-rani it seems the sample project is not producing a runnable jar:
```
$ java -jar build/libs/helidon-quickstart-mp-unspecified.jar 
no main manifest attribute, in build/libs/helidon-quickstart-mp-unspecified.jar
```
What am I missing?

**Comment by MikeEdgar** [comment]
@ruchi-rani is this still an issue? I wasn't able to reproduce it earlier.

**Comment by MikeEdgar** [comment]
Closing due to lack of feedback.
