### ISSUE TITLE
Allow defining arrays with multiple types of items

### ISSUE THREAD

**Issue by mklueh** [smallrye/smallrye-open-api#1683]
Hello. I found this [issue ](https://github.com/eclipse/microprofile-open-api/issues/425)in the microprofile repository and participated there, as I`m missing a feature that should exist according to the specification:

using Schema with anyOf / oneOf / allOf

```
@Data
@Builder
@AllArgsConstructor
public class SomeResponseObject {

    private long page;

    private long pages;

    @Schema(type = ARRAY, oneOf = {SomeItem.class, SomeOtherItem.class})
    private List<BaseClass> items;
}
```

Which however, against expectations leads to this schema

```
 "SomeResponseObject" : {
        "type" : "object",
        "properties" : {
          "page" : {
            "format" : "int64",
            "type" : "integer"
          },
          "pages" : {
            "format" : "int64",
            "type" : "integer"
          },
          "items" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BaseClass"
            },
             "oneOf" : [ {
              "$ref" : "#/components/schemas/SomeItem"
            }, {
              "$ref" : "#/components/schemas/SomeOtherItem"
            } ]
          }
        }
      },
```

which generates his typescript object
```
    SomeResponseObject: {
      /** Format: int64 */
      page?: number;
      /** Format: int64 */
      pages?: number;
      items?: components["schemas"]["SomeItem"] | components["schemas"]["SomeOtherItem"];
    };
```

This is the current vs the expected result discussed here https://github.com/drwpow/openapi-typescript/issues/1421#issuecomment-1792334575:

![image](https://github.com/eclipse/microprofile-open-api/assets/1553757/2b93a582-14f7-437a-b256-47aa98b5f6ef)

The guys from Eclipse have provided multiple solution ideas like this

https://github.com/eclipse/microprofile-open-api/issues/425#issuecomment-1820789794

```
    @Schema(type = ARRAY, items = @PropertySchema(oneOf = {BaseClass.class, SomeItem.class, SomeOtherItem.class}))
    private List<BaseClass> items;
```

which would apply the Schema to the Item(s) instead of the list property.

As the issue is already **almost 4 years** old and I'm not sure how the relation between the Eclipse and the Smallrye project is, I have doubts that a solution will find its way into the Quarkus ecosystem anytime soon. That's why I repost it here.

**Comment by MikeEdgar** [comment]
Hi @mklueh, I am a contributor to both projects. The SmallRye implementation of MP OpenAPI aims to follow the spec as closely as possible and of course pass the TCK tests. Generally, we avoid extending the API (adding annotations or new interfaces). 

Until the change is available in the MP OpenAPI spec to specify `items` in a `@Schema`, a common pattern is to use an intermediate class to hold the item schema, example below. You don't need to use the class in your application, it only needs to be declared with the annotations as shown.

```java
@Data
@Builder
@AllArgsConstructor
public class SomeResponseObject {

    private long page;

    private long pages;

    @Schema(implementation = BaseClassSchema[].class)
    private List<BaseClass> items;

    @Schema(oneOf = { SomeItem.class, SomeOtherItem.class })
    private static class BaseClassSchema { /* Schema marker class only */ }
}
```

**Comment by mklueh** [comment]
@MikeEdgar thanks for the clarification and the workaround :) I'll try that out

**Comment by MikeEdgar** [comment]
@mklueh , you could of course place `@Schema(oneOf = { SomeItem.class, SomeOtherItem.class })` directly on `BaseClass` for a similar result.

**Comment by mklueh** [comment]
@MikeEdgar thank you, seems to work :)

**Comment by MikeEdgar** [comment]
@mklueh would you be OK with closing this issue? We'll need to work in the spec project anyway to make the enhancements to the annotations that is being discussed there.

**Comment by mklueh** [comment]
@MikeEdgar sure 😊
