### ISSUE TITLE
Regression: OpenAPI scanner reports duplicate operation id for exactly the same methods of the same class

### ISSUE THREAD

**Issue by snazy** [smallrye/smallrye-open-api#1688]
I see issue #1379 happening (again) in [our project](https://github.com/projectnessie/nessie), via Quarkus 3.6.3, using smallrye-open-api-core 3.7.0:

```
SROAP07903: Duplicate operationId: %s produced by Class: %s, Method: %s and Class: %s, Method: %s
SROAP07903: Duplicate operationId: %s produced by Class: %s, Method: %s and Class: %s, Method: %s
SROAP07903: Duplicate operationId: %s produced by Class: %s, Method: %s and Class: %s, Method: %s
SROAP07903: Duplicate operationId: %s produced by Class: %s, Method: %s and Class: %s, Method: %s
SROAP07903: Duplicate operationId: %s produced by Class: %s, Method: %s and Class: %s, Method: %s
SROAP07903: Duplicate operationId: %s produced by Class: %s, Method: %s and Class: %s, Method: %s
SROAP07903: Duplicate operationId: %s produced by Class: %s, Method: %s and Class: %s, Method: %s
```
(Unfortunately, logging via Gradle eats up all the message formatting, but that's a different issue.)

Our REST classes basically all use the same inheritance model:
1. The implementation class [example](https://github.com/projectnessie/nessie/blob/64e5b458a877c5470ed56fa6cf30e3ebe3edaa5c/servers/services/src/main/java/org/projectnessie/services/impl/DiffApiImpl.java), which implements a ...
2. REST/OpenAPI annotated interface [example](https://github.com/projectnessie/nessie/blob/64e5b458a877c5470ed56fa6cf30e3ebe3edaa5c/api/model/src/main/java/org/projectnessie/api/v1/http/HttpDiffApi.java), which extends a ...
3. base interface (w/o) the REST/OpenAPI annotations ([example](https://github.com/projectnessie/nessie/blob/64e5b458a877c5470ed56fa6cf30e3ebe3edaa5c/api/model/src/main/java/org/projectnessie/api/v1/DiffApi.java)).

Looking into this issue in a debugger, I see in [`AnnotationScanner.processOperation`](https://github.com/smallrye/smallrye-open-api/blob/89b367a66a7cdca0956f701a0eaafbb02282cc3b/core/src/main/java/io/smallrye/openapi/runtime/scanner/spi/AnnotationScanner.java#L353) that `conflictingMethod` points to the exact same (not equal) object as `method` (so: `method == conflictingMethod`). This means, that the `Duplicate operationId` warning is a false-positive w/o a negative effect (for us).

Looking into this a bit deeper, in `AnnotationScanner.getResourceMethods()`, I see the following behavior:
1. It looks up the methods via `classInfo`, getting one in this example:
![image](https://github.com/smallrye/smallrye-open-api/assets/957468/5215d738-f37e-4956-ab51-f3a79dd9469d)
2. It then includes the interfaces, adding the base methods as well (same signature!):
![image](https://github.com/smallrye/smallrye-open-api/assets/957468/7f301db6-3ec7-44e9-ae8f-faf1d8c569cf)

IIUC to fix this issue, it would be the better approach to change `AnnotationScanner.getResourceMethods()` to be aware of overrides and not "blindly" add those (again). WDYT?

**Comment by snazy** [comment]
Thinking a bit more, it seems a more complex inheritance model could make it even worse (more warnings) like this (adding base classes to the inheritance `chain`):
```java
public class MyResourceImpl extends BaseResourceImpl implements TopInterface, BaseInterface {
  public myMethod() { ...; }
}
public class BaseResourceImpl implements BaseInterface {
  public myMethod() { ...; }
}
public interface TopInterface extends BaseInterface {
  @AllTheAnnotations public myMethod();
}
public interface BaseInterface {
  public myMethod();
}
```

**Comment by phillip-kruger** [comment]
You can have the operationId use the fully qualified name? What is your config for openapi?

**Comment by MikeEdgar** [comment]
@snazy , are you seeing the error once per operation? I noticed that you are using both the `javax` and the `jakarta` annotations on the example REST endpoint. The scanner does check for both and would (currently) process the `getDiff` method twice, once for each annotation.

I assume you have good reason for doing that, so maybe a `distinct()` after the HTTP method is parsed from the JAX-RS annotation would eliminate the problem.

https://github.com/smallrye/smallrye-open-api/blob/e022c14c2d9778067bfcfa967e44c6a1230c1fb0/extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/JaxRsAnnotationScanner.java#L286

Alternatively, maybe you no longer have a reason to put both annotations and haven't thought about it in a while? :smile:

**Comment by snazy** [comment]
@MikeEdgar yes, we're seeing this once per operation.
Sadly we have to keep both `javax` and `jakarta` annotations, because our clients have to still support Java 8, but server(s) (Quarkus) require `jakarta`. It's quite a pain, but that's the sad reality :(

A `distinct()` could resolve the issue. I'll check and open a PR.
