### ISSUE TITLE
Response code map is not sorted, which makes review hard

### ISSUE THREAD

**Issue by HerrDerb** [smallrye/smallrye-open-api#1811]
The response map of an api seems currently not sorted. The keys (response codes) of the object `responses` have a toggeling order which make a review really hard, up to impossible.

```
      responses:
        "201":
          description: Created
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
```
can toggle on the next generation run  to:
```
      responses:
        "201":
          description: Created
        "403":
          description: Not Allowed
        "401":
          description: Not Authorized
```

Having a large api, any important change will be lost in the massiv diff.

I would expect, that I get a deterministic output.

**Comment by MikeEdgar** [comment]
@HerrDerb are you using Quarkus with auto-security in the OpenAPI? If so, this may have already been fixed there: https://github.com/quarkusio/quarkus/issues/40222

**Comment by HerrDerb** [comment]
Exactly this 👍 😀 Cheers
