### ISSUE TITLE
Support traversing up the class hierarchy for JAX-RS resources

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-open-api#184]
Currently, if annotations are added to methods on a parent class or interface they are not picked up by the scanner.

It might be worth adding support for this as it seems a common pattern

**Comment by MikeEdgar** [comment]
@kenfinnigan, do you mean on JaxRS resources or models? It SHOULD be supported for models in recent versions.

**Comment by EricWittmann** [comment]
He's referring to the resource classes.

**Comment by MikeEdgar** [comment]
I've started taking a look at this and it shouldn't be too complicated, except for the parameter processing.

Provided the following interface method
```java
@PathParam("name")
@Parameter(name = "name", description = "Parent description")
void setName(String name);
```

And the following implementation:
```java
@Override
@Parameter(name = "name", example = "Duke")
public void setName(String name) {
  this.name = name;
}
```
Which of the following would you expect?
1. The parameter information from the parent
2. The parameter information from the child
3. The parameter information from the parent, merged with the child's

**Comment by EricWittmann** [comment]
(3)

**Comment by MikeEdgar** [comment]
> (3)

I was afraid that might be the answer :-)

**Comment by EricWittmann** [comment]
Yeah. :)  You asked what I would expect, not what I think we should do.  If it's significantly easier to implement, I think (2) would be sufficient.
