### ISSUE TITLE
SROAP01001: Schema with zero references removed from

### ISSUE THREAD

**Issue by Postremus** [smallrye/smallrye-open-api#1890]
I get a lot of messages like
```
2024-07-02 13:46:46,185 INFO  [io.sma.ope.api.util] (vert.x-eventloop-thread-3) SROAP01001: Schema with zero references removed from #/components/schemas:
```
when I activate the option `mp.openapi.extensions.smallrye.remove-unused-schemas.enable`.
I believe that log message is mostly usefull for debugging purposes.

Can you please therefore change this message to debug level?

**Comment by phillip-kruger** [comment]
+1. Are you keen to provide a PR
