### ISSUE TITLE
Example object not generated

### ISSUE THREAD

**Issue by cristalp** [smallrye/smallrye-open-api#1893]
I'm switching to Eclipse MicroProfile annotations from Swagger annotations and from another Maven plugin to the Smallrye Maven plugin.

However, there seems to be a bug with the \@ExampleObject.

If I annotate the following:

```
      @APIResponse(responseCode = "200", description = "Application is online.", content = @Content(mediaType =
       MediaType.TEXT_PLAIN, examples = {
          @ExampleObject(summary = "The timestamp", value = "2022-01-21T09:40:50.3472393+01:00") }
       ))
```

then nothing of the example object ends up in the JSON:

```
        "responses" : {
          "200" : {
            "description" : "Application is online.",
            "content" : {
              "text/plain" : {
                "examples" : { }
              }
            }
          }
```

Does the plugin expect other data in the example object?

**Comment by MikeEdgar** [comment]
@cristalp , `examples` is an object and the keys are based on the `name`. Adding a `name` to `@ExampleObject` should fix it.

**Comment by cristalp** [comment]
Ah! Well, `name` makes more sense than `summary` anyway. Thanks a lot and please close the issue.
