### ISSUE TITLE
Line feeds in example object value are ignored, text is truncated

### ISSUE THREAD

**Issue by cristalp** [smallrye/smallrye-open-api#1895]
I'm switching to Eclipse MicroProfile annotations from Swagger annotations and from another Maven plugin to the Smallrye Maven plugin.

I found that line feeds are ignored in @ExampleObject values. This is what I annotate:

```
@Content(examples = { @ExampleObject(name = "The user IDS", value = "1046\n1049\n1051") })
```

With the old toolchain, I get the following in `openapi.json` :

```
            "content" : {
              "text/plain" : {
                "example" : "1046\n1049\n1051"
              }
            }
```
(I didn't specify any name back then.)

Rendered in SwaggerUI it looks like this:

```
1046
1049
1051
```

With the Smallrye Maven plugin, this is what I get:
```
            "content" : {
              "text/plain" : {
                "examples" : {
                  "The user IDS" : {
                    "value" : 1046
                  }
                }
              }
```

Of course, SwaggerUI shows it like this:

```
1046
```

So any text after the first line feed is thrown away. As far as I remember, any OpenAPI text is considered Markdown, so shouldn't that work?

And is there any relation to the old rendering as one `example` and Smallrye correctly creating `examples` ?

**Comment by MikeEdgar** [comment]
Just out of curiosity, if you add a space in the example before the `1046`, does it pass through all three lines? I think it believes the value is a number and the Jackson parser may be throwing out the second and third lines.

**Comment by MikeEdgar** [comment]
Actually, space won't work - it's trimmed. Try adding a `+` prefix to test it.

**Comment by cristalp** [comment]
Well, using `"1046 \n 1049 \n1051"`shows the same behavior.

However, I have another endpoint which returns JSON, and the example value was not valid JSON. This was shown during build (cool!) and thus I could fix it. That example also contains line feeds, and it's rendered with line feeds in the `openapi.json`. But I don't know whether that's because of my line feeds or whether the plugin parses it and pretty prints it anyway.

What exactly do you mean with the `+` prefix?

**Comment by cristalp** [comment]
I also wonder: Since this is `text/plain`, why would it be parsed by the Jackson parser?

**Comment by cristalp** [comment]
Ok, so I set it to `"1046+\n1049+\n1051"`, and this is what's rendered:

```
"value" : "1046+\n1049+\n1051"
```

And in Swagger UI:
```
1046+
1049+
1051
```

**Comment by MikeEdgar** [comment]
Thanks, adding the + just breaks the conversion of the value to a number. This definitely seems like a bug.

**Comment by cristalp** [comment]
Yes, I also think so. Since no media type is given, the String should just be copied through to `openapi.json` .

**Comment by cristalp** [comment]
Thanks!
