### ISSUE TITLE
Class loading for reflection breaks Quarkus ORM enhancement

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#191]
Original issue: quarkusio/quarkus#2961
Regression caused by fix for quarkusio/quarkus#4329 and #185

**Comment by MikeEdgar** [comment]
@FroMage in #185 :
> Apparently, if we are able to pass you a ClassLoader instead of you using Class.forName (which will always use the CL of smallrye-openapi), we can make this work. Or you can use the TCCL.
>
>I can make a PR for either solution if you want.

Using the TCCL in `TypeUtil.getClass(String name)` instead of `Class.forName` probably will be the easiest and quickest at this point. @EricWittmann, any concerns?

**Comment by EricWittmann** [comment]
No concerns I can think of at the moment. :)

**Comment by MikeEdgar** [comment]
I'm thinking it might be a good idea to have an internal index in `TypeUtil` with the JDK classes we are known to be looking for, specifically `java.lang.Enum` and the collection types. That should remove the need for reflection. It would be something like the small internal index that is used in `OpenApiDataObjectScanner` for the stand-in types. By doing that, we won't impact class field scanning, but still be able to determine the relevant class hierarchies using Jandex only.

I know a fix for this is very likely to be time sensitive so that change can happen later.

**Comment by kenfinnigan** [comment]
@MikeEdgar is this something you're actively working on a fix for?

**Comment by MikeEdgar** [comment]
@kenfinnigan - not yet. If @FroMage has not already started I can pick it up, but I won't be able to do that until this evening.

**Comment by kenfinnigan** [comment]
Ok, I can take a look now.

**Comment by FroMage** [comment]
Thanks @kenfinnigan
