### ISSUE TITLE
Abstract REST classes should be ignored

### ISSUE THREAD

**Issue by cristalp** [smallrye/smallrye-open-api#1961]
We have a lot of REST resources which consist of an abstract class with a lot of endpoints. In another Maven project (and EAR) there is a depencency on the JAR with the abstract class, and there is a concrete subclass that implements some methods and perhaps adds other endpoints as well.

With our current Swagger toolchain, we can annotate `@Hidden` on the abstract class, and it will be ignored. It will however be used if there is a concrete subclass.

With SmallRye however, the scanning will take all the endpoints of the abstract classes and present them everywhere that the abstract class is in the Maven dependency tree. Since there's no concrete class, this will not work.

Using `@Operation(hidden = true)` doesn't solve the problem, since then the endpoint will **never** appear.

So I suggest there should be a parameter in the Maven plugin that allows to ignore REST endpoints in abstract classes. However, it should not ignore `@Tag`, see https://github.com/smallrye/smallrye-open-api/issues/1901

**Comment by MikeEdgar** [comment]
@cristalp do you have a reproducer for this? Abstract classes without an implementation should already be ignored.

**Comment by cristalp** [comment]
Ok, so here we go:

There's a simple resource in some Maven project A:

```java
@Path("/")
public abstract class BaseFooResource {

  @GET
  @Path("/foo")
  @Produces(MediaType.TEXT_PLAIN)
  @Operation(summary = "Gets the foo")
  @APIResponses(value = { @APIResponse(responseCode = "200", description = "The Foo") })
  public Response getFoo() {
    return Response.ok("foo", MediaType.TEXT_PLAIN).build();
  }
}
```

And then there's another resource in a Maven project B:

```java
@Path("/")
public abstract class BaseBarResource {

  @GET
  @Path("/bar")
  @Produces(MediaType.TEXT_PLAIN)
  @Operation(summary = "Gets the bar")
  @APIResponses(value = { @APIResponse(responseCode = "200", description = "The Bar") })
  public Response getBar() {
    return Response.ok("bar", MediaType.TEXT_PLAIN).build();
  }
}
```

Now, Maven project B has a dependency on Maven project A. The SmallRye plugin is only triggered for Maven project B. And then Maven project B is packaged into an EAR, which is deployed.

I would expect both endpoints to be ignored, since both classes are abstract.

But what I see in SwaggerUI is that both endpoints are shown:
![screenshot](https://github.com/user-attachments/assets/edb2097f-b35d-42c8-b93f-e75a2ba82a0f)

**Comment by cristalp** [comment]
Thanks a lot!
