### ISSUE TITLE
"Could not find schema class in index" for class in dependency

### ISSUE THREAD

**Issue by xgp** [smallrye/smallrye-open-api#1969]
I am using the `smallrye-open-api-maven-plugin` with the following configuration:

```xml
      <plugin>
	<artifactId>smallrye-open-api-maven-plugin</artifactId>
	<groupId>io.smallrye</groupId>
	<executions>
          <execution>
            <goals>
              <goal>generate-schema</goal>
            </goals>
          </execution>
	</executions>
	<configuration>
        </configuration>
      </plugin>
```

I have an operation which returns a type from a dependency I import as `provided`. When I run the `generate-schema` goal, it gives me the following error:

```
Aug 28, 2024 7:47:03 PM io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner process
WARN: SROAP04005: Could not find schema class in index: org.keycloak.representations.info.SystemInfoRepresentation
```

I've tried a bunch of permutations of `scanPackages` and `includeDependenciesScopes`, but nothing seems to solve it. I'm probably missing some configuration parameter, but I've read the [README](https://github.com/smallrye/smallrye-open-api/blob/main/tools/maven-plugin/README.adoc) several times and can't figure it out.

**Comment by MikeEdgar** [comment]
Hi @xgp, have you tried using the configuration option `includeDependenciesScopes` on the plugin? You can set that to `compose,system,provided` and it should include that dependency in the index. The default for that option is just `compose,system`.

```xml
<includeDependenciesScopes>compose,system,provided</includeDependenciesScopes>
```

**Comment by MikeEdgar** [comment]
@xgp I tested this with `org.keycloak:keycloak-core` (with `provided` scope) and the below included scopes option works.

```xml
<includeDependenciesScopes>compile,system,provided</includeDependenciesScopes>
```

**Comment by xgp** [comment]
That works. Thank you @MikeEdgar 

The problem now is that "pulled in the world" that was in that jar (they also have jax-rs annotations in their resources classes there), so I think I need to filter using `scanPackages` to make sure I'm only generating my API def.
