### ISSUE TITLE
[4.0] Schema reference serialization change in behaviour

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-open-api#1987]
When deserializing the schema
```json
{
    "$ref": "abc"
}
```

In 3.1, it gets converted to
```json
{
    "$ref": "#/components/schemas/abc"
}
```
but in 4.0 it doesn't.

I think this is due to `SchemaIO` not calling `Schema.setRef()` and instead setting the `"$ref"` property directly which bypasses the code which would expand the reference.

To be honest, I was a bit surprised that we do this sort of reference expansion on deserialization, rather than just when the user calls `setRef` themselves.

**Comment by MikeEdgar** [comment]
Thinking about this one, I am wondering if 4.0 is the time to make the change to no longer manipulate the ref in deserialization. I think of the static file as something that should be preserved as much as possible and this makes assumptions about the user's intentions when specifying a simple ref value.

@Azquelt , what do you think about keeping the changed behavior?

**Comment by Azquelt** [comment]
If we change it, we should change it for all types. At the moment the changed behaviour is only in `Schema`.

We also need to make a decision about whether we still manipulate the ref if the user calls `setRef` in a reader or filter. If you keep that behaviour, then you end up in a state where you can't create the same model using the API that you can create using a static file.
