### ISSUE TITLE
JDK classes should also be scanned if required

### ISSUE THREAD

**Issue by cristalp** [smallrye/smallrye-open-api#1999]
Started by https://github.com/smallrye/smallrye-open-api/discussions/1995

The Maven plugin doesn't scan any JDK classes. We use `TimeUnit` in some REST endpoints, and while there is a workaround for that (thanks @MikeEdgar), it's cumbersome.

So I suggest an enhancement: Either there should be a flag to enable JDK class scanning or there should be a plugin property where a number of JDK classes can be listed to be scanned.

Since the first solution would probably make scanning slower, I suggest implementing the second solution - thanks!

**Comment by MikeEdgar** [comment]
If you run the plugin with `-X` do you see any logging about `module:java.base` being indexed?

**Comment by MikeEdgar** [comment]
What properties are you providing for these?
```xml
<scanExcludePackages>${openapi.exclude.packages}</scanExcludePackages>
<scanExcludeClasses>${openapi.exclude.classes}</scanExcludeClasses>
```

**Comment by cristalp** [comment]
Some internal classes, and then `com.google` and `org.rendersnake.Renderable`.

But I also see the following in the scanner log:

```
Okt. 28, 2024 2:26:13 PM io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner process
WARN: SROAP04005: Could not find schema class in index: org.rendersnake.Renderable
```

**Comment by cristalp** [comment]
Well, here's the Maven debugging output, I'm not using regexes:

```
[DEBUG] Configuring mojo execution 'io.smallrye:smallrye-open-api-maven-plugin:4.0.0:generate-schema:default' with basic configurator -->
...
[DEBUG]   (f) includeDependenciesScopes = [compile, runtime, system]
[DEBUG]   (f) includeDependenciesTypes = [jar, ejb]
[DEBUG]   (f) includeStandardJavaModules = [java.base]
...
[DEBUG]   (f) scanDependenciesDisable = false
[DEBUG]   (f) scanExcludeClasses = foobar.type.ReflectiveEqualityObject,org.rendersnake.Renderable,foobar.web.service.esv.AufgabeResource
[DEBUG]   (f) scanExcludePackages = foobar.web.util.rs.resource,com.google
[DEBUG]   (f) scanExcludeProfiles = []
[DEBUG]   (f) scanPackages = foobar
[DEBUG]   (f) scanProfiles = []
[DEBUG]   (f) scanResourceClasses = {}
[DEBUG]   (f) scanners = []
...
[DEBUG]   (f) systemPropertyVariables = {mp.openapi.extensions.smallrye.private-properties.enable=false}
```

**Comment by MikeEdgar** [comment]
Ok, the presence of `scanPackages = foobar` means that is the only thing to include. You can add `java.util.concurrent.TimeUnit` to `scanClasses` or add `java.util.concurrent` to `scanPackages`. Once you've specified what is included, basically other things will not be "seen" by the scanner.

**Comment by MikeEdgar** [comment]
This is from the specification [1], which might help how you set these include/exclude options:

> The following rules are used to determine whether a class is scanned for annotations:
> 
> - A class is not scanned if it's listed in `mp.openapi.scan.exclude.classes`
> 
> - A class is scanned if it's listed in `mp.openapi.scan.classes`
> 
> - A class is not scanned if its package, or any of its parent packages are listed in `mp.openapi.scan.exclude.packages`, unless a more complete package or parent package is listed in `mp.openapi.scan.packages`
> 
> - A class is scanned if its package or any of its parent packages are listed in `mp.openapi.scan.packages`
> 
> - A class is scanned if `mp.openapi.scan.classes` and `mp.openapi.scan.packages` are both empty or not set

[1] https://download.eclipse.org/microprofile/microprofile-open-api-4.0.2/microprofile-openapi-spec-4.0.2.html#_core_configurations

**Comment by cristalp** [comment]
Ah, I wasn't aware of that, thanks! I now removed `scanPackages` completely and have started a full build. Let's see what happens. But in my local test, `TimeUnit` has now appeared!
