### ISSUE TITLE
Is it possible to flatten nested POJOs

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#201]
See eclipse/microprofile-open-api#380 for original discussion.

**Comment by MikeEdgar** [comment]
@norrman - if you have added the following to your pom:
```
    <dependency>
        <groupId>io.smallrye</groupId>
        <artifactId>smallrye-open-api</artifactId>
        <version>1.1.19</version>
    </dependency>
```

Please also be sure to **exclude** the following from the io.thorntail openapi dependency:
```
  <groupId>io.smallrye</groupId>
  <artifactId>smallrye-open-api-1.1</artifactId>
```

I would also suggest that you add a TODO comment to remove the include/exclude next time Thorntail is updated :-)

**Comment by norrman** [comment]
Hi,
Sorry, I should've pointed out that we use smallrye-openapi directly in a maven plugin to generate openapi document during build time, so there is no  thorntail interference; we just used the version pointed to from thorntail.
Maybe this maven plugin could be contributed if there is interest, if nothing else is available?
Coming back to the issue, can you point to a test in smallrye-openapi that demonstrate that this mechanism work? Some experiments using swagger indicates that they honor the @JsonValue annotation (which is at the core here), but I cannot see any reference to that annotation in smallrye-openapi.

**Comment by MikeEdgar** [comment]
Using your original example, it should work due to the annotation on `getMessages` in `GreetingMessage`. Did you update the version of smallrye-open-api being used in the Maven plugin? Also, what happens if you move the `@Schema` annotation to `SimpleString` itself?

```java
public class SimpleString {
       private final String value;
       public SimpleString(String value) {this.value = value;}
       @JsonValue public String getValue() { return value; }
}

public class GreetingMessage {
	private final SimpleString message;
	public GreetingMessage(@JsonProperty SimpleString message) {
		this.message = message;
	}

	@Schema(implementation = String.class, type = SchemaType.STRING)
	public SimpleString getMessage() { return message; }
}
```

**Comment by norrman** [comment]
I tried several variations, including putting @Schema on SimpleString.

**Comment by MikeEdgar** [comment]
Just to summarize for my own understanding - you are generating an `openapi.yml` static file at build time using a custom plugin that is using version 1.1.19 and the output of that static file is incorrect, even before running the application?

**Comment by norrman** [comment]
Almost. I'm not saying that the output is incorrect, just that I cannot achieve what I want, i.e. treat an object as a string property.

**Comment by MikeEdgar** [comment]
Well, if you're using 1.1.19 with those annotations, it's not correct :-) If there is any way to share some trimmed-down version of your project on Github, I would be happy to take a look. Is the plugin that you are using public or something homegrown that you can not publish?

**Comment by norrman** [comment]
[issue-201.zip](https://github.com/smallrye/smallrye-open-api/files/3794401/issue-201.zip)
Attached a zip file containing two maven projects: the plugin and a test project

**Comment by MikeEdgar** [comment]
@norrman , please annotate your classes like below (note `implementation` is not used here). This issue can remain open since it _should_ have worked when using `implementation` and that will need some additional research.

```java
public class GreetingMessage {
    private final SimpleString message;

    public GreetingMessage(@JsonProperty SimpleString message) {
        this.message = message;
    }

    public SimpleString getMessage() {
        return message;
    }
}

@Schema(type = SchemaType.STRING)
public class SimpleString {
    @Schema(hidden = true)
    private final String value;

    public SimpleString(String value) {
        this.value = value;
    }

    @JsonValue
    public String getValue() {
        return value;
    }
}
```

**Comment by norrman** [comment]
Hi,
I will try to confirm this tomorrow (Nov 5th).

**Comment by MikeEdgar** [comment]
@norrman - did you get an opportunity to try the configuration suggested earlier?
