### ISSUE TITLE
Duplicate operationId

### ISSUE THREAD

**Issue by nimo23** [smallrye/smallrye-open-api#2010]
According to https://github.com/smallrye/smallrye-open-api/issues/1688, it should be resolved, but I am getting also the "SROAP07903: Duplicate operationId"-error.

I have MyResource which makes use of an Interface:

```
@Path("/myResource")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@ApplicationScoped
public class MyResource implements MyInterface<User>{

        @GET
	@Path("/{id}")
	@APIResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(type = SchemaType.OBJECT, implementation = User.class)))
	@Override
	public Response getById(Integer id) {
		return MyInterfae.super.byId(id);
	}

}
```
The interface:

```
interface MyInterface<T> {

	@GET
	@Path("/{id}")
        default Response getById(@PathParam("id") Integer id) {
		// implemenation
	}

}
```

and the `operationId` is generated by **Quarkus (version 3.15.1)** by using the following property:

`mp.openapi.extensions.smallrye.operationIdStrategy=CLASS_METHOD`

when running in dev or test mode, it prints:

> [io.sma.ope.run.sca.spi] (build-9) SROAP07903: 
> Duplicate operationId: 
> MyResource_getById produced by Class: com.acme.MyResource, Method: jakarta.ws.rs.core.Response getById(java.lang.Integer id) 
> and Class: com.acme.MyResource, Method: jakarta.ws.rs.core.Response getById(Integer id)

**If I interpret the error message correctly:**
It complains about a `operationId` even though it is the same class (it compares the `MyResource` class with itself which does not make sense), or?

**Comment by MikeEdgar** [comment]
@nimo23 is the `getById` method in your interface defined as a `default` method? Just curious because the code snippet shows a method body.

**Comment by MikeEdgar** [comment]
@nimo23 are you required to re-specify the JAX-RS annotations on the implementation class?

That is, can you remove `@GET @Path("/{id}")` from `MyResource#getById` and allow them to be inherited from `MyInterface#getById` ?

**Comment by MikeEdgar** [comment]
What I am getting at is, if you put `@GET @Path("/{id}")` on `getById` in the interface, you shouldn't need to have it again in the implementations (as long as there are no other JAX-RS annotations on the implementation methods).

I think in that case you should get the operationIds as expected without the warning in the logs.

**Comment by MikeEdgar** [comment]
Fair enough, I'll push a fix for this to ignore duplicates when the duplicate is an override.
