### ISSUE TITLE
Empty @SecurityRequirements annotation is only honored on methods but not on classes

### ISSUE THREAD

**Issue by danielbobbert** [smallrye/smallrye-open-api#2011]
The behavior of the smallrye-open-api-maven-plugin to generate an OpenAPI schema from Jax-RS sources has changed.

Up until (including) version 3.10.0, putting an empty \@SecurityRequirements annotation on a **class** lead to a schema, where each operation in the resulting schema was annotated with "security: []". This is important for us during validation of the schema.

Since version 3.11.0, this attribute is missing from the generated schema.

Putting an empty  \@SecurityRequirements on a **method** still results in an attribute being added to that operation. So our current workaround is to put the annotation on every single method. But, of course, annotating the whole class is much easier, and the change in behavior looks like a regression and not like a intended feature.

I have attached a small test case that illustrates the problem.

[smallrye-security-requirements.zip](https://github.com/user-attachments/files/17280959/smallrye-security-requirements.zip)

**Comment by MikeEdgar** [comment]
Thanks for reporting it. This will be fixed in #2012 for the next release.

**Comment by danielbobbert** [comment]
Awesome. Thank you for the quick response!
