### ISSUE TITLE
smallrye-open-api-maven-plugin does not include static schema from META-INF/schema.json

### ISSUE THREAD

**Issue by robotmrv** [smallrye/smallrye-open-api#2016]
since `io.smallrye:smallrye-open-api-maven-plugin:3.11.0` resulting schema does not include static schema.

reproducer 
[openapi-static-resource.zip](https://github.com/user-attachments/files/17379079/openapi-static-resource.zip)
Run 
```shell script
./mvnw clean install
```
Check `src/main/resources/test-openapi.json`  
ER: it contains content from `src/main/resources/META-INF/openapi.json`  
AR: it does not contain content from `src/main/resources/META-INF/openapi.json`  

reproduces with io.smallrye:smallrye-open-api-maven-plugin:3.11.0 and 3.13.0   
does not reproduce with 3.10.0 

--- 
looks like the issue comes from this commit https://github.com/smallrye/smallrye-open-api/commit/e60e1a5ca8bbd82e917d528c4e1426e41c4ded67#diff-fcff67b00bd32110e7c6feabf5bc2bc7590dad5e2e718da59de30b12e7de861aL361 it changed the way static file was loaded.

**Comment by MikeEdgar** [comment]
Thanks for reporting this. The fix is in #2017 which will be in 4.0 (future) and 3.13.1 (likely this week)

**Comment by MikeEdgar** [comment]
@robotmrv I have it tagged for backport, but nothing planned just yet. Is there anything blocking you from moving to version 4.0+ of the plugin?

**Comment by robotmrv** [comment]
it is major version update and it uses new mp-openapi version.   
So it looks like is not safe upgrade for our applications and tools that process generated openapi specifications.  
Fast try detected changes in generated result so I did not risk to upgrade.

**Comment by MikeEdgar** [comment]
> it is major version update and it uses new mp-openapi version. So it looks like is not safe upgrade for our applications and tools that process generated openapi specifications. Fast try detected changes in generated result so I did not risk to upgrade.

Fair enough - I'll try to get a 3.x release out this week or early next week.

**Comment by MikeEdgar** [comment]
@robotmrv I haven't yet had a chance to do the backports/3.x release. Have you tried setting `mp.openapi.extensions.smallrye.openapi=3.0.3` when using version 4.0.x? That will output OpenAPI 3.0 format.

**Comment by robotmrv** [comment]
@MikeEdgar 
tried with <openApiVersion>3.0.3</openApiVersion> and 4.0.5 plugin version 
got following diff  
changes all allOf to anyOf in references and adds enum schema as additional element of anyOf 
e.g.
```diff
           "myAttribute": {
-            "allOf": [
+            "anyOf": [
               {
                 "$ref": "#/components/schemas/MyType"
+              },
+              {
+                "enum": [
+                  null
+                ]
               }
             ],
```

**Comment by robotmrv** [comment]
also removed all nullable markers 
```diff 
-            "nullable": true,
```
