### ISSUE TITLE
JacksonJsonIO may throw exception when trying to read a number

### ISSUE THREAD

**Issue by Azquelt** [smallrye/smallrye-open-api#2054]
[JacksonJsonIO.getJsonBigDecimal](https://github.com/smallrye/smallrye-open-api/blob/ecb1ae514d64a642673b4fb9e58fdeab138c0631/core/src/main/java/io/smallrye/openapi/runtime/io/JacksonJsonIO.java#L153-L157) does not check that the node contains a number before trying to parse it as a big decimal.

This results in a `NumberFormatException` rather than a `null` [as the Javadoc would suggest](https://github.com/smallrye/smallrye-open-api/blob/ecb1ae514d64a642673b4fb9e58fdeab138c0631/core/src/main/java/io/smallrye/openapi/runtime/io/JsonIO.java#L308-L315).

Admittedly, the Javadoc was written after the implementation, so arguably it's the Javadoc that's wrong here, but having this method return a `null` would be consistent with the other methods in this class.

This can result in throwing an exception when parsing an OpenAPI 3.0 schema rather than ignoring the invalid field.

Ideally we should unit test the `JsonIO` implementations. There may be other similar bugs.

**Comment by MikeEdgar** [comment]
+1

Currently it supports both text and numeric JSON values. I wonder if that it correct or whether it should be limited to only numeric values. That can easily be tested with `JsonNode#isNumber` together with `JsonNode#decimalValue`, but allowing text would require a bit more involved check.
