### ISSUE TITLE
Found several bugs in the OpenAPI generation results

### ISSUE THREAD

**Issue by dhoffer** [smallrye/smallrye-open-api#2062]
We are trying to upgrade a large JAX-RS REST app to use the quarkus-smallrye-openapi library instead of Swagger libraries but we have run into some blocking issues.

List of issues:
1. JDK types should never have new types with the JsonView suffix.  JDK types are just the JDK type, no way to have JsonView modified versions.
2. When JsonView types are created they should not append the full JsonView class hierarchy they should just append the view that was specified. E.g Full, Ingest, Abridged, etc.   Not Full_Ingest_Abridged.
3. In the Group entity, @JsonIgnoreProperties should only apply to this entity's use case of Role.  Currently, it's global because Group was processed before Role.
4. Adding @Schema() in Role entity on the description field does fix the problem were @JsonIgnoreProperties in Group was removing description globally, but now the @JsonView on description field is being ignored and description field is in all JsonViews.  Furthermore we have observed that @JsonView is not respected at all if there is a @Schema annotation.

I have created workarounds for 1 & 2 in our OASFilter but it is not possible to fix 3 & 4 in the filter as the schema is completely broken before it reaches the filter.

I have attached a reproducer project.

We are using Quarkus 3.16.2.  This is a blocking issue for us so can't use quarkus-smallrye-openapi library until we have fixes or workarounds for all of these issues.

[json-view-schema-example.zip](https://github.com/user-attachments/files/17683494/json-view-schema-example.zip)

**Comment by MikeEdgar** [comment]
Thanks for reporting this @dhoffer . PR #2063 should resolve most, if not all, of the items you've listed.

**Comment by dhoffer** [comment]
Hi @MikeEdgar thanks, I will checkout the changes.  What is the best way to pickup these changes, point to Quarkus 999-SNAPSHOT?  

Also what about the #4 issue, Furthermore we have observed that @JSONVIEW is not respected at all if there is a @Schema annotation.  This is one of the biggest bugs we found but didn't see that listed as fixed.

**Comment by MikeEdgar** [comment]
To answer your other question, this is not yet incorporated in Quarkus, so you would need to build it locally and add the `smallrye-open-api-core` and `smallrye-open-api-jaxrs` dependencies to the Quarkus Maven plugin. I'd like to accumulate a few more fixes before releasing a new version, so perhaps later this week or early next week.

**Comment by dhoffer** [comment]
Hi @MikeEdgar but you are also removing the String description from all of the Role models:

`    Role_Full:
      type: object
      properties:
        name:
          type: string
        id:
          $ref: "#/components/schemas/UUID"`

Where is this part?

`@Schema()
    @JsonView(Views.Full.class)
    private String description;`

**Comment by MikeEdgar** [comment]
It's not in the unit test, but if I do add the `RoleResource` from your reproducer project, it looks like it renders properly.

```java
@Path("/role")
class RoleResource {
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @JsonView(Views.Full.class)
    @APIResponse(responseCode = "200", content = @Content(schema = @Schema(implementation = Role.class)))
    public Response getRole() {
        return null;
    }

    @POST
    public Response post(@RequestBody @JsonView(Views.Ingest.class) Role role) {
        return null;
    }
}
```

The resulting schemas are like this (which I see a bug where description should not be present in the `Ingest` view).
```json
"Role_Full" : {
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "string",
      "format" : "uuid",
      "pattern" : "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
    },
    "name" : {
      "type" : "string"
    },
    "createdAt" : {
      "$ref" : "#/components/schemas/LocalDateTime"
    },
    "description" : {
      "type" : "string",
      "title" : "Title of description"
    }
  }
},
"Role_Ingest" : {
  "type" : "object",
  "properties" : {
    "name" : {
      "type" : "string"
    },
    "description" : {
      "type" : "string",
      "title" : "Title of description"
    }
  }
}
```

**Comment by dhoffer** [comment]
@MikeEdgar The problem with that test is it's not applying what the Group processing is doing first.  I will attach the full OpenAPI of this sample project.

[openapi.yaml.txt](https://github.com/user-attachments/files/17706873/openapi.yaml.txt)

**Comment by dhoffer** [comment]
@MikeEdgar One more thought on this.  I know you said you feel @JsonIgnoreProperties is important and should be supported to allow precise inline OpenAPI models and we are fine with that but I'd like to see this be configurable.  One idea would be for smallrye openapi to allow users to specify the list of annotations that smallrye openapi should ignore.  

Our current/prior approach that used Swagger libraries skipped @JsonIgnoreProperties for OpenAPI generation and that was fine for us.  We would actually prefer it that way just so there is no change with this upgrade to use smallrye openapi, so having it configurable would be ideal.

**Comment by dhoffer** [comment]
@MikeEdgar In our case we really aren't trying to hide anything, it was added to break a circular recursion issue when the data was serialized by Jackson.   That wouldn't be a problem in the sample reproducer project but it is in our production system.  I believe that is the only reason we have to occasionally use @JsonIgnoreProperties.

**Comment by MikeEdgar** [comment]
Ok, I see. Either way the result is that the JSON is missing a property that is documented by the OpenAPI schema, no? I'm trying to understand if there is a better/different way to make things work for you.

**Comment by dhoffer** [comment]
Well, lets back up and first cover the remaining bug.  Then we can discuss the idea of it being configurable.  The current code does not work because @JsonIgnoreProperties is still being applied globally and it should just be applied to the inline model.  That is the breaking part.

Then yes being able to configure smallrye openapi to skip @JsonIgnoreProperties would be nice for our use case as we are fine with it always being in the model but no data exists (it doesn't exist at a low nested level so users don't want the data at that level anyway).  I hope that makes sense.

**Comment by JakeH10** [comment]
@MikeEdgar The issue we see with `@JsonIgnoreProperties` depends on the order classes are resolved. 

In the reproducer, the issue occurs since the scanner resolves `group` before `role`. When the annotation scanner resolves `group`, it finds the embedded `role` object so it also resolves `role` within the context of `group`. Within this context, the `description` field is ignored via `@JsonIgnoreProperties("description")`. Later, the annotation scanner finds the `Role` class but it believes it has already resolved it, so it skips it.

Without `@JsonIgnoreProperties` on `com.example.jsonview.model.Group#roles`:
```
Role:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
    id:
      $ref: "#/components/schemas/UUID"
```

With `@JsonIgnoreProperties` on `com.example.jsonview.model.Group#roles`:
```
Role:
  type: object
  properties:
    name:
      type: string
    id:
      $ref: "#/components/schemas/UUID"
```

**Comment by MikeEdgar** [comment]
Thanks @JakeH10 , I see the issue and I'll look into the fix.

**Comment by MikeEdgar** [comment]
@dhoffer @JakeH10 , PR #2065 should resolve the issue with `@JsonIgnoreProperties` modifying `Role_Full` globally. If you'd like to try it I can leave the PR open a while longer and merge tomorrow.

**Comment by dhoffer** [comment]
I'm not able to pull down the PR branch for some reason.  Are you able to merge so we can test using main branch?

**Comment by MikeEdgar** [comment]
> I'm not able to pull down the PR branch for some reason. Are you able to merge so we can test using main branch?

The branch is in my fork. I can go ahead and merge and we'll address anything new in a separate change.

**Comment by JakeH10** [comment]
@MikeEdgar Fields are not being hidden when in-line, i.e. when `@JsonIgnoreProperties` is used. We currently use `@Schema` and `@JsonIgnore` and neither hides the files when the object is in-line. I have updated `Role` in the reproducer:

```
public class Role implements Serializable {

    @JsonIgnore
    @Transient
    protected Logger logger = LoggerFactory.getLogger(Role.class);

    @Schema(hidden = true)
    public String getJsonType() {
        return getClass().getSimpleName();
    }

    @Id
    @JsonView(Views.Full.class)
    private UUID id;

    @JsonView(Views.Abridged.class)
    private String name;

    @JsonView(Views.Full.class)
    private String description;

}
```
The group schema is created as:
```
Group:
  type: object
  properties:
    roleId:
      type: string
    roles:
      type: array
      items:
        type: object
        properties:
          logger:
            $ref: '#/components/schemas/Logger'
          name:
            type: string
          id:
            $ref: '#/components/schemas/UUID'
          jsonType:
            type: string
    name:
      type: string
    description:
      type: string
    id:
      $ref: '#/components/schemas/UUID'
```
The actual `role` reference is created as expected:
```
Role:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
    id:
      $ref: '#/components/schemas/UUID'
```

**Comment by MikeEdgar** [comment]
Yeah, I think the logger should have been ignored from that annotation. Just curious, why not make the logger `static`?

**Comment by dhoffer** [comment]
In production we have hundreds of entities and its just easier to have this in the base class.

 @Schema(hidden = true)
 @Transient
 protected final Logger logger = LoggerFactory.getLogger(getClass());

**Comment by MikeEdgar** [comment]
@dhoffer the third linked PR (now merged to `main`) should have resolved this. If you test and find more issue on your end, let me know. Thanks

**Comment by dhoffer** [comment]
@MikeEdgar We have been testing and this looks good.  We will let you know if we find anything.  How soon could you make the next release with these fixes?  We could use that asap.

**Comment by MikeEdgar** [comment]
I'll cut release 4.0.3 now.
