### ISSUE TITLE
Bug: fields from abstract classes missing in openapi.yaml

### ISSUE THREAD

**Issue by nimo23** [smallrye/smallrye-open-api#2073]
The generated `openapi.yaml` does not consider properties (fields) inherited from **abstract classes**. For example:

```
public class MyUser extends User{

..

// inherits property "tasks"


}
```

```
public abstract class User{

// this field should is missing in openapi.yaml
private transient Task tasks;

..

// getter/setter

}
```

The `openapi.yaml` generator should consider fields inherited from abstract classes.

**Comment by MikeEdgar** [comment]
@nimo23 is it only an issue for `transient` fields? The scanner ignores them unless they are annotated to be part of the schema with `@Schema`.
