### ISSUE TITLE
Inherited Endpoints Cannot be Hidden

### ISSUE THREAD

**Issue by JakeH10** [smallrye/smallrye-open-api#2080]
If Resource A inherits Resource B and Resource B contains an endpoint, that endpoint will display under resource A in the openapi. However, the endpoint cannot be hidden with `@Override` and `@Operation(hidden = true)`.

This does seem to be a part of a more general issue: `@Operation` is completely ignored on an Overridden method. I also tried to set the description, but it is ignored.

**Comment by dhoffer** [comment]
What is the status of this one?  This is a blocking issue for us.  We are currently working with the latest smallrye-open-api SNAPSHOT code to get another needed fix(s) but we need this one too.  I don't think its possible for us to fix this in the filter.

**Comment by MikeEdgar** [comment]
@dhoffer I haven't yet had a chance to look into this issue and I'll unlikely be able to do so until next week.

**Comment by dhoffer** [comment]
@MikeEdgar Yeah I know this is a holiday week for many, myself included.  Ideally we would like to have this issue resolved and a new release as early as possible next week to we can push this into our next release cycle.

**Comment by dhoffer** [comment]
Hi @MikeEdgar just checking the status of this one?

**Comment by MikeEdgar** [comment]
@dhoffer I'm planning to look at this one in the next day or two.

**Comment by MikeEdgar** [comment]
I'm looking into this today. I am not able to reproduce what you reported about `@Operation` descriptions not overriding a parent method, but I do see the issue with the hidden operations.

**Comment by dhoffer** [comment]
@MikeEdgar Okay I'll retest again today but its definitely the hidden issue that we care about most.  So if you have that fixed we are good to go.
