### ISSUE TITLE
[4.0 regression] ref-properties get generated as `$ref` instead of `allOf [ { $ref ...} ]`

### ISSUE THREAD

**Issue by Felk** [smallrye/smallrye-open-api#2097]
I have the following model:

```java
public record MyModel(
    @Schema(title = "Valid From", description = "Start timestamp this entity is valid from")
    Instant validFrom,
    // ...
) {}
```

Starting with smallrye-open-api 4.0 (I tested 4.0.4), this produces the following yaml:
```yaml
"MyModel" : {
  "type" : "object",
  "properties" : {
    "validFrom" : {
      "title" : "Valid From",
      "description" : "Start timestamp this entity is valid from",
      "type" : "string",
      "$ref" : "#/components/schemas/Instant"
    },
```

The OpenAPI generated with `smallrye-open-api-core:jar:3.13.0` was this:
```yaml
"MyModel" : {
  "type" : "object",
  "properties" : {
    "validFrom" : {
      "title" : "Valid From",
      "description" : "Start timestamp this entity is valid from",
      "type" : "string",
      "allOf" : [ {
        "$ref" : "#/components/schemas/Instant"
      } ]
    },
```

The latter looks like a well-formed OpenAPI to me. However, the former appears to violate the OpenAPI 3.1 spec, see https://github.com/swagger-api/swagger-parser/issues/2036#issuecomment-2523701571.

> [RefObject] cannot be extended with additional properties and any properties added SHALL be ignored.

Right now, this change causes any additional fields, like `title` and `description` in this case, to be lost by tooling, e.g. as described in https://github.com/swagger-api/swagger-parser/issues/2036#issuecomment-2523580054.

**Comment by MikeEdgar** [comment]
The schema is somewhat of a special case object in OpenAPI 3.1 since it is now essentially just JSON Schema draft 2020-12 and the RefObject limitation no longer applies. See the fixed fields for components [1]. Schema does not allow a "Reference Object" like the others because it is now JSON Schema.

[1] https://spec.openapis.org/oas/v3.1.0.html#fixed-fields-5

**Comment by Felk** [comment]
Thanks for the clarification! Good to know,  As I understand, this means that the 3.1 schema is valid and fields like `title` or `description` should not be lost. In that case, this seems to just be a bug in swagger-parser. I'll close this issue then in favor of https://github.com/swagger-api/swagger-parser/issues/2036
