### ISSUE TITLE
Swagger UI does not display arrays of complex DTOs (List ) clearly compared to Springdoc

### ISSUE THREAD

**Issue by RaymondMouthaan** [smallrye/smallrye-open-api#2109]
**Description**:
When using Quarkus's SmallRye OpenAPI with Swagger UI, the representation of endpoint responses containing arrays of complex DTOs (e.g., `List<GenreDto>`) lacks clarity. Instead of showing `List<GenreDto>` or `array<GenreDto>`, it is visualized entirely in a generic way, such as `array<object>`. This makes it difficult for users – especially students – to understand the structure of the returned data.
This behavior has been observed with Swagger UI in Quarkus but is not an issue when using other frameworks such as Springdoc and Spring. For teaching purposes, this is problematic as it makes it harder for students to create proper DTOs based on API documentation.
Improving this would not only enhance Swagger UI’s usability but would also help Quarkus adoption in educational contexts where clear documentation is essential for training users.

**Steps to Reproduce**:

```
   @GET
   @Produces(APPLICATION_JSON)
   public List<GenreDto> findAllGenres() {
       return genreService.findAllGenres();
   }
```   
 
 **Expected Behavior**:
The endpoint response should show `List<GenreDto>` or `array<GenreDto>` explicitly, providing a clear visualization of the return type. For educational purposes, this makes it easier for students and users to understand what the array contains and how to create proper client-side DTOs.

**Actual Behavior**:
Swagger UI displays the response generically (e.g., `array<object>` or similar), making it unclear that the array contains `GenreDto` objects. This forces the user to dig into the generated OpenAPI spec manually to understand the return type, reducing usability and accessibility.

**Environment**:
- **Quarkus version**: `3.17.4`
- **Dependencies**: `quarkus-smallrye-openapi`
- **Java**: JDK 21

- **Spring boot version**: 3.4.0
- **Springdoc openapi**: 2.7.0

**Feature Request or Fix Suggestion**:
1. Swagger UI should include more explicit type annotations for arrays of complex objects.
2. The visualization could resemble Springdoc-style rendering, such as `array<GenreDto>` rather than the current generic approach (e.g., `array<object>`).
3. Consider enhancing the Quarkus-SmallRye OpenAPI integration for Swagger UI to handle arrayed DTOs more explicitly.

**Screenshots**:

Quarkus:
<img width="591" alt="image" src="https://github.com/user-attachments/assets/0ce1e214-d16f-4567-8b09-a143f4a012e7" />

<img width="601" alt="image" src="https://github.com/user-attachments/assets/dd131216-24f6-4f29-baf3-473eb7f5c49a" />

Spring:
<img width="779" alt="image" src="https://github.com/user-attachments/assets/2f3dc22b-8e49-4ef7-9ff4-8fbbcbfde109" />

**Generated OpenAPI JSON**:
Below is the OpenAPI JSON generated by SmallRye OpenAPI for the `findAllGenres` endpoint:

```json
{
  "paths": {
    "/genres": {
      "get": {
        "summary": "Find All Genres",
        "description": "Retrieve a list of all genres available.",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/GenreDto"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "GenreDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          }
        },
        "description": "DTO representing a genre."
      }
    }
  }
}
```

Below is the OpenAPI JSON generated by Spring OpenAPI for the `findAllGenres` endpoint:

```json
{
  "/rest-api/genres": {
    "get": {
      "tags": [
        "Genre"
      ],
      "summary": "Get genres",
      "description": "Obtain the genres",
      "operationId": "getGenres",
      "responses": {
        "200": {
          "description": "successful operation",
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/GenreDto"
                }
              }
            }
          }
        }
      },
      "security": [
        {
          "bearer-key": []
        }
      ]
    }
  },
  "components": {
    "schemas": {
      "GenreDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

### Solution

add to application.properties:

```
quarkus.smallrye-openapi.open-api-version=3.0.1
```
or application.yml

```yml
quarkus:
    smallrye-openapi:
        open-api-version: 3.0.1
```

**Comment by MikeEdgar** [comment]
Do you have the comparable OpenAPI JSON or YAML from Spring? Also, can you confirm that the two are using the same version of Swagger UI?

**Comment by RaymondMouthaan** [comment]
> Do you have the comparable OpenAPI JSON or YAML from Spring? Also, can you confirm that the two are using the same version of Swagger UI?

I've updated the post with requested info.

**Comment by MikeEdgar** [comment]
Ah, thanks for checking that out. Are you going to report this in Swagger UI? Any reason to keep this issue open?

**Comment by RaymondMouthaan** [comment]
> Ah, thanks for checking that out. Are you going to report this in Swagger UI? Any reason to keep this issue open?

Np, no I have no plans yet to report it (1k1 open issues + 82 PRs).

I'll close this issue.
