### ISSUE TITLE
Use Path Template Pattern as Parameter Pattern

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#216]
Path parameters that declare a regular expression are not currently handled. For example:

```java
@Path("/example")
class PathParamTemplateRegexTestResource {
        @GET
        @Path("{name:[A-Z]+}")
        @Produces(MediaType.TEXT_PLAIN)
        public String echo(@PathParam("name") String name) {
            return name;
        }
    }
```
will produce a path key of `"/example/{name:[A-Z]+}"`. The pattern part of the path should be extracted and applied to the associated `name` parameter's schema `pattern` attribute if no value has been explicitly given in another annotation.

**Comment by EricWittmann** [comment]
So many edge cases to cover!

**Comment by EricWittmann** [comment]
Hey @lamtrhieu - if you are interested in contributing to an implementation of microprofile-open-api, this might be a good one to look at. Let us know if you're interested!

**Comment by MikeEdgar** [comment]
@EricWittmann , @lamtrhieu - I actually have this one just about done, but there are definitely lots of other things to do. There are a number of issues identified in the project's [Sonar report](https://sonarcloud.io/project/issues?id=smallrye_smallrye-open-api&resolved=false) that may be good starting points for getting familiar with the code and getting ideas for fixes/enhancements. I can spend some time opening some new GH issues based on that list and on some other ideas for enhancements.

**Comment by lamtrhieu** [comment]
Hi @EricWittmann 
I am interested :). I also have a question regarding open-api and implementations. 
I think smallrye-open-api is an implementation of microprofile-open-api. And server like openliberty and thorntail will use smallrye implementation in their code?

I have checked out both the projects and read some code. I see lots of tests for the resources class with open-api annotations. 
So I think I can test/debug code in smallrye-open-api without the app server ? 
Is there any docs or guidelines showing how to setup env and run/debug code ?

I would appreciate if you can provide me with some starting point to setup env/run the code.

**Comment by EricWittmann** [comment]
You are right - `smallrye-open-api` is an implementation of the `microprofile-open-api` specification.  SmallRye is used in various project to provide MP-OpenAPI functionality, including (but not limited to):

* Quarkus
* Thorntail
* Wildfly
* JBoss EAP

Currently I believe that Open Liberty uses their own separate implementation, but I would not be surprised if they switched to using the SmallRye impl soon.

Almost all work on the SmallRye OpenAPI repository can be done without running a server - the JUnit tests are very thorough and should be sufficient for pretty much any feature/bug work you might do.

So if you clone the repository and import it into your IDE of choice (sounds like IntelliJ for you) then you should be all set.  Just run the JUnit tests however you normally do it from within your IDE.  I use Eclipse so I can't really help you set up an IntelliJ environment.  In Eclipse I simply import the SmallRye OpenAPI repository as an "existing maven project" and that's all.  Once it's imported I can easily run/debug the JUnit tests.

**Comment by lamtrhieu** [comment]
Thanks @EricWittmann. I can import maven project into IntelliJ and after looking closely at the tests I think most of them just 
1. Setup test model and resource
2. Generate json from the model and resource and do assertion
So I think I am good now. Really straight forward, just import maven project and run junit tests.

@MikeEdgar I am waiting for your enhancement issues ? Can I have a look at your PR for this main issue? Thanks

**Comment by MikeEdgar** [comment]
@lamtrhieu - I likely won't be able to open the issues until tomorrow morning (US Eastern time). I'll also push the changes and open the PR then. I will mention you in the PR.

**Comment by MikeEdgar** [comment]
@lamtrhieu - the PR for this is #219
