### ISSUE TITLE
Explore scanning of annotated ExceptionMapper instances

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#220]
@lamtrhieu, @EricWittmann - idea for consideration.

Suppose an application defines the following classes. It might be interesting for the scanner to find instances of `ExceptionMapper` that map declared checked exceptions or (undeclared?) runtime exceptions, adding any discovered `@APIResponse` annotations from the mapper to the path/method being scanned. This would be a convenient way to have all operations include a 404 or 500 response without declaring it with annotations throughout an application.

```java
@Provider
public class AppServerExceptionMapper implements ExceptionMapper<AppServerException> {
  @APIResponse(responseCode = "500", ...)
  Response toResponse(AppServerException exception) {
    ...
  }
}

@Path("/app/{id}")
public class AppResource {
  @GET
  public String getSomething(@PathParam("id") String id) 
      throws AppServerException {
    ...
  }

  @PUT
  public String updateSomething(@PathParam("id") String id, String newVersion) 
      throws AppServerException {
    ...
  }
}
```

**Comment by EricWittmann** [comment]
Yes for sure.  It's a great way to generate re-usable Responses in the OpenAPI document (from ExceptionMappers) and then link them appropriately in each generated operation based on the declared/checked exceptions on the jax-rs methods.

I'm not so sure about unchecked exceptions though.  I suppose we could assume that if there is a `500` mapper for an unchecked exception, then add it for every generated operation.  But that seems perhaps aggressive.

Change my mind!  ;)

**Comment by MikeEdgar** [comment]
You may be right about being aggressive. Maybe if it is limited to unchecked exceptions that extend from `javax.ws.rs.WebApplicationException` (and derive the correct `responseCode` based on that if no `@APIResponse` is present in the exception mapper) it would be feasible. In any case there should be a way to disable it. I don't think it would be too bad to require that apps declare unchecked exceptions in a `throws` if it allows the linkage to work.

**Comment by EricWittmann** [comment]
Either way I love the idea of generating reusable responses from the exception mappers.

**Comment by lamtrhieu** [comment]
@EricWittmann @MikeEdgar  
Do we come to a decision here ? Can I help with a small pr for this one?

**Comment by EricWittmann** [comment]
@lamtrhieu Yes I think we should start by scanning for Exception Mappers and generating reponse definitions for them.  Do you agree @MikeEdgar ?

**Comment by MikeEdgar** [comment]
@EricWittmann , @lamtrhieu  

+1

I agree. Consider doing it by looking for the `@Provider` annotation and then filtering by those that implement `ExceptionMapper<T>`. You can then match up response annotations found on the mapper's single method by comparing with the `throws` clause of the methods scanned in the `OpenApiAnnotationScanner`. 

It can be possibly expanded from that point to handle scenarios like run time exceptions, etc.

**Comment by lamtrhieu** [comment]
@EricWittmann @MikeEdgar 
Ok. Let me try with a PR. This is really a good chance to get familiar with the code. Thanks
