### ISSUE TITLE
Handle `JsonUnwrapped`jackson annotation

### ISSUE THREAD

**Issue by XciD** [smallrye/smallrye-open-api#226]
Hello,

I don't know if it's here but the `@JsonUnwrapped` annotation is not handle.

Any way to help you to implement it ?

Thanks

**Comment by msavy** [comment]
Thanks for opening this

Can you link to some docs so we can understand what it does.

 And any of your thoughts with respect to how it should be handled.

**Comment by msavy** [comment]
I had a quick look at the docs for this, and it essentially seems to merge/flatten the annotated entity's properties into its parent's properties.

For example:

```
class Root {
	int foo;
	@JsonUnwrapped
	LabelledThing thing;
}

class LabelledThing {
	int a;
	int b;
}
```

Normally this would be (pseudo code):

```
{
   "foo": ...
   "thing": { "a": ..., "b": ... }
}
```

When annotated, this becomes (note, `thing` is now elided):

```
{
   "foo": ...
   "a": ..., 
   "b": ...
}
```

So, in the JSON Schema you would want that field skipped and its properties merged into the parent.

@XciD Can you confirm this high-level understanding is generally correct?

Also, what happens currently when the `@unwrapped` annotation is ignored? Particularly, if the user utilises the current OpenAPI document we generate, does the payload still work?

**Comment by XciD** [comment]
Hello,

Sorry for the delay.
You are right about the definition.

If the `unwrap` is ignored and you did not mark unknow fields are ignored, you will have an jackson exception.

**Comment by phillip-kruger** [comment]
This will have to be supported on a JAX-RS (and Spring and Vert.x) level right ? Or am I missing something ?

**Comment by MikeEdgar** [comment]
@phillip-kruger , this would go in core as part of the schema scanning process.

**Comment by phillip-kruger** [comment]
@MikeEdgar - What I mean is, we can of course add this functionality to generate the schema using the flattening as described here, but the underlying REST service (JAX-RS or Spring or Vertx) needs to also understand that else the service will fail?

**Comment by MikeEdgar** [comment]
@phillip-kruger , I agree. This would be similar to the support for the various mechanisms for ingoring or ordering fields. The assumption we make is that if the annotations are present, the run-time supports them.

**Comment by phillip-kruger** [comment]
Ok cool. I still feel unsure where to draw the line. I wonder if this will not be better to rather allow some sort of extension that allow developers to support something like this....

**Comment by MikeEdgar** [comment]
That's what the `OASFilter` and `OASModelReader` are for, in my opinion. Having users utilize those are the best way to get cross platform compatibility. Having too many SR specific extension points might be counter to that. Just my 2 cents.

**Comment by phillip-kruger** [comment]
So using that the developer can add support for `@JsonUnwrapped` ? If so I think we should close this ticket.

**Comment by MikeEdgar** [comment]
They could. The filter is the last thing to process the `OpenAPI` object and it can do anything with it. That being said, there is still some value to supporting it out of the box, if we ever get an opportunity to implement it :-)

**Comment by phillip-kruger** [comment]
Not that we support multiple filters, maybe we can start a new module that contains some filters. Then for cases like this users can include this module and set the config ? w.d.y.t ?

**Comment by MikeEdgar** [comment]
I'm not sure this could be done generically with a filter (unless somehow the Jandex index is available). In the user space, they would know where they are using the specialized annotation and adjust the output accordingly.
