### ISSUE TITLE
TCK module is not testing YAML

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#228]
It looks like the TCK module is not testing YAML generation due to the following -

1. `BaseTckTest` always generates JSON
2. `TckTestRunner` does not call the test methods multiple times based on the TCK `@Test` annotation's `dataProvider` property

I think all of the TCK's tests that have `@Test(dataProvider = "formatProvider")` are supposed to be called twice, once for YAML and once for JSON.

**Comment by EricWittmann** [comment]
This is all true.  It never really seemed like a priority.

**Comment by MikeEdgar** [comment]
@EricWittmann, I think you're right and serving the YAML response wouldn't actually be testing any of the code in the implementation any differently. However, it might be important to some degree due to eclipse/microprofile-open-api#307. What are your thoughts? I did some work on that issue and ran into this. In any case, probably low priority until the 2.0 TCK needs to be passed (assuming the change for 307 is accepted).
