### ISSUE TITLE
Response created from JAXRS method contains no description

### ISSUE THREAD

**Issue by michbeck100** [smallrye/smallrye-open-api#23]
The OpenAPI spec says a response must have a description (see [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#responseObject)). 
When generating a response from a JAXRS method (see [here](https://github.com/smallrye/smallrye-open-api/blob/master/implementation/src/main/java/io/smallrye/openapi/runtime/scanner/OpenApiAnnotationScanner.java#L699)), no description  is set. 

When pasting the generated OpenAPI document into [editor.swagger.io](https://editor.swagger.io) you can see the validation errors.

**Comment by jmini** [comment]
I have noticed this too during the [talk](https://jmini.github.io/ece2018-openapi/) I gave at EclipseCon Europe.

Given the code in [OpenApiAnnotationScanner.java](https://github.com/smallrye/smallrye-open-api/blob/4d82fef7fb4f794eafdbe10c87f44a8981776ece/implementation/src/main/java/io/smallrye/openapi/runtime/scanner/OpenApiAnnotationScanner.java#L699) linked in the previous post, there are only 3 cases:

* 204
* 201
* 200

Why not add some default descriptions:

* 204: `"No content response"`
* 201: `"Created response"`
* 200: `"Ok response"`

This way the OpenAPI Spec would validate.

**Comment by gastaldi** [comment]
> Why not add some default descriptions:
> 
> 204: "No content response"
> 201: "Created response"
> 200: "Ok response"
> 

I'd remove the "response" suffix

- 204: "No Content"
- 201: "Created"
- 200: "OK"
