### ISSUE TITLE
Add LocalTime format as a String (JDK8) 

### ISSUE THREAD

**Issue by zakhdar** [smallrye/smallrye-open-api#233]
It's possible to add format to LocalTime as String , related to  [https://github.com/quarkusio/quarkus/issues/6065#issuecomment-564578870](https://github.com/quarkusio/quarkus/issues/6065#issuecomment-564578870)

**Comment by MikeEdgar** [comment]
Thanks for opening this. I'll take some time this weekend to put together an enhancement.

**Comment by MikeEdgar** [comment]
Looking at the [ABNF table in RFC3339](https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14), it seems like it would make sense to use `partial-time` for a `LocalTime`, and `full-time` for an `OffsetTime`. I'm wondering if those terms are enough to convey format of [`LocalTime`](https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html#toString--) or [`OffsetTime`](https://docs.oracle.com/javase/8/docs/api/java/time/OffsetTime.html#toString--) and the regular expression patterns would be non-obvious at a glance. 

Some other options:
* Use `description` with a concise message about the format (e.g. "ISO-8601 time with zone offset")
* Use `externalDocs` to link to RFC3339
* Use `example` to show the possible formats from the JavaDoc `toString` methods

The defaulted information for those options would appear on the schema located in `components`, so I don't expect that it would be duplicated all over the final document.

@EricWittmann and @msavy - do you have a leaning one way or another - or something completely different?

**Comment by EricWittmann** [comment]
Those are all good suggestions.  I think `externalDocs` and `example` are definitely a +1 for me.  I'm less sure about adding a description, but am not opposed.  Thoughts @msavy?

**Comment by msavy** [comment]
I don't think the description is a bad idea, as long as others think it doesn't violate the principle of least surprise.

The whole time thing is a bit of a morass in my experience, so anything we can do to clarify things is good.

p.s. Should your description example not say **WITHOUT** a zone offset?

**Comment by MikeEdgar** [comment]
> p.s. Should your description example not say **WITHOUT** a zone offset? @MikeEdgar

@msavy - for the `LocalTime`, you're right. I am planning on handling both that and the `OffsetTime` with this issue.
