### ISSUE TITLE
How do I describe a multi value parameter?  

### ISSUE THREAD

**Issue by ahofmeister** [smallrye/smallrye-open-api#235]
Hello! 

Leaving the question as it is. 

`@QueryParam("name") List<String> names` This works perfect with JAX-RS, but how do I describe this parameter with `@Parameter`, that it is clear, that the param is a multi-value? 

I found something like `collectionFormat` on the internet (Swagger/OpenAPI), but can not find it in this project. :/ 

Alexander

**Comment by MikeEdgar** [comment]
Hi @AlexanderHofmeister, I believe what you're looking for is an array schema type with `explode` set to true. For example:

```java
@Parameter(
    name = "name",
    in = ParameterIn.QUERY,
    explode = Explode.TRUE,
    schema = @Schema(type = SchemaType.ARRAY, implementation = String.class))
```

You should be able to omit specifying the `schema` property of the `@Parameter`, as that should automatically be scanned by the annotation scanner.

Thinking about this example, it seems as though the annotation scanner should be generating the `explode = Explode.TRUE` for JAX-RS endpoints with `List` and/or `Collection` query parameters.

**Comment by MikeEdgar** [comment]
Looking at the OAI spec further, `explode` of true is the default serialization for query parameters. See https://swagger.io/docs/specification/serialization/#query. Specifying it in your OpenAPI output would be redundant, although still correct for JAX-RS.

What is the output you are getting that seems incorrect?

**Comment by AlexanderHofmeister** [comment]
I must say, I have enums ninstead of Strings, dont know if it make a difference.  Well, I am not sure how it should look in the OpenAPI UI.

I got following visual output with type `array` or no type at all. 
 
`pointTypesarray[string](query) | description.`

`pointTypes(query) | description.`

I am missing the hint, that the parameter can be append multiple times, but maybe I am just on the wrong foot. How would the visual output look correct?

**Comment by MikeEdgar** [comment]
@AlexanderHofmeister - can you post the following:
1. the section of the output OpenAPI document (either JSON or YAML) that corresponds to the operation with the `@QueryParam("name") List<String> names` parameter
2. the full method signature (including annotations) of the JAX-RS operation

**Comment by AlexanderHofmeister** [comment]
```
  - name: myEnum
        in: query
        description: description
        schema:
          $ref: '#/components/schemas/myEnum'
```

`@Parameter(description = "description.", in = ParameterIn.QUERY, explode = Explode.TRUE) @QueryParam("myEnum") List<MyEnum> enumValues) {`

**Comment by MikeEdgar** [comment]
@AlexanderHofmeister - what run time environment (and which version) are you using? Using the annotations you provided, the current version of SmallRye OpenAPI produces a different result (JSON shown):

```json
{
  "name" : "myEnum",
  "in" : "query",
  "description" : "description.",
  "schema" : {
    "type" : "array",
    "items" : {
      "$ref" : "#/components/schemas/MyEnum"
    }
  },
  "explode" : true
}
```

Where `MyEnum` is:
```json
"MyEnum" : {
  "enum" : [ "VALUE1", "VALUE2", "VALUE3" ],
  "type" : "string"
}
```

**Comment by MikeEdgar** [comment]
@ahofmeister - were you able to resolve your issue with the current version?

**Comment by ahofmeister** [comment]
@MikeEdgar  Sorry for not responding. Let me try to recap and I will come back to you the next days. :)

**Comment by ahofmeister** [comment]
@MikeEdgar It does work in an sample project. I will let you know if I managed to implement it in the actual project. :) Thank you so far!

**Comment by ahofmeister** [comment]
@MikeEdgar It worked. The part that was missing: ` schema = @Schema(type = SchemaType.ARRAY, implementation = String.class)` Thanks for your help, I will close this issue.

**Comment by ahofmeister** [comment]
```
    @GET
    @Path("enum")
    @Produces(MediaType.APPLICATION_JSON)
    public List<MyEnum> get(@Parameter(
            name = "name",
            in = ParameterIn.QUERY,
            explode = Explode.TRUE,
            schema = @Schema(type = SchemaType.ARRAY, implementation = String.class)) @QueryParam("name") List<MyEnum> enums) {
        return enums;
    }
```
