### ISSUE TITLE
Support inheritance for BeanParam and MultipartForm

### ISSUE THREAD

**Issue by SetoKaiba** [smallrye/smallrye-open-api#239]
I have forms for resteasy. The token and os is missing in the openapi and swagger-ui.
The json schema is without problem. But the forms isn't.
What should I do to make it correct in the openapi?

```java
public class Verify {
    @FormParam("token")
    public String token;
    @FormParam("os")
    public String os;
}

public static class UploadIconForm extends Verify {
    @FormParam("icon")
    public byte[] icon;
}
```

**Comment by MikeEdgar** [comment]
Hi @SetoKaiba - please post the JAX-RS method where the `Verify` or `UploadIconForm` is used. Please also post the resulting OpenAPI JSON that is incorrect.

**Comment by SetoKaiba** [comment]
I found out the problem. When I use @Form, the params from the parent is there.  When I use @MultipartForm from, the params from the parent is missing.

**Comment by SetoKaiba** [comment]
Change the @MultipartForm to @Form, it will contain the token and os from Verify.
```
    @Path("/uploadUserAvatar")
    @POST
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public Result uploadUserAvatar(@MultipartForm UploadIconForm form) {
```
```
    "/rest/user/uploadUserAvatar" : {
      "post" : {
        "requestBody" : {
          "content" : {
            "multipart/form-data" : {
              "schema" : {
                "type" : "object",
                "properties" : {
                  "icon" : {
                    "type" : "array",
                    "items" : {
                      "format" : "byte",
                      "type" : "string"
                    }
                  }
                }
              }
            }
          }
        },
        "responses" : {
          "200" : {
            "description" : "OK",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/Result"
                }
              }
            }
          }
        }
      }
    },
```

**Comment by MikeEdgar** [comment]
@SetoKaiba - the OpenAPI parameter scanner currently does not support inheritance on types annotated with `@BeanParam` or `@MultipartForm`. Please try to annotate your JAX-RS method with `@RequestBody(content = @Content(schema = @Schema(implementation = UploadIconForm.class)))` to get the desired output.

We can leave this issue open as a task to enhance the scanner to support inheritance on those types of requests in the future.

**Comment by SetoKaiba** [comment]
Thank you. It does help. At least, it's correctly show the openapi and swagger-ui now,

**Comment by sean-scott-lr** [comment]
@MikeEdgar I believe that mislabelling this as an enhancement has caused this issue to not receive the appropriate priority.  @BeanParam supports inheritance and the APIDoc does not appropriately reflect the inherited parameters.  

Also, I am using @QueryParam and the suggested workaround for this issue does not seem to work for me.  Should it?  If not, is there another workaround I can use for @QueryParam?

Thank you

**Comment by MikeEdgar** [comment]
@sean-scott-lr, I understand your point, but from an annotation scanning perspective it is an unimplemented feature rather than one that is just not working properly. Granted, it is not working as users expect.

`@FormParam`s are treated slightly differently by the scanner, which is the reason the work-around mentioned earlier will not work for the other types of JAX-RS parameters.

@phillip-kruger, where does this issue fall in your list of priorities? I'm happy to take a deeper look at it also if you want to reassign it to me.

**Comment by phillip-kruger** [comment]
Thanks @MikeEdgar  !

**Comment by MikeEdgar** [comment]
Based on the uncertainty around how downstream servers will be incorporating the next major MP version, I think it makes sense for this change to be made to both `master` and `1.x`. I anticipate having these changes ready in the next couple of days.

**Comment by SetoKaiba** [comment]
Thank you so much.

**Comment by sean-scott-lr** [comment]
@MikeEdgar Thank you for fixing.  I see its been merged to 1.x, When can we expect this to be in a release?

**Comment by MikeEdgar** [comment]
@phillip-kruger - do you think it's time for a 1.x release? I think it would be good to make the latest fixes on 1.x generally available.

**Comment by phillip-kruger** [comment]
Sure ! Let's do it.

**Comment by sean-scott-lr** [comment]
Great, thank you.  Hopefully Quarkus can pull it into 1.4.0
