### ISSUE TITLE
Move ArchiveUtils class out of src/main and move to src/test

### ISSUE THREAD

**Issue by EricWittmann** [smallrye/smallrye-open-api#246]
The `ArchiveUtil` class is found here:

https://github.com/smallrye/smallrye-open-api/blob/master/implementation/src/main/java/io/smallrye/openapi/api/util/ArchiveUtil.java

This class lives in `src/main/java` but is only used by test classes.  We should move it to `src/main/test` so that we no longer have a non-test dependency on ShrinkWrap.  It's possible/likely it should be removed from **implementation** and into **tck** but I didn't check that.

**Comment by MikeEdgar** [comment]
Does Thorntail use this?

**Comment by Ladicek** [comment]
It does, see https://github.com/thorntail/thorntail/blob/master/fractions/microprofile/microprofile-openapi/src/main/java/org/wildfly/swarm/microprofile/openapi/runtime/OpenApiDeploymentProcessor.java

**Comment by EricWittmann** [comment]
Well at least that explains why the class remains there.  So either we can leave it there or perhaps move it to a separate jar?  Or maybe @michalszynkiewicz can just continue excluding ShrinkWrap when doing Quarkus builds.  That's what prompted this issue, btw - the shrinkwrap dependency when doing Quarkus release builds.

**Comment by MikeEdgar** [comment]
It's simple enough that maybe it could just be copied to Thorntail and moved into the TCK module here.

**Comment by Ladicek** [comment]
I confess I don't like the idea that I'd have to track changes in that class and copy them over to Thorntail, if that perhaps happens. One possible option: could that class be put into a separate artifact that Thorntail and the test suite could depend on?

**Comment by MikeEdgar** [comment]
@EricWittmann  - would making Shrinkwrap an `optional` dependency solve this?

**Comment by Ladicek** [comment]
That would also work, I guess? Add a comment to that class that you need to bring ShrinkWrap yourself (which we do in Thorntail) and be done with it? :-)

**Comment by EricWittmann** [comment]
That's sounding like it is probably the best option, yes.

**Comment by gastaldi** [comment]
I think it's easier to copy that class over to Thorntail and merge the PR?

**Comment by phillip-kruger** [comment]
Hi @EricWittmann @MikeEdgar @Ladicek @gastaldi @jmesnil 

I want to reopen this issue and ask if we can re-consider removing ArchiveUtil from SmallRye Implementation. It's not used in the implementation at all and it's pulling in the shrinkwrap dependency. We only use it in the TCK.

I know Thorntail also use it, but I would suggest that we either have a copy in Thorntail or we create a new module in SmallRye that has this class in.

As we all know, Thorntail has a end of life coming up, so I am in favour just copy the class as it would have a natural death soon. 

Let me know what you think.

**Comment by EricWittmann** [comment]
I've never had a strong opinion on this - so would be happy moving this class within smallrye-open-api and also copying it to thorntail.  (I'm also typically more amenable to copy/paste of code than others)  :)

**Comment by phillip-kruger** [comment]
OK Seems like most people are OK with this. I am adding this to my TODO list.

**Comment by phillip-kruger** [comment]
This has been removed and is now merged.
