### ISSUE TITLE
Allow to override base path from @ApplicationPath

### ISSUE THREAD

**Issue by pilhuhn** [smallrye/smallrye-open-api#247]
In our application we are using `@ApplicationPath("/api/custom-policies/v1.0")` to set a base path for the individual rest-endpoints. 
This results in 

    paths : 
        /api/custom-policies/v1.0/policies
          ...
        /api/custom-policies/v1.0/facts
          ...

The base path of `/api/custom-policies/v1.0` is already represented in the servers section of the openapi document

The desired outcome would be to override the path from `@ApplicationPath` e.g. by the empty string so that the output looks like

    paths : 
        /policies
          ...
        /facts
          ...

**Comment by radcortez** [comment]
If I understood correctly, you also set the base path with `@Server.url`? Any particular reason for it? I usually only set the hostname and leave the path in the endpoints. Is this a possibility for you?

**Comment by pilhuhn** [comment]
Well, the basePath in @server.url goes into the servers section. When I set the application path as shown above, it gets prepended for each individual path item (which is coming out of `@Path` annotations on the individual classes/methods. 
But then I may be missing something.

**Comment by radcortez** [comment]
Do you have something like this:

```
@ApplicationPath("/api/custom-policies/v1.0"")
@OpenAPIDefinition(
    servers = {
        @Server(url = "http://localhost:8080/api/custom-policies/v1.0"", description = "OAuth2 Token Server")
    },
```

?

**Comment by MikeEdgar** [comment]
@pilhuhn - I think to accomplish what you're looking for, you need to set your application's _context path_ to `/api/custom-policies/v1.0` and then set the `@ApplicationPath` value to `"/"`.

**Comment by EricWittmann** [comment]
I agree that there are workarounds for this, I think it still might be reasonable to have an option to suppress the `@ApplicationPath`.  It would be trivial to implement (I'm happy to do it if there are no objections).

**Comment by MikeEdgar** [comment]
That sounds good to me. This seems like the correct approach for what we talked about in #21

**Comment by pilhuhn** [comment]
@MikeEdgar Setting the context may or may not be possible depending on other factors.
I have played with a few options and the result was not satisfactory. So seeing @EricWittmann being happy to do it is great :)

**Comment by EricWittmann** [comment]
@pilhuhn Check out the PR that addresses this issue.  You'll need to just set an option in your MP config properties file.

**Comment by pilhuhn** [comment]
@EricWittmann Sorry, i missed that - which PR is/was that?

**Comment by EricWittmann** [comment]
https://github.com/smallrye/smallrye-open-api/pull/252
