### ISSUE TITLE
Plan for Version 2.0

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#257]
With MP OpenAPI 2.0 on the horizon, it probably makes sense to start thinking about how to move forward with the repository. Looking over the issue list, it seems that none are "must haves" for version 1.x and several are actually addressed by 2.0. What are everyone's thoughts on the following?

- Create a `1.x` maintenance branch for bug fixes
- Re-base the existing `2.x` branch and merge into `master`. Prior to merging to `master`, additional changes may be required to ensure everything builds and passes the SNAPSHOT 2.0 TCK (e.g. adding the OSSRH Sonatype repo temporarily for building against the nightly MP OAI builds).

Alternatively, `2.x` could be re-based and left as a separate branch. In that case, it may be best to minimize changes to `master` to only bug fixes.

**Comment by EricWittmann** [comment]
My preference is always to have `master` be where new development takes place.  So my vote would be to create the `1.x` branch (as you suggest) for maintenance of the current stable version.  And then merge the outstanding 2.0 work onto `master` and run with it.

**Comment by phillip-kruger** [comment]
+1

**Comment by kenfinnigan** [comment]
Once a milestone is created here, can it be added to https://github.com/smallrye/smallrye-parent/issues/99 so it's easy to link through. Thanks

**Comment by MikeEdgar** [comment]
Thanks everyone for the feedback. I'll look at putting together a PR to get `master` aligned with MP OpenAPI 2.0-SNAPSHOT over the next few days.

**Comment by MikeEdgar** [comment]
The last thing to be done here (I think) is to remove the old `2.x` branch. If there are no objections I'll go ahead and do that and close this issue.
