### ISSUE TITLE
@OpenAPIDefinition doesn't seem to work

### ISSUE THREAD

**Issue by pe-st** [smallrye/smallrye-open-api#26]
I have a private playground application using Thorntail 2.2.0 (with smallrye-open-api:1.0.1 if I got that right). My entrypoint has these annotations:

    @OpenAPIDefinition(info = @Info(title = "myFancyEndpoint", version = "0.9"))
    @Path("fancy")
    public class FancyEndpoint {

When I call `localhost:8080/openapi`, the returned yaml starts as follows:

    ---
    openapi: 3.0.1
    info:
      title: Generated API
      version: "1.0"
    paths:
      ...

I would have expected `title: myFancyEndpoint` and `version: "0.9"`. Did I miss something or is there something missing in the Smallrye implementation?

**Comment by EricWittmann** [comment]
Try putting the `@OpenAPIDefinition` annotation on the application class rather than on a resource class (I'm assuming `FancyEndpoint` is actually a JAX-RS resource class since it is also annotated with `@Path`).

**Comment by pe-st** [comment]
Hello @EricWittmann 
Thanks for the quick response. Your assumption was right... And yes, it works when put on the application class!
