### ISSUE TITLE
Swagger-UI/Openapi-Link provides faulty schema-components for List/Set

### ISSUE THREAD

**Issue by ehora** [smallrye/smallrye-open-api#260]
This issue belongs to https://github.com/quarkusio/quarkus/issues/7238. @EricWittmann asked me to create an issue here https://stackoverflow.com/a/60268508/12912411.

I'm evaluating Quarkus as backend, accessed by an angular frontend. I wanted to use the openapi data provided by Quarkus via http://localhost:8080/openapi, and generate via openapi-generator tools an typescript-angular client stub.

I used as first step the Quarkus Openapi Guide: https://quarkus.io/guides/openapi-swaggerui But after running the unmodified example and retrieve the Openapi YAML-Data via the http://localhost:8080/openapi I noticed that the generated data is wrong and the openapi generator is not able to generate a client because of a stackoverflow error.

Problem: a self-reference in the Openapi-data for the SetFruit-Definition (last line):

```
openapi: 3.0.1
info:
  title: Generated API
  version: "1.0"
paths:
  /fruits:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetFruit'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fruit'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetFruit'
    delete:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fruit'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SetFruit'
components:
  schemas:
    Fruit:
      type: object
      properties:
        description:
          type: string
        name:
          type: string
    SetFruit:
      $ref: '#/components/schemas/SetFruit'
```

The FruitResource Endpoint:

````
package org.acme.openapi.swaggerui;

import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Set;

@Path("/fruits")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public class FruitResource {

    private Set<Fruit> fruits = Collections.newSetFromMap(Collections.synchronizedMap(new LinkedHashMap<>()));

    public FruitResource() {
        fruits.add(new Fruit("Apple", "Winter fruit"));
        fruits.add(new Fruit("Pineapple", "Tropical fruit"));
    }

    @GET
    public Set<Fruit> list() {
        return fruits;
    }

    @POST
    public Set<Fruit> add(Fruit fruit) {
        fruits.add(fruit);
        return fruits;
    }

    @DELETE
    public Set<Fruit> delete(Fruit fruit) {
        fruits.removeIf(existingFruit -> existingFruit.name.contentEquals(fruit.name));
        return fruits;
    }
}
````

**Expected behavior**
Generation result should be:
```
   SetFruit:
     type: array
     items:
       $ref: '#/components/schemas/Fruit'
```
**Actual behavior**
```
    SetFruit:
      $ref: '#/components/schemas/SetFruit'`
```

**To Reproduce**
1. Sourcecode of Quarkus Openapi Guide: https://github.com/quarkusio/quarkus-quickstarts/tree/master/openapi-swaggerui-quickstart
2. Run Quarkus Openapi Example
2. Call http://localhost:8080/openapi

**Comment by EricWittmann** [comment]
Thanks for opening this, @ehora

**Comment by gsmet** [comment]
Just FYI, it would be nice if we could get the fix in Quarkus before the end of the week so that we can safely include it in 1.3.0.CR1.

Thanks!

**Comment by gsmet** [comment]
@MikeEdgar @EricWittmann can you tell me when you plan to release this fix? Just to know when we will get it in Quarkus.

Thanks!

**Comment by MikeEdgar** [comment]
@gsmet - sorry, lost track of this. @kenfinnigan - please go ahead with a release of 1.2.1.

**Comment by gsmet** [comment]
Thanks @MikeEdgar and @kenfinnigan !

**Comment by kenfinnigan** [comment]
Release build running

**Comment by kenfinnigan** [comment]
It's released, maybe a half hour or so to propagate to Central
