### ISSUE TITLE
Allow autogeneration of operation id

### ISSUE THREAD

**Issue by pilhuhn** [smallrye/smallrye-open-api#265]
Operation-ID is optional in the spec (https://swagger.io/docs/specification/paths-and-operations/ )

> operationId is an optional unique string used to identify an operation. If provided, these IDs must be unique among all operations described in your API.
> [..]
> Some common use cases for operationId are:
> 
>     Some code generators use this value to name the corresponding methods in code.
>     Links can refer to the linked operations by operationId.

It would be good according to the 2nd last line to have an option to generate the auto-operation id from e.g. the fully qualified class + method name. The class name-part could perhaps also be specified, so that users can use a shorter one in case the fqn is very long.

**Comment by phillip-kruger** [comment]
Do we want to do this by default if no operation Id is supplied ? Or should we have a config option that allows user to enable this functionality.

**Comment by MikeEdgar** [comment]
I would go with a config option, but it's not a strong opinion. If it's enabled by default, the option would allow turning it off.

**Comment by phillip-kruger** [comment]
Ok, Here is my plan, please let me know what you think.

1. We make this an explicit opt-in via config (then the new version can not break anything as by default it will work as always)
2. The config option is an enum that contains the naming strategy, one of METHOD, CLASS_METHOD, PACKAGE_CLASS_METHOD. The stragegy then taken when auto-generate this would be either just the methodName, or the className+methodName or the full name.
3. The auto-generate only occurs when the above is set and model does not get a id anywhere else (annotation, model etc)

Ja ? W.d.y.t ?

**Comment by MikeEdgar** [comment]
Sounds like a good approach to me.

**Comment by phillip-kruger** [comment]
@pilhuhn - see https://quarkus.io/guides/openapi-swaggerui#auto-generation-of-operation-id
