### ISSUE TITLE
How to add custom extension(AnnotationScannerExtension)?

### ISSUE THREAD

**Issue by rainmanhhh** [smallrye/smallrye-open-api#292]
OpenApiProcessor.modelFromAnnotations use OpenApiAnnotationScanner with singleton(readonly) list extension(which only process CompletionStage exclude CompletableFuture)

**Comment by MikeEdgar** [comment]
Hi @rainmanhhh, your comment is not entirely clear. What is the problem you are facing?

**Comment by rainmanhhh** [comment]
my controller method returns a CompletableFuture:
```
@GET
  @Path("hello")
  @Produces(MediaType.TEXT_PLAIN)
  fun hello() = CompletableFuture<String>().apply {
    launch {
      try {
        delay(1000)
        val result = "hello"
        complete(result)
      } catch (e: Throwable) {
        completeExceptionally(e)
      }
    }
  }
```
and the default scanner only unwrap CompletionStage&lt;T&gt; to T, not include classes implement it, such as CompletableFuture

**Comment by MikeEdgar** [comment]
Ok, I see. The `AnnotationScannerExtension` interface is not really usable from an application. It would be used by a server/runtime that integrates this library. 

I think the issue that needs to be addressed here is that `SchemaFactory#resolveAsyncType` is only checking for the `CompletionStage` interface and not implementations. This could be updated by replacing the name comparison `pType.name().equals(JDKConstants.COMPLETION_STAGE_NAME)` with a call to `TypeUtil#isA`.

Are you able to work around this? This could be updated for the upcoming 2.0 version.

**Comment by rainmanhhh** [comment]
I tried but failed :( 
quarkus defined a RESTEasyExtension using spi(in a wrong way) to load AsyncResponseProviders
I created a META-INF/services/javax.ws.rs.ext.Providers to specific my custom AsyncResponseProvider but classloader of RESTEasyExtension can't find it(maybe it will be loaded by another classloader)

hope your 2.0 release comping up(and quarkus upgade its dependencies) soon
before then I have to use CompletionStage explicitly in code

**Comment by EricWittmann** [comment]
Yeah I suspect you won't be able to leverage the SPI unless maybe you figure out how to do it at build time - since that's when Quarkus does most of its work, even for the MP OpenAPI stuff.  It's a relatively simple fix in SmallRye to fix this problem, but yeah it requires that you wait for a new release. :(
