### ISSUE TITLE
Allow generation of a static OpenAPI file

### ISSUE THREAD

**Issue by michael-schnell** [smallrye/smallrye-open-api#296]
It would be nice to have a way to generate a static OpenAPI file instead of doing this dynamically at runtime. This avoids error prone manual maintenance of the API definiton.

In general a static OpenAPI can be used to compare the current version against the previous version. This allows automated checks for backward compatibility. The file will then be created during a build and is part of the published JAR as normal with handcrafted OpenAPI files.

**Comment by phillip-kruger** [comment]
This should already be possible i think. That is how Quarkus use SmallRye Open API:

https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-openapi/runtime/src/main/java/io/quarkus/smallrye/openapi/runtime/OpenApiDocumentProducer.java

What runtime are you using ?

**Comment by michael-schnell** [comment]
If I understand the example correctly it's just the other way round: Read an already existing static file ("load the document from the generated JSON file"). I'm talking about creating a static file: Read Java code with all annotations, create an in-memory model and generate a static file from it (Seralize the in-memory model).

**Comment by phillip-kruger** [comment]
Ok I provided the code where the code is using the generated file, so the file will be created during build here I think : https://github.com/quarkusio/quarkus/blob/7894a228a825c4617469ccbb53fdead3bb392cf8/extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java#L274

**Comment by michael-schnell** [comment]
OK, thank you for the hint. I will take a look at it. Maybe I can extract something to allow an easy way of doing the same thing directly with SmallRye OpenAPI.

**Comment by phillip-kruger** [comment]
If you find a needed change in SmallRye that would make this easier to use, please reopen this issue, or even better, do a PR with the change :)

Closing this for now.
