### ISSUE TITLE
Wrong inheritance/polymorphism support ?

### ISSUE THREAD

**Issue by amoscatelli** [smallrye/smallrye-open-api#306]
In my JAX-RS resource Creable class extends Identifiable class

This is what is generated in the openapi file 

`    Identifiable:
      type: object
      properties:
        '@type':
          type: string
        id:
          type: string
        version:
          format: int64
          type: integer
     Creable:
      type: object
      properties:
        '@type':
          type: string
        id:
          type: string
        version:
          format: int64
          type: integer
        creation:
          format: date
          type: string`

Accoring to Openapi 3.0 documentation I expected this 

`    Identifiable:
      type: object
      properties:
        '@type':
          type: string
        id:
          type: string
        version:
          format: int64
          type: integer
     Creable:
      allOf:
        - $ref: "#/components/schemas/Identifiable"
        - type: object
      properties:
        creation:
          format: date
          type: string`

Why are the parent properties repeated by default ?

This is also a problem for polymorphism since this way a Creable isn't an Identifiable ...
So, for example, a service accepting an Identifiable as a parameter can't accept a Creable.

**Comment by osbeorn** [comment]
I have the same problem. Is there any workaround for this?

**Comment by edpri** [comment]
Same problem here, one workaround could be to use @Schema(allOf=Identifiable.class) in Creable on class level, but then i would need to remove "extends Identifiable" from there, otherwise i end up having duplicated fields, since scanner doesnt ignore parent class fields when allOf on class level is present. Any automatic way of doing this or can someone at least confirm it's a bug?

**Comment by MikeEdgar** [comment]
@edpri , confirmed. There is currently no way to disable having a class's hierarchy in-lined when Java inheritance is in use (via `extends`).

**Comment by edpri** [comment]
@MikeEdgar so only workaround i see there is having 2 sets of dtos, one set that ill use in rest controllers for deserializing jsons and one for generating openapi specs. For example.

dto for openapi
`@Schema(allOf = MyParentDTO.class)
public class MySpecDTO {
  ...fields here
}`

dto for deserializing
`public class MyDTO extends MyParentDTO {
   ...fields here
}`

and then use it in rest controller as such
`public Response createDTO(@Schema(implementation = MySpecDTO.class) MyDTO myDTO) {
   ...logic here
}`

This way i should have correct openapi.yaml generated. Does it seem like correct workaround approach for you?

**Comment by MikeEdgar** [comment]
@edpri - you will need to use `@Schema` inside of a `@RequestBody` to define the schema of the HTTP body. Your work-around description seems like it would work on the surface.
