### ISSUE TITLE
Create Maven/Gradle plugin to generate openapi schemafiles

### ISSUE THREAD

**Issue by marceloverdijk** [smallrye/smallrye-open-api#313]
Similar as this plugin for SmallRye GraphQL: https://github.com/smallrye/smallrye-graphql/issues/191

This is useful for storing the generated schema e.g. in git to track changes or share the generated schema across different teams.

**Comment by ewoks** [comment]
This will definitely be very useful.
Having it explicitly as an the artifact would be allow developers to share it without any additional effort.

**Comment by andrejpetras** [comment]
Hi,

we have a maven plugin based on the Smallrye OpenAPI library.
It is public and published in maven central repository.
Configuration is done by microprofile properties which could be set in the plugin configuration.

https://gitlab.com/1000kit/libs/maven/tkit-mp-openapi-plugin
