### ISSUE TITLE
Implement i18n logging and messages

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-open-api#318]
Follow the procedures defined in https://github.com/smallrye/smallrye-parent/wiki/I18N-Messages-and-Logging as part of implementing https://github.com/smallrye/smallrye-parent/issues/102 for all SmallRye projects

An example usage can be found in https://github.com/smallrye/smallrye-common

**Comment by mcserra** [comment]
Can i pick this one?

**Comment by kenfinnigan** [comment]
Sure!

**Comment by radcortez** [comment]
Nice to see Portuguese people around here :) Welcome!

**Comment by mcserra** [comment]
I have some doubts on this requirements: 

> All interfaces should be package-private and not public

In the `runtime.io` package there are logging per sub-package which follow the same pattern, I'm creating one interface per package but I'm wondering if it wouldn't be better to create one public class in `runtime.io` and pass one parameter. One example:

`Processing a @Contact annotation.` and `Processing a @Components annotation.`

**Comment by kenfinnigan** [comment]
In general it should be `package-private`, but if there's lots of sub packages you can use a single interface to prevent burning through groups of numbers for a couple of classes.

The main benefit is to prevent it from being usable as a "public API" of the project
