### ISSUE TITLE
Restore MP OpenAPI 1.1.2 Compatibility in master branch

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#321]
This issue is to track the need to release the master branch prior to the availability of MP OpenAPI 2.0. Non-breaking changes/features in MP OpenAPI 2.0 will be kept.

@phillip-kruger, @EricWittmann  - I assume `master` can still be released as SmallRye version `2.0`. If not, perhaps we can look at moving back to 1.3, etc. and keeping 2.0 for the MP version change. Thoughts?

**Comment by phillip-kruger** [comment]
I am happy that it still release as 2.0, as we have done some big refactoring.  But I am easy. @EricWittmann ?
