### ISSUE TITLE
Add support for mp.openapi.schema.FQCN to 1.x

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#335]
Add support for mp.openapi.schema.FQCN to 1.x

This should help with situations like what is described in quarkusio/quarkus#8810

**Comment by phillip-kruger** [comment]
Hi @MikeEdgar , Are you working on this ?

**Comment by MikeEdgar** [comment]
@phillip-kruger , yes. Are you planning a release shortly?

**Comment by phillip-kruger** [comment]
Yes. I want to create a release to include your fix for https://github.com/quarkusio/quarkus/issues/9538
that we can pull into Quarkus 1.5.1 and also want to do a release of 2.0.0 so we can pull the Spring stuff into Quarkus 1.6.

w.d.y.t ?

I can wait for this, would be good to have that issue resolved as well.

**Comment by MikeEdgar** [comment]
Release of both branches sounds good to me.

**Comment by phillip-kruger** [comment]
Do we need a fix in master for this too ?

**Comment by MikeEdgar** [comment]
This one is already there as part of the compatible 2.0 changes. I actually just cherry-picked that commit and did some touch-ups for 1.x.

**Comment by phillip-kruger** [comment]
Ok cool ! Thanks . So we can release both ?

**Comment by MikeEdgar** [comment]
Yes, in my view :-)
