### ISSUE TITLE
Annotation scanner NPE when processing JAX-RS endpoints with params of type SortedSet

### ISSUE THREAD

**Issue by fabiobrz** [smallrye/smallrye-open-api#349]
Hi, I've noticed that some RESTEasy tests failing against Wildfly when declaring REST resources methods accepting parameters of type `SortedSet`. 
Maybe I am missing something but looks like this is allowed by JAX-RS spec: https://docs.oracle.com/javaee/7/api/javax/ws/rs/FormParam.html 

The following stack trace represents the output of a deployment failure when an attempt to deploy a WAR with such a resource:

```
Caused by: java.lang.NullPointerException
	at io.smallrye.openapi.runtime.scanner.ParameterProcessor.setSchemaProperties(ParameterProcessor.java:637)
	at io.smallrye.openapi.runtime.scanner.ParameterProcessor.getFormBodyContent(ParameterProcessor.java:605)
	at io.smallrye.openapi.runtime.scanner.ParameterProcessor.process(ParameterProcessor.java:404)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.processJaxRsMethod(OpenApiAnnotationScanner.java:577)
	at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.lambda$processJaxRsResourceClass$0(OpenApiAnnotationScanner.java:422)
...
```

I've isolated a reproducer [1] which has three methods to demonstrate the failure: the first and the second ones (namely `formAsListOfString` and `formAsSetOfString`) take a `List` and a `Set` and are working fine, while the last one - `formAsSortedSetOfString` -, taking a `SortedSet`, fails. 
The methods are using `@FormParam` because it was the first case that I spotted but I've seen failures when using the same data type with `@QueryParam` and `@MatrixParam` as well.

The reproducer should fail by default. For a successful deploy the `formAsSortedSetOfString` method should be commented.

[1]
https://github.com/fabiobrz/microprofile-openapi-example/tree/sorted-set-repro

**Comment by phillip-kruger** [comment]
Hi @fabiobrz - What version of SmallRye OpenAPI ? master or 1.x ?

**Comment by phillip-kruger** [comment]
Nevermind, I can see it in your example app. Looking at it now.

**Comment by fabiobrz** [comment]
Yeah, sorry @phillip-kruger, my bad for not specifying it. It is 1.1.22

**Comment by phillip-kruger** [comment]
@MikeEdgar - I can confirm this is an issue. line 634 'SchemaFactory.typeToSchema(index, paramType, extensions);' return null if the parameter is a SortedSet. 

Can you confirm that this is a wildfly issue ? The Jandex index is not complete and needs to contain SortedSet ?

**Comment by MikeEdgar** [comment]
@phillip-kruger - I think this is a bug. `TypeUtil#isA` does not traverse up the interface hierarchy, only the class hierarchy. Since `SortedSet` is two removed from `Collection`, it's not properly detecting that. I think `TypeUtil#hasSuper` needs work to account for interface hierarchy. I've started looking down that path and I'll report back shortly.

**Comment by MikeEdgar** [comment]
@fabiobrz , @phillip-kruger - do you know if there needs to be a 1.1.23 or will Wildfly be moving up to 1.2.x?

**Comment by fabiobrz** [comment]
Hi @MikeEdgar. Wildfly master is using 1.2.3 already. That said, IMHO there should be a 1.1.23 for supported releases (e.g. productized versions).
BTW, I amm investigating some more issues that popped up when testing RESTEasy, so it could happen that more issues will be filed soon.

**Comment by fabiobrz** [comment]
Hi @MikeEdgar and @phillip-kruger. I see this was backported everywhere but I was wondering whether it could be added to the related milestones for clarity (e.g. 1.2.5). WDYT?

**Comment by MikeEdgar** [comment]
@fabiobrz - the only question is - which milestone? :-) The three PRs are now labelled with their respective milestone. Since only a single milestone can be tied to an issue, we'll have to pick one.
