### ISSUE TITLE
Annotation scanner NPE due to null parameter schema

### ISSUE THREAD

**Issue by fabiobrz** [smallrye/smallrye-open-api#359]
Opening this issue to follow up on the the discussion here https://github.com/smallrye/smallrye-open-api/issues/353#issuecomment-639556113.

**Comment by MikeEdgar** [comment]
I'm thinking the simplest fix would be to no longer return `null` as the `Schema` for unknown types (i.e. not indexed) and instead use the following simple object schema.

```json
{
     "type" : "object"
}
```

**Comment by MikeEdgar** [comment]
Just to add - as of #338, developers should be able to provide their own schema via configuration in both `master` (2.x) and 1.x (but not 1.1.x) if the simple object schema is undesirable.

**Comment by fabiobrz** [comment]
> I'm thinking the simplest fix would be to no longer return `null` as the `Schema` for unknown types (i.e. not indexed) and instead use the following simple object schema.
> 
> ```json
> {
>      "type" : "object"
> }
> ```

Seems reasonable to me too.

> developers should be able to provide their own schema via configuration in both master (2.x) and 1.x (but not 1.1.x) if the simple object schema is undesirable.

And I am still wondering how - being all about the same JAX-RS resource class - the annotation scanning behaves differntly - e.g. the index is substantially different. But I must admit that I am not into the code details and could spend just a few hours around the whole thing.

**Comment by MikeEdgar** [comment]
Do you know if Wildfly includes the RestEasy classes in the index? I was able to reproduce the issue in a unit test using a `@FormParam` of type `org.jboss.resteasy.plugins.providers.multipart.InputPart` which is not in the index.

**Comment by fabiobrz** [comment]
Hi @MikeEdgar I am not aware of that but can check. Do you think you could share your repro with me?
Also - can this fix be merged for 1.1.x, too? @phillip-kruger WDYT?

**Comment by phillip-kruger** [comment]
@fabiobrz Sure ! Can you do a PR ?

**Comment by fabiobrz** [comment]
Hi @phillip-kruger - done, see https://github.com/smallrye/smallrye-open-api/pull/362.
Do you think this could be added to https://github.com/smallrye/smallrye-open-api/milestone/11?
I don't know whether it is to late to use it but let's see.

**Comment by phillip-kruger** [comment]
We have not yet released 1.1.23 a.f.a.i.k

**Comment by fabiobrz** [comment]
Sure, I can see it. I was wondering whether it will be used in a close Wildfly/productized release. Just that.

**Comment by phillip-kruger** [comment]
I am not sure .
