### ISSUE TITLE
There is some promblem in ParameterProcessor.java

### ISSUE THREAD

**Issue by hubinix** [smallrye/smallrye-open-api#363]
https://github.com/smallrye/smallrye-open-api/blob/1cd81b4943b3a8a6cd96be05bf07dc7a3b2d9e1b/extension-jaxrs/src/main/java/io/smallrye/openapi/jaxrs/ParameterProcessor.java#L654

We want to input JWT(JsonWebToken) in http header,from swagger-ui 's page.
But  isIgnoredParameter function ingnored the AUTHORIZATION parameter. 
The AUTHORIZATION parameter can not be seen from the swagger-ui , and we can not from the "try it out " button.

**Comment by phillip-kruger** [comment]
Are you using the security annotations from OpenAPI ?
https://swagger.io/docs/specification/authentication/bearer-authentication/

See this blog as an example:

https://kostenko.org/blog/2020/02/jwt-openapi-microprofile-quarkus.html

You should not treat it as a normal header parameter, but rather use the security fields. Then swagger ui will work

**Comment by hubinix** [comment]
> Are you using the security annotations from OpenAPI ?
> https://swagger.io/docs/specification/authentication/bearer-authentication/
> 
> See this blog as an example:
> 
> https://kostenko.org/blog/2020/02/jwt-openapi-microprofile-quarkus.html
> 
> You should not treat it as a normal header parameter, but rather use the security fields. Then swagger ui will work

it works, thank you very much!
