### ISSUE TITLE
How to add descriptions or examples in swagger-ui http response json body.

### ISSUE THREAD

**Issue by liukch** [smallrye/smallrye-open-api#365]
As the describe of the title, I want to add describes or examples in swagger-ui http response json body.
In openapi.yml, we can use a node like properties

```
  Pet:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      id:
        type: "integer"
        format: "int64"
      category:
        $ref: "#/definitions/Category"
      name:
        type: "string"
        example: "doggie"
      photoUrls:
        type: "array"
        xml:
          name: "photoUrl"
          wrapped: true
        items:
          type: "string"
      tags:
        type: "array"
        xml:
          name: "tag"
          wrapped: true
        items:
          $ref: "#/definitions/Tag"
      status:
        type: "string"
        description: "pet status in the store"
        enum:
        - "available"
        - "pending"
        - "sold"
    xml:
      name: "Pet"
``` 
But if use annotations, what should I do to get the same output.

**Comment by MikeEdgar** [comment]
@liukch - did you get the response you were looking for with the `@Schema` annotation's `description` and/or `example` properties?

**Comment by liukch** [comment]
@MikeEdgar 
I've tried use description or example in @Schema annotation.
But it is used to describe the whole of http response,
I want describe every element in response Json, not the whole response, 
Just make it has the same effect with the above openapi.yml

**Comment by liukch** [comment]
This is my one annotation on api: 
``` java
    @Path("/")
    @GET
    @Operation(
        summary = "foo.",
        description = "bar."
    )
    @APIResponses({
        @APIResponse(
            responseCode = "200",
            description = "Request has succeed.",
            content = @Content(
                mediaType = MediaType.APPLICATION_JSON,
                schema = @Schema(
                    type = SchemaType.OBJECT,
                    name = "getFoo",
                    implementation = GetFooResponse.class
                )
            )
        ),
        @APIResponse(responseCode = "401", ref = "#/components/responses/UnauthorizedResponse"),
        @APIResponse(responseCode = "500", ref = "#/components/responses/InternalErrorResponse")
    })
``` 
I want describe or example every element in ``GetFooResponse.class``
How cant I do?

**Comment by MikeEdgar** [comment]
@liukch - if you have the source code for `GetFooResponse`, you can annotate the fields in that class with `@Schema` and use `description` or `example` for each.

**Comment by liukch** [comment]
@MikeEdgar 
It worked, thanks!

**Comment by SimoBkr** [comment]
how can i add attribute example to our json file with the object response

**Comment by MikeEdgar** [comment]
Hi @SimoBkr, do you have an sample of what you're trying to do? Are you using annotation scanning?
