### ISSUE TITLE
Support java.time.Duration and java.time.Period

### ISSUE THREAD

**Issue by lucamolteni** [smallrye/smallrye-open-api#368]
Currently `java.time.Period` and `java.time.Duration` are shown in this way while using smallrye-open-api 1.2.4.Final

![openapi-period](https://user-images.githubusercontent.com/454752/84759075-8cde8480-afc6-11ea-88b0-a604bd835bd6.png)

Needless to say, this is not the correct way to provide a Duration or a Period in a REST endpoint.

We'd like to have a better example for that, so I fixed the 1.2.4 release on this branch

https://github.com/smallrye/smallrye-open-api/compare/1.2.4...lucamolteni:period-duration-124?expand=1

Unfortunately there's no 1.2.x branch on this repository and I'm not sure how to create a PR there.

I also read this shouldn't be the "canonical" way to support custom formats and that they're discussing the way to do in the specification, but as smallrye-open-api supports most of `java.time` classes I think it'd make sense to support all of them.

Here's the output from my branch

![Screen Shot 2020-06-16 at 11 45 51](https://user-images.githubusercontent.com/454752/84759417-f9f21a00-afc6-11ea-9e01-e48ea6d1a35c.png)

**Comment by MikeEdgar** [comment]
This is an interesting idea, although I think both `Duration` and `Period` are "durations" from an ISO perspective: https://en.wikipedia.org/wiki/ISO_8601#Durations
