### ISSUE TITLE
Request: Modify SmallRye specific MP Config properties to include vendor name

### ISSUE THREAD

**Issue by msmiths** [smallrye/smallrye-open-api#370]
## Overview

Section 3.1.2, "Vendor extensions", of the MP OpenAPI specification allows vendors to define vendor-specific configuration via MP Config. Any vendor-specific properties must be prefixed with `mp.openapi.extensions`.

The SmallRye implementation has used this mechanism to define the following SmallRye specific MP Config properties:

- mp.openapi.extensions.scan-dependencies.disable
- mp.openapi.extensions.scan-dependencies.jars
- mp.openapi.extensions.schema-references.enable
- mp.openapi.extensions.custom-schema-registry.class
- mp.openapi.extensions.application-path.disable

However, when embedding the SmallRye implementation into other runtimes it is not clear where these MP Config properties originate. This is exacerbated if the consuming runtime defines its own vendor-specific MP Config properties, alongside those inherited from the SmallRye implementation.

It would be useful to rename these properties to include `smallrye` in the property name to remove this ambiguity.  For example:

- mp.openapi.extensions.smallrye.scan-dependencies.disable
- mp.openapi.extensions.smallrye.scan-dependencies.jars
- mp.openapi.extensions.smallrye.schema-references.enable
- mp.openapi.extensions.smallrye.custom-schema-registry.class
- mp.openapi.extensions.smallrye.application-path.disable

**Comment by phillip-kruger** [comment]
Thanks @msmiths :)

**Comment by radcortez** [comment]
For renames you can use this:
https://smallrye.io/docs/smallrye-config/interceptors/interceptors.html#relocate-interceptor :)

**Comment by msmiths** [comment]
@radcortez This would place a runtime dependency on `smallrye-config` and I am looking to embed `smallrye-open-api` inside OpenLiberty where the MP Config implementation is not guaranteed to be SmallRye.

**Comment by radcortez** [comment]
Sure :)
