### ISSUE TITLE
Request: ParameterImpl::setIn should set required = true for In.PATH

### ISSUE THREAD

**Issue by msmiths** [smallrye/smallrye-open-api#372]
## Overview

The current implementation of the `ParameterImpl::setIn` method simply sets the value of the **in** attribute, as follows:

```
@Override
public void setIn(In in) {
    this.in = in;
}
```
However, the Open API Specification states the following with relation to the **required** property on the **Parameter Object**:

> Determines whether this parameter is mandatory. If the parameter location is "path", this property is REQUIRED and its value MUST be true. Otherwise, the property MAY be included and its default value is false.

As a result, consumers of the SmallRye implementation of OpenAPI must explicitly set **required** to `true` on a path `Parameter`... which requires more code.

It would be more convenient to update the implementation as follows:

```
@Override
public void setIn(In in) {
    if (in == In.PATH) {
        this.required = true;
    }
    this.in = in;
}
```

**Comment by MikeEdgar** [comment]
@msmiths - this is only dealing with the model class correct? I think there may already be something in the annotation scanner that sets the `required` flag to `true` for path parameters.

**Comment by msmiths** [comment]
@MikeEdgar Yes... I see code in the `ParameterProcessor` class in the `extension-jaxrs` module that handles this... so it is just for the model class.
