### ISSUE TITLE
Inline schemas are also updating global components/schemas

### ISSUE THREAD

**Issue by msmiths** [smallrye/smallrye-open-api#399]
## Overview

Use of the `@Schema` annotation that results in an inline schema being generated also appears to result in the global definition of the schema being updated in `components/schemas`.

You can see this in the `AirlinesAppTckTest`.

The **User** schema is defined on the `JAXRSApp` class, as follows:

```
components = @Components(
    schemas = {
         ...
        @Schema(name = "User", implementation = User.class, properties = {
            @SchemaProperty(name = "phone", description = "Telephone number to contact the user"),
            @SchemaProperty(name = "foo", description = "bar")
         })},
```

The **User** class is also referenced by the `@Schema` annotation on the `UserResource::createUser` method but, since this is not a simple use of the `@Schema` annotation, it should result in an inline schema being generated and should not result in any changes to the **User** schema in the global `components/schemas`. The relevant annotation is as follows:

```
    @RequestBody(
        ...
        content = @Content(
            mediaType = "application/json",
            schema = @Schema(
                name = "testUser",
                type = SchemaType.OBJECT,
                maxProperties = 1024,
                minProperties = 1,
                required = true,
                implementation = User.class
            ),
        ...
```
However, the `components/schemas/User` schema that is generated in the OpenAPI document for the `airlines.war` application is as follows:
```
      "User" : {
        "maxProperties" : 1024,
        "minProperties" : 1,
        "required" : [ "id", "username", "password", "age", "email", "firstName", "gender", "lastName", "phone", "status" ],
        "type" : "object",
        "properties" : {
          "age" : {
            "format" : "int32",
            "type" : "integer",
            "example" : 37
          },
          "email" : {
            "type" : "string",
            "example" : "bob@test.ca"
          },
          "firstName" : {
            "type" : "string",
            "example" : "Bob"
          },
          "gender" : {
            "allOf" : [ {
              "$ref" : "#/components/schemas/Gender"
            }, {
              "example" : "M"
            } ]
          },
          "id" : {
            "format" : "int32",
            "type" : "integer",
            "example" : 3456
          },
          "lastName" : {
            "type" : "string",
            "example" : "Smith"
          },
          "password" : {
            "type" : "string",
            "example" : "bobSm37"
          },
          "phone" : {
            "type" : "string",
            "example" : "123-456-7890"
          },
          "status" : {
            "format" : "int32",
            "title" : "User Status",
            "type" : "integer"
          },
          "userName" : {
            "type" : "string",
            "example" : "user1"
          }
        }
      },
```
Notice that the schema has been updated to reflect the `maxProperties` and `minProperties` that are defined on `@Schema` annotation on the `UserResource::createUser` method.

**Comment by MikeEdgar** [comment]
Thanks for opening this. To me the ideal situation would be a local schema on the operation, with an `allOf` that references the global schema and lists the local schema properties. Are you thinking something like that or that the operation schema should be fully inline?

**Comment by msmiths** [comment]
@MikeEdgar Using `allOf` would certainly be less verbose but it can make the definition more obscure/difficult to read. There is also the possibility that the `@Schema` annotation in question could specify its own `allOf`, `oneOf` or `anyOf` attributes, which could make things more complex.

One example making the generated OpenAPI more difficult to read is how we handle the `Gender` enum in the same TCK test. An entry is correctly generated in `/components/schemas`, as follows:
```
  Gender:
    enum:
    - Male
    - Female
    - Other
    type: string
```
However, the `gender` property in `/components/schema/User` is generated as follows:
```
  gender:
    allOf:
    - $ref: '#/components/schemas/Gender'
    - example: M
```
While this is still "correct" (ignoring the fact that the example does not match any of the enum values) and is caused by a separate `@Schema` annotation being specified on the `gender` property in the `User` class, I cannot help thinking that a more concise approach is to merge `example` into the definition of the schema, i.e.:
```
  Gender:
    type: string
    example: M
    enum:
    - Male
    - Female
    - Other
```
Of course, you could argue that this should be achieved by moving the definition of the example into `@Schema` annotation on the `Gender` enum. But it does raise another issue with the code that generates the OpenAPI doc when inlining schemas... the `gender` property that is generated on the inline schema that results from the `@Schema` annotation on the  `UserResource::createUser` is as follows:

```
  gender:
    allOf:
    - $ref: '#/components/schemas/Gender'
    - example: M
    - $ref: '#/components/schemas/Gender'
    - example: M
    - $ref: '#/components/schemas/Gender'
    - example: M
    - $ref: '#/components/schemas/Gender'
    - example: M
```
I will raise a separate issue for this problem.

**Comment by MikeEdgar** [comment]
@msmiths - having the merged behavior was the original way SmallRye worked, but it was changed to the current behavior (one of my first contributions, :-D ). I think when you have a small API or you are looking at a single operation, it make sense to in-line the schemas. However, the larger things get, you may lose track that the same model is used in multiple places. Looking at the raw output requires some additional connect-the-dots, but things like Swagger UI should handle it properly and display the schemas inline in the UI. There is a config option `mp.openapi.extensions.smallrye.schema-references.enable` to shut it off, but I think the TCK should pass either way, and the issue of the schema in components being updated with the local `@Schema` properties is definitely a bug.

**Comment by MikeEdgar** [comment]
@msmiths - I believe the schema for `User` above is correct. Although `UserResource::createUser` has the `maxProperties` and `minProperties`, they are also specified in the `@Schema` annotation directly on `User`. If you agree, let's close this one. 

I think the enumeration issue may be solved on the branch we've been discussing.

**Comment by msmiths** [comment]
@MikeEdgar Agreed... looking at the `User` class in more details, I see that this is where the `maxProperties` and `minProperties` values are coming from. Closing the issue.
