### ISSUE TITLE
AnnotationScannerFactory is hard coded to load AnnotationScanner instances from the TCCL.

### ISSUE THREAD

**Issue by pferraro** [smallrye/smallrye-open-api#404]
OpenApiProcessor.modelFromAnnotations(...) creates a new OpenApiAnnotationScanner instance which currently loads AnnotationScanner instances from the TCCL.  Given that smallrye has no control which thread will call this method, it cannot assume that the intended annotation scanner instances (or indeed, if any) will be loadable from the TCCL.

Ideally OpenApiProcessor.modelFromAnnotations(...) should accept a ClassLoader instance from which to load AnnotationScanner instances.

**Comment by pferraro** [comment]
@phillip-kruger I don't think this fix is sufficient.  AnnotationScannerFactory still loads AnnotationScanner instances using the TCCL, instead of the classloader passed to the OpenApiProcessor.modelFromAnnotations(...) method.  See:
https://github.com/smallrye/smallrye-open-api/blob/master/core/src/main/java/io/smallrye/openapi/runtime/scanner/spi/AnnotationScannerFactory.java#L19

**Comment by phillip-kruger** [comment]
Thanks, I'll look again in the morning
