### ISSUE TITLE
Vert.x: Default when no method is ALL

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-open-api#416]
At the moment, the default method when none given is GET, but it should be all methods.

**Comment by mkouba** [comment]
For the record, reactive routes mimic the behavior defined by [io.vertx.ext.web.Route](https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/Route.java#L37-L45).
