### ISSUE TITLE
Private properties are included the generated OpenAPI document

### ISSUE THREAD

**Issue by msmiths** [smallrye/smallrye-open-api#418]
## Overview

The SmallRye implementation generates an entry for a property in a schema, even if the property in the POJO is declared as private and there are no getters/setters/annotations on the property. For example, if I have the following POJO which declares a private `testProperty`, as follows:

```
@Schema(
    title = "Pet",
    discriminatorProperty = "petType"
)
@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, include=JsonTypeInfo.As.EXISTING_PROPERTY, property="petType")
@JsonSubTypes({
    @JsonSubTypes.Type(value=Cat.class, name=Constants.ENUM_PET_TYPE_CAT),
    @JsonSubTypes.Type(value=Dog.class, name=Constants.ENUM_PET_TYPE_DOG)
})
public abstract class Pet {
    @Schema(required = true)
    public PetType petType;

    private String testProperty;

    public Pet() {
    }

    public Pet(PetType petType) {
        this.petType = petType;
    }
}
```

... the schema that is generated in `/components/schemas` is as follows:

```
    Pet:
      title: Pet
      required:
      - petType
      type: object
      properties:
        petType:
          $ref: '#/components/schemas/PetType'
        testProperty:
          type: string
      discriminator:
        propertyName: petType
```

**Comment by MikeEdgar** [comment]
I think this should be done, but maybe wait for a major release? @phillip-kruger , @EricWittmann what are your thoughts on this? I imagine there may be some applications unknowingly using this "feature" or somehow working around it.

**Comment by phillip-kruger** [comment]
Yea maybe we add it to a major release and allow changing the behaviour (back to what it is now) via config ?
