### ISSUE TITLE
Support multi-level interface inheritance

### ISSUE THREAD

**Issue by gtnicol** [smallrye/smallrye-open-api#423]
I have an inheritance hierarchy like Note<-extends-MutableEntity<-extends-ImmutableEntity and the documentation generated for Note does not include properties from ImmutableEntity. From looking at the code, it appears to only scan parent interfaces requiring Note to extend both interfaces.

**Comment by MikeEdgar** [comment]
@gtnicol , it is supposed to scan all parent classes and interfaces so we'll call this a bug :-)

Can you post the Java code you're scanning and the incorrect output? That will help get things moving more quickly on a fix.

**Comment by gtnicol** [comment]
This is a Quarkus project using `quarkus-smallrye-openapi`... would you like me to produce a small project that demonstrates the issue? Probably easiest for debugging...

**Comment by MikeEdgar** [comment]
Yes, please. A demo project would be great.

**Comment by gtnicol** [comment]
Here we go. On the Note interface if you add/remove ImmutableEntity you can see the properties displayed by the online docs change (expected.png vs actual.png).
[openapi-swaggerui-quickstart.tar.gz](https://github.com/smallrye/smallrye-open-api/files/4996918/openapi-swaggerui-quickstart.tar.gz)
