### ISSUE TITLE
Remove the mp.openapi.extensions.smallrye.schema-references.enable MP Config property...

### ISSUE THREAD

**Issue by msmiths** [smallrye/smallrye-open-api#446]
## Overview

The `mp.openapi.extensions.smallrye.schema-references.enable` MP Config property appears left over the implementation of support for `$ref`... apparently it was added when support for `$ref` was still experimental. Now that the implementation of `$ref` support is complete, this property should be removed.

**Comment by MikeEdgar** [comment]
Closed by #465
