### ISSUE TITLE
Support extensions to JAX-RS

### ISSUE THREAD

**Issue by FroMage** [smallrye/smallrye-open-api#46]
RESTEasy supports additions to JAX-RS, such as:

- `@FormParam`, `@QueryParam` etc… that have an optional parameter name and uses the annotated param/field name
- reactive return types such as RxJava `Single` or `Flowable`

Additionally, I know of applications that do not require `Application` classes to set up jax-rs resources.

It would be great to have extension points in smallrye-open-api to be able to hook into in order to support this behaviour. Swagger has such extension points that I was able to use for that.

**Comment by FroMage** [comment]
For example, see https://github.com/FroMage/redpipe/blob/master/redpipe-engine/src/main/java/net/redpipe/engine/swagger/RxModelConverter.java and https://github.com/FroMage/redpipe/blob/master/redpipe-engine/src/main/java/net/redpipe/engine/core/Server.java#L390

**Comment by FroMage** [comment]
And for custom parameter annotations: https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/ext/OpenAPIExtension.java and https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs2/src/main/java/io/swagger/v3/jaxrs2/DefaultParameterExtension.java

**Comment by FroMage** [comment]
I'll try to prototype something and do a PR.

**Comment by EricWittmann** [comment]
Oh that'd be great!

**Comment by FroMage** [comment]
Actually in the case of `@*Param` I can't solve this just with an extension as Jandex does not have the parameter names. I'll see if we can get Jandex to support this.

**Comment by EricWittmann** [comment]
My understanding is that method parameter names are simply not part of the java bytecode.  Admittedly my knowledge in this area is quite stale, so perhaps that has changed.

**Comment by FroMage** [comment]
It is part of the bytecode, with an option to Javac. https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html

**Comment by MikeEdgar** [comment]
@FroMage - are there any other cases not being covered or can this be closed?

**Comment by MikeEdgar** [comment]
Closing - please re-open or open a new issue if anything else needs to be covered.
