### ISSUE TITLE
[1.1] ModelConstructionTckTest is not executing any tests

### ISSUE THREAD

**Issue by jmini** [smallrye/smallrye-open-api#48]
As discussed here: https://github.com/smallrye/smallrye-open-api/issues/44#issuecomment-439798885

`ModelConstructionTckTest` is green because none of the tests are executed.
I guess this is a TestNG / JUnit issue...

If you revert some changes made with 24d4fd7d9eb85a27c612c2175a466cbfeeb29305 the test should fail.

The maven build is running JUnit Surefire and the TCK Tests are written with TestNG (`@org.testng.annotations.Test`). The tests are ignored.

If you run it inside your IDE with the TestNG runner, then you see test results. I can not run the class with the JUnit runner in my IDE.

**Comment by EricWittmann** [comment]
Yeah I didn't get around to fixing that yet.  But I haven't forgotten!

**Comment by EricWittmann** [comment]
Hey @jmini - can you have a look at this PR?

https://github.com/smallrye/smallrye-open-api/pull/49

**Comment by EricWittmann** [comment]
Fixed in https://github.com/smallrye/smallrye-open-api/pull/49
