### ISSUE TITLE
2.0.x releases depend on Quarkus 999-SNAPSHOT

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-open-api#507]
This is because of https://github.com/smallrye/smallrye-open-api/blob/2.0.x/extension-vertx/pom.xml#L17 and causes mildly annoying troubles during productization :-)

**Comment by phillip-kruger** [comment]
Sorry, that should be fixes. I fixed in master but never applied to this branch. I'll do so now. How urgent is this ? Should we do a release with just this ?

**Comment by phillip-kruger** [comment]
Fixed, let me know if you need a release.

**Comment by Ladicek** [comment]
No, I don't need a release, it's easy to workaround. But if there will be more releases in the 2.0.x branch, they will be a tiny bit better :-)
