### ISSUE TITLE
Ignore some classes for schema generation by default

### ISSUE THREAD

**Issue by neon-dev** [smallrye/smallrye-open-api#508]
Since upgrading from Thorntail to Quarkus, the schema generation became much more verbose.

1. For every `Set` and `List` an anonymous type is generated, which clutters the Swagger UI Schema overview.
2. `javax.json.JsonValue` and its descendants are also listed and all their getters are parsed (generates another schema for `JsonValue.ValueType` for example).
3. Date fields are now parsed too, even though they're almost never transmitted as a complex object but as a string or number.

Here's an old vs. current comparison:
<img src="https://user-images.githubusercontent.com/1169307/96020157-e4dea800-0e4d-11eb-96ca-5142f4a60587.png" alt="old" width="350"> <img src="https://user-images.githubusercontent.com/1169307/96021037-2e7bc280-0e4f-11eb-8138-2c1c0b44b736.png" alt="new" width="350">
Left was under Thorntail 2.5, right is with Quarkus 1.8.3.

I propose to not autogenerate schemas for those types, since they don't provide much additional info and at the cost of clarity. Especially when those are inner fields and not the root node. Knowing what's a Set, List or Date interally doesn't really make a difference since we're still talking REST, so there's no corresponding type. Auto generating a hint at the field level might be an alternative, if we don't want to omit the info completely.

Thanks for considering.

**Comment by MikeEdgar** [comment]
Hi @neon-dev , are you able to also share the yaml or json for each version of the API?

**Comment by neon-dev** [comment]
Sure. Hopefully it helps, because I had to redact some info since it's work related:
[openapi.zip](https://github.com/smallrye/smallrye-open-api/files/5380647/openapi.zip)

Now that I inspected the file itself, it looks like `@XmlAccessorType(XmlAccessType.FIELD)` is ignored too in the newer file. There are private methods in the schema which have no relation to any field, so that's wrong.

**Comment by MikeEdgar** [comment]
Thanks, that helps. It seems that the biggest issue is that `@XmlAccessorType` is not being considered, correct? The extraction and referencing of schemas is more of an annoyance, but generally correct information? I also agree that things like `JsonString` should not be generating the way they are in your example.

**Comment by neon-dev** [comment]
Yeah, I think too that the `@XmlAccessorType` issue is the biggest one, as it generates wrong info. The rest is just overly verbose info, which I'd love to see get cut down a bit.
So let's summarize:
1. Bug: `@XmlAccessorType` is not considered when generating schemas
2. `Collection<>`s, `List<>`s and `Set<>`s should not generate dedicated `Collection*`/`List*`/`Set*` schema entries. After all they're arrays in JSON / element lists in XML and therefore do not need custom types.  
As previously said, we still could include the info about the exact collection type as an auto generated description, if really needed.
3. `javax.json.JsonValue` and its descendants should not get schema entries and instead be treated like their primitve counterparts.
4. `java.util.Date` should not get a dedicated schema and instead be handled like before (see field `registrationDate` in openapi_old inside the zip file I uploaded yesterday)

**Comment by neon-dev** [comment]
Great work, thanks!
