### ISSUE TITLE
Duplicated root-path in OpenAPI document for JAX-RS sub-resource

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-open-api#518]
Reported by @andbin  in Quarkus (https://github.com/quarkusio/quarkus/issues/12803)

I have found that OpenAPI duplicates the root-path (from quarkus.http.root-path property in application.properties) when there is a JAX-RS "sub-resource".

```
package sample;

import javax.ws.rs.Path;

@Path("sample")
public class SampleResource {
    @Path("subresource")
    public SubResource subResource() {
        return new SubResource();
    }
}
```

```
package sample;

import javax.ws.rs.GET;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

public class SubResource {
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "HELLO from SubResource!";
    }
}
```

The greeting message is available at http://localhost:8080/dummyapp/sample/subresource .
However, the OpenAPI document shows:

paths:
/dummyapp/dummyapp/sample/subresource:

which does not exist. And clearly, this is also what Swagger UI shows.

**Comment by andbin** [comment]
I noticed that the problem also involves the other property named `quarkus.resteasy.path`.
Just to be clear:

Case A) With just only the property:
```properties
quarkus.resteasy.path = /api
```

The path in OpenAPI document results in: **/api/api**/sample/subresource

Case B) With the two properties:
```properties
quarkus.http.root-path = /dummyapp
quarkus.resteasy.path = /api
```

The path in OpenAPI document results in: **/dummyapp/api/dummyapp/api**/sample/subresource

**Comment by phillip-kruger** [comment]
Hi @andbin - thanks for the extra info. We will fix this a.s.a.p. You are also welcome to give it a go and do a PR if you are keen ?

**Comment by andbin** [comment]
> You are also welcome to give it a go and do a PR if you are keen ?

Sorry, I have little/no familiarity with SmallRye projects internals, thus I cannot contribute in reasonable time.

**Comment by MikeEdgar** [comment]
@phillip-kruger - does Quarkus generate some synthetic class that is then available in the Jandex index? I'm trying to understand how the quarkus properties would impact the SmallRye scanner.

**Comment by phillip-kruger** [comment]
@MikeEdgar - I am not sure... Is the subresource working fine in SmallRye ? Do we have test cases for that ?

**Comment by MikeEdgar** [comment]
@phillip-kruger , there are test cases for sure. It is supposed to use the application path like the other types of scan which made me wonder about a synthetic or generated class being passed from quarkus.

**Comment by andbin** [comment]
Just an extra info: I tried to add another sub-resource step, that is, a sub-resource of a sub-resource (not really useful in practice but just to try).
The path in OpenAPI document results in: **/dummyapp/dummyapp/dummyapp**/sample/subresource/subresource2

It seems that each step brings again the root path in a recursive way ....

**Comment by phillip-kruger** [comment]
Thanks @MikeEdgar - I am looking at this. Problem is with the scanner context root.

**Comment by phillip-kruger** [comment]
Fix. will be pulled into Quarkus 1.10.
