### ISSUE TITLE
AllOf for enum

### ISSUE THREAD

**Issue by bartman86** [smallrye/smallrye-open-api#520]
After generation of open api for any java enum field contains  "allOf" insterad of schema for reference to external Enum class e.g.
`Test:
          allOf:
          - $ref: '#/components/schemas/Test'
          - enum:
            - ABC
            - CDE

Test:
      enum:
      - ABC
      - CDE
      type: string

`

Based on open api documentation correct format is 
`
`Test:
          allOf:
          - $ref: '#/components/schemas/Test'

Test:
      enum:
      - ABC
      - CDE
      type: string

`

**Comment by MikeEdgar** [comment]
@bartman86 , can you also share the Java code that is generating this?

**Comment by bartman86** [comment]
ach... I finaly discovered what is the issue here, when I was writing some simple example to attach it.
1. Generation of api is done by maven plugin, but in this case it is irrelevant 
2. This issue is caused by @NotNull annotation which is on top of Enum call e.g
`
class TransferObject{
@javax.validation.constraints.NotNull;
Test test; //Test is en enum
}
`
With @Valid annotation it is generated allOf and without it output is ok it sth like:
Test:
 $ref: '#/components/schemas/Test'
