### ISSUE TITLE
Generated schema for Java class with enum field

### ISSUE THREAD

**Issue by flo-ryan** [smallrye/smallrye-open-api#546]
First, I'm not sure if this is a bug or just my lack of understanding of the annotations.

I have a Java class with an enum field and I'd like to generate a schema for this class. 
I'd like to generate a schema/type for the enum ("Genre") which is then referenced by the genre field in the book's schema.

```
public enum Genre
{
    FANTASY,
    ROMANCE,
    THRILLER
}

public class Book
{
    private String title;
    private Genre genre;
}
```

If I annotate the genre field like this, setting the enum class as implementation, the enum is generated inline in the schema and not referenced:
```
@Schema(description = "the book's genre", implementation = Genre.class)
private Genre genre;
```
```
  "Book" : {
	"type" : "object",
	"properties" : {
	  "genre" : {
		"description" : "the book's genre",
		"enum" : [ "FANTASY", "ROMANCE", "THRILLER" ],
		"type" : "object"
	  },
	  "title" : {
		"description" : "the book's title",
		"type" : "string",
		"example" : "Lord of the Rings"
	  }
	}
  },
```

If I leave out the implementation, I get this weird generated schema using model composition (maybe due to Void.class being the default for the implementation attribute?):
```
@Schema(description = "the book's genre")
private Genre genre;
```
```
  "Genre" : {
	"enum" : [ "FANTASY", "ROMANCE", "THRILLER" ],
	"type" : "string"
  },
  "Book" : {
	"type" : "object",
	"properties" : {
	  "genre" : {
		"allOf" : [ {
		  "$ref" : "#/components/schemas/Genre"
		}, {
		  "description" : "the book's genre"
		} ]
	  },
	  "title" : {
		"description" : "the book's title",
		"type" : "string",
		"example" : "Lord of the Rings"
	  }
	}
  },
```
I've only annotated the fields of Book.class with @Schema, so no annotations on Book.java or on/in Genre.java

Am I using the wrong annotations?
Or do I need to set the Schema annotation's attributes differently?
Or it it somehow not possible to reference the schema/type for an enum field (but only to have it inline)?
Or is this simply a bug?

Thanks a lot in advance!

**Comment by MikeEdgar** [comment]
Hi @flo-ryan - did you try putting the `@Schema` annotation on the `Genre` enum itself (and omitting it on the field)? That may give you the output you are looking for.

**Comment by flo-ryan** [comment]
@MikeEdgar thanks a lot for your quick response!
Your suggestion does indeed result in what I'm looking for:
```
  "genre" : {
	"$ref" : "#/components/schemas/Genre"
  },
```
Does this mean though, that there is no way to add a description/example/etc to this field?
I want the enum to be referenced instead of inline, because I want to be able to re-use it, e.g. have a genre field in `Book.java` but also `Movie.java`. So it would be great if I could add different descriptions and examples for the genre field, for each field where the enum is used.

**Comment by MikeEdgar** [comment]
@flo-ryan - is the description different for `Book` and `Movie`? In that case, you can go back to what you did earlier and place the `@Schema` with a `description` on those fields. The `allOf` schema attribuite that is generated allows you to compose the common schema information (via the `$ref`) with the model-specific descriptions.

**Comment by flo-ryan** [comment]
@MikeEdgar I would like the descriptions to be potentially different, if possible, yes.
So you mean going back to my second approach?
```
@Schema(description = "the book's genre")
private Genre genre;
```
And it is "normal" that the generated schema looks like this?
```
  "genre" : {
	"allOf" : [ {
	  "$ref" : "#/components/schemas/Genre"
	}, {
	  "description" : "the book's genre"
	} ]
  },
```
I'm asking because this then creates some issues when I'm generating the Typescript API based on this schema.

**Comment by MikeEdgar** [comment]
@flo-ryan - that's right. Using the `allOf` format is saying that the schema of the `genre` property is the logical union of every schema in the `allOf` array. What issues do you get generating the API?

**Comment by flo-ryan** [comment]
@MikeEdgar alright, thanks for the clarification!

I'm using the following maven plugin:
```
<groupId>io.swagger.codegen.v3 </groupId>
<artifactId>swagger-codegen-maven-plugin</artifactId>
<version>3.0.22</version>
```
Depending on which "version" of the annotation parameters I use, I get one of the two following outputs:
```
// for type = SchemaType.OBJECT
export interface Book { 
    genre?: Genre & any;
...
```
```
// for type = SchemaType.STRING or type = SchemaType.DEFAULT
import { ModelObject } from './modelObject';
export interface Book { 
    genre?: Genre & ModelObject;
...
```
The problem with the first is the loss of type safety and the second adds a "fake object" `ModelObject` which does not exist (there are some GitHub issues regarding this, but apparently the problem is not fixed yet).

**Comment by flo-ryan** [comment]
@MikeEdgar unfortunately I'm no Typescript expert, but I was told that the `& any` is problematic when it comes to type-safety.
Since I have a lot Book/Movie-Genre constellations in my project, the overhead to create a specific type for each combinations is probably too high.
So I guess I'll either have to go without description/example or somehow deal with the type composition of my generated Typescript API.
