### ISSUE TITLE
Include schema for additional Java class in generated OpenAPI file

### ISSUE THREAD

**Issue by flo-ryan** [smallrye/smallrye-open-api#554]
I'm using the `smallrye-open-api-maven-plugin` to generate the OpenAPI json/yaml from a Java application which uses the `org.eclipse.microprofile.openapi.annotations`.
I have a few classes which are not exposed over the REST API (not "in a typed way" at least), but I would like to include them in the generated OpenAPI schema file. Simply adding an annotation like `@Schema` to the class does not seem to work.

Is there a way to include additional Java classes when generating the schema file using the maven plugin?

Is it maybe possible to use a custom implementation of `OASModelReader` or similar, which somehow uses the smallrye implementation and then adds a few classes/types?
However, my first simple attempt resulted in a ClassNotFoundException when defining `mp.openapi.model.reader` (or `modelReader`).

Thanks a lot in advance!

**Comment by phillip-kruger** [comment]
Hi @flo-ryan - The maven plugin might need a update for this. Do you have a small project that reproduce the issue ?

**Comment by flo-ryan** [comment]
Hi @phillip-kruger, you mean it might need an update to include classes that are not exposed via the API? Or are you referring to the ClassNotFoundException (I'm assuming not)?
I do not have a small reproducer at the moment, since it's part of a bigger application - I just have some "separate" classes which are not added to the generated schema file, despite their `@Schema annotation`. Right now it seems that only classes, that are somehow exposed via the REST API (directly or contained in another class, which is exposed directly), are included in the schema.
But if necessary or helpful, I can definitely try to create a small (Quarkus) project as reproducer.

**Comment by phillip-kruger** [comment]
Hi @flo-ryan - you should be able to do this with the filter, that is the recommended way, but it might mean that the maven plugin is not picking up the filter, so that is what we need to check. So if you can create a small reproducer that would speed up a fix ! Thanks

**Comment by flo-ryan** [comment]
@phillip-kruger sorry, I'm not sure I fully understand what you mean.
Do you mean a custom filter (`OASFilter` implementation) should/could be used for this?

I haven't used a (custom) filter yet, but to my understanding it can be used to filter/exclude elements from the generated schema, depending on which method is overriden. Is this correct?
That would mean that this filter is applied to the model, that is created by the `OASModelReader` or its custom implementation, correct?
So for my use case, the model reader would have be able to read ALL elements for the OpenAPI schema (Java classes etc) that I potentially want to include in the generated schema file (which does not work yet), and then as 2nd step, one could use the filter to exclude some unwanted elements. Are there assumptions correct?

I just tried to add a custom filter implementation using `mp.openapi.filter`, however just like with the custom model reader I also get a ClassNotFoundException when executing the plugin:

```
Execution default of goal io.smallrye:smallrye-open-api-maven-plugin:2.0.14:generate-schema failed: java.lang.ClassNotFoundException: com.test.MyModelReader -> [Help 1]
```

So if my understanding and my assumptions are correct, you'd want a project to reproduce:
- a Java class (with `@Schema` annotation), which is NOT included in the generated schema (but should/could be)
- a custom model reader
- a custom model filter

Is that correct?

**Comment by phillip-kruger** [comment]
Hi @flo-ryan - I managed to recreate the issue with using a filter with the maven plug in, I'll look to fix that a.s.a.p.

But that might not what you want. Your classes are never scanned (as they are not used in an endpoint). So if we fix the above issue, you will have to scan this manually, or create the schema objects manually. That might not be what you want.

Else we can discuss if we should include Schema objects that is not part of the OpenAPI model if the java class is annotated with `@Schema`. Or maybe we need a new annotation to force inclusion. @MikeEdgar - any ideas ?

What you can do in the mean time is to create a application.yml with your objects in, and include that in the classpath, that should be merged with the generated model. see https://download.eclipse.org/microprofile/microprofile-open-api-1.0/microprofile-openapi-spec.html#_static_openapi_files

**Comment by MikeEdgar** [comment]
Listing them in `@OpenAPIDefinition.components()` should at least making them available in `#/components/schemas` for a filter to reference them. That might be the quickest work-around. Scanning all classes with `@Schema` may not be a bad idea. Classes with that annotation typically end up in `#/components/schemas` anyway, so it may not be too different for most users and would end up supporting situations like this.

**Comment by MikeEdgar** [comment]
There is also the `mp.openapi.schema.*` property (from MP OAI 2.0 that is supported even in the current releases) for defining schemas under `#/components/schemas`.

**Comment by phillip-kruger** [comment]
@flo-ryan @MikeEdgar - I created a fix for the maven plugin classloader problem, however, we can still discuss scanning all `@Schema` annotations, event if it's not visible on the endpoint.

**Comment by flo-ryan** [comment]
@MikeEdgar I feel the `mp.openapi.schema` property is only a good fit, when a single schema (or so) needs be added. Also I just tried that by adding it to the `application.properties` of my Quarkus project, but couldn't see any additional schemas in the generated OpenAPI file (with v2.0.14 of the maven plugin).

@phillip-kruger thanks a lot for the fast PR! Does that also fix the `ClassNotFoundException` when using a custom model reader?

Re: scanning all `@Schema` annotations
This definitely is a use-case for me and would be a great functionality to have. 
For a quick fix I created a fake REST endpoint and added all needed classes in the allOf class-array of the response's schema. Obviously this is only a hacky and ugly fix for now.

**Comment by MikeEdgar** [comment]
@flo-ryan , did you also try the OpenAPIDefinition annotation? That would allow you to specify the schemas globally and is essentially the same thing that scanning all Schemas will achieve, albeit with more code. Interesting the property does not work in the Maven plugin. How did you use it?

**Comment by flo-ryan** [comment]
@MikeEdgar yes, sorry - forgot to mention that I also tried this, however the class/schema is not included in the generated `openapi.json` file (the content of `@Info` however is used to set the title etc.):
```
@OpenAPIDefinition(
        info = @Info(
                [...]
        ),
        components = @Components(schemas = {
                @Schema(implementation = MyClass.class)
        })
)
```
Is this the way you it could/should work?

---
For the Maven plugin, I referenced the Quarkus properties and added the schema there, using an example I found:
```
<configProperties>${basedir}/src/main/resources/application.properties</configProperties>
```
```
mp.openapi.schema.java.time.LocalDate = { \
  "name": "EpochMillis" \
  "type": "number", \
  "format": "int64", \
  "description": "Milliseconds since January 1, 1970, 00:00:00 GMT" \
}
```

**Comment by phillip-kruger** [comment]
@flo-ryan yes I believe so, the class path in the maven plugin is fix everywhere.

How about we add scanning all `@schema` with the option to disable that via config ?

**Comment by MikeEdgar** [comment]
@flo-ryan , yes that annotation looks correct. Did you place it on an Application class or package-info?

**Comment by flo-ryan** [comment]
@phillip-kruger Scanning all `@Schema` annotated classes not only would be great for the needs in my project, I'm also assuming that it could benefit others. 
And I think it could also make sense to be able to disable (or enable?) this via config. Although that could also be done by excluding unwanted classes/schemas using a filter, I guess.

@MikeEdgar Thanks for verifying - I put the annotation on the Application class.
