### ISSUE TITLE
maven-plugin mp.openapi.filter ClassNotFoundException

### ISSUE THREAD

**Issue by OliverSanftleben** [smallrye/smallrye-open-api#564]
Hello,

filter class will not be found, when generating OpenAPI with the Maven plugin.

But the filter is found and works (with mp.openapi.filter in application.properties) if I'm starting the application with quarkus.

My pom looks like this:
```
<plugin>
	<artifactId>smallrye-open-api-maven-plugin</artifactId>
	<groupId>io.smallrye</groupId>
	<configuration>
		<configProperties>${basedir}/src/main/resources/application.properties</configProperties>
		<filter>my.OASFilterImpl</filter>
	</configuration>
	<executions>
		<execution>
			<id>stage</id>
			<configuration>
			...
			</configuration>
			<goals>
				<goal>generate-schema</goal>
			</goals>
		</execution>
		<execution>
			<id>prod</id>
			<configuration>
			...
			</configuration>
			<goals>
				<goal>generate-schema</goal>
			</goals>
		</execution>
	</executions>
</plugin>
```

output with mvn clean test-compile:

[ERROR] Failed to execute goal io.smallrye:smallrye-open-api-maven-plugin:2.0.8:generate-schema (stage) on project foo: Execution stage of goal io.smallrye:smallrye-open-api-maven-plugin:2.0.8:generate-schema failed: java.lang.ClassNotFoundException: my.OASFilterImpl -> [Help 1]

But my.OASFilterImpl is compiled and in /target/classes folder

**Comment by phillip-kruger** [comment]
I think this is fixed in https://github.com/smallrye/smallrye-open-api/pull/556
It should be available in the next version

Can you confirm ?

**Comment by phillip-kruger** [comment]
Closing (no feedback) - please reopen if this is still an issue.
