### ISSUE TITLE
Run junit TCK tests on non-8080 port

### ISSUE THREAD

**Issue by EricWittmann** [smallrye/smallrye-open-api#57]
The tests start up a server on port 8080.  Instead, it should start the server on a random port and then use that.  Otherwise it's very possible to collide with something else running on the machine.

**Comment by EricWittmann** [comment]
Yeah that could work.  Thanks for the tip.

**Comment by msavy** [comment]
Okay, took a little longer than expected, but got it done. Turns out that there's a way to globally set the port in the client :-).

See #57
