### ISSUE TITLE
Support RESTEasy Reactive extensions

### ISSUE THREAD

**Issue by FroMage** [smallrye/smallrye-open-api#576]
We currently have extensions that SR-OpenApi needs to be aware of:

- `@RestPath`, `@RestQuery` and friends, which have their value name optional, like the `@PathParam` and friends in RESTEasy, but we renamed them because most users were super confused with them having the same name
- default produces/consumes rules (not yet finalised)
- `@PathParam` is optional and inferred if there's an existing path param declared with the same parameter name
- `@Context` is optional and inferred if there's an existing context type known at build time
- We're thinking of doing the same for CDI beans (not yet finalised)
- We're investigating a genericised `Response` which would allow you to know the return type even when returning a response (not yet finalised).

Did I forget anything @geoand ?

**Comment by FroMage** [comment]
To be clear, it's not yet the right time to start working on this because we're still finalising stuff, but we'll let you know :)

**Comment by geoand** [comment]
In the second point, I think you mean `@RestPath` instead of `@PathParam` :)

**Comment by MikeEdgar** [comment]
@FroMage, @geoand - is the extension still targeting 1.11? I'm curious on the timeline for this request.

**Comment by geoand** [comment]
We have included RESTEasy Reactive in Quarkus 1.11, so as soon as we can have OpenAPI fully support it, the better 🙂

**Comment by MikeEdgar** [comment]
@geoand - just to clarify, these are the new annotations that should be supported, with `RestPath` being optional when the resource method has an argument named the same as a path parameter variable in the template.

- `org.jboss.resteasy.reactive.RestCookie`
- `org.jboss.resteasy.reactive.RestForm`
- `org.jboss.resteasy.reactive.RestHeader`
- `org.jboss.resteasy.reactive.RestMatrix`
- `org.jboss.resteasy.reactive.RestPath`
- `org.jboss.resteasy.reactive.RestQuery`

Anything else? Did you define a generic version of `Response` also?

**Comment by geoand** [comment]
@MikeEdgar yes, that is correct. 

We don't have a generic version of `Response` (yet)
