### ISSUE TITLE
JAX-RS multipart form data

### ISSUE THREAD

**Issue by KivApple** [smallrye/smallrye-open-api#599]
Let's define POJO for multipart form:

    public class FormDTO {
    	@FormParam("file")
    	@PartType(MediaType.APPLICATION_OCTET_STREAM)
    	private InputStream file;
    	
    	...
    }

Then define a multipart endpoint:

    @POST
    @Path("/upload")
    @Consumes("multipart/form-data")
    public String updateFromFile(@MultipartForm FormDTO form) {
        ...
    }

Now we have such generated OpenAPI specification for this endpoint:

    ...
    paths:
      /upload:
        post:
          requestBody:
            content:
              multipart/form-data:
                schema:
                  type: object
                  properties:
                    file:
                      $ref: '#/components/schemas/InputStream'
    components:
      schemas:
        InputStream:
          type: object

Actually we need something like this instead of referencing `InputStream`:

    file:
      type: string
      format: binary

Changing `InputStream` to `byte[]` (other possible POJO field type to accept a file in JAX-RS) does not help (we got an array of numbers instead of binary string in our OpenAPI specification).
More information: https://swagger.io/docs/specification/describing-request-body/file-upload/

Tested with Quarkus and Resteasy.

**Comment by MikeEdgar** [comment]
@KivApple - I've faced this myself in projects, but have yet to address it in the library. You can try to provide an implementation of the `OASFilter` interface (which must be registered via the `mp.openapi.filter` config property). Implement the `filterOpenAPI` method and try something like this:

```java
public class OASModelFilter implements OASFilter {

    @Override
    public void filterOpenAPI(OpenAPI openAPI) {
        setSchemaFileProperty(openAPI.getPaths().getPathItem("/upload").getPOST());

        Map<String, Schema> schemas = openAPI.getComponents().getSchemas();
        openAPI.getComponents().removeSchema("InputStream");
    }

    void setSchemaFileProperty(Operation operation) {
        operation.getRequestBody()
                 .getContent()
                 .getMediaType(MediaType.MULTIPART_FORM_DATA)
                 .getSchema()
                 .addProperty("file",
                              OASFactory.createSchema()
                                        .type(SchemaType.STRING)
                                        .format("binary"));
    }
}
```

**Comment by KivApple** [comment]
I have implemented more generic solution for my project which automatically replaces three variants of file field (`byte[]`, `InputStream` and `InputPart`):
```
public class OpenAPIConfig implements OASFilter {
	@Override
	public void filterOpenAPI(OpenAPI openAPI) {
		openAPI.getComponents().removeSchema("InputStream");
		openAPI.getComponents().removeSchema("InputPart");
	}
	
	@Override
	public RequestBody filterRequestBody(RequestBody requestBody) {
		Optional.ofNullable(requestBody.getContent())
				.map(content -> content.getMediaType(MediaType.MULTIPART_FORM_DATA))
				.map(org.eclipse.microprofile.openapi.models.media.MediaType::getSchema)
				.filter(schema -> schema.getProperties() != null)
				.ifPresent(schema -> schema.setProperties(
						schema.getProperties().entrySet().stream()
								.map(entry -> {
									boolean isBinary = false;
									if (entry.getValue().getRef() != null) {
										switch (entry.getValue().getRef()) {
											case "#/components/schemas/InputStream":
											case "#/components/schemas/InputPart":
												isBinary = true;
												break;
										}
									} else if (entry.getValue().getType() == Schema.SchemaType.ARRAY) {
										if (entry.getValue().getItems().getType() == Schema.SchemaType.STRING) {
											if ("byte".equals(entry.getValue().getItems().getFormat())) {
												isBinary = true;
											}
										}
									}
									if (isBinary) {
										return new AbstractMap.SimpleImmutableEntry<>(
												entry.getKey(),
												OASFactory.createSchema()
														.type(Schema.SchemaType.STRING)
														.format("binary")
										);
									}
									return entry;
								})
								.collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue))
				));
		return requestBody;
	}
}
```
I hope this issue will be resolved in future and we won't be need such dirty hacks anymore. Thank you very much for pointing me in direction of usage of `OASFilter`.
