### ISSUE TITLE
2.1.0-RC1: NullPointerException on PathItem#setOperation(HttpMethod, Operation)

### ISSUE THREAD

**Issue by jmini** [smallrye/smallrye-open-api#620]
`PathItem#setOperation(HttpMethod, Operation)` was introduced with https://github.com/eclipse/microprofile-open-api/issues/432

---

I don't think that the TCK contains anything for this case:

```java
PathItem pathItem = OASFactory.createPathItem();
Operation operation = OASFactory.createOperation().description("This is some op");

pathItem.setOperation(null, operation);
```

Is it expected that in smallrye a `NullPointerException` is thrown when the `HttpMethod` parameter is `null`?

**Comment by MikeEdgar** [comment]
Hi @jmini - from a user/developer perspective, would you expect that passing `null` result in a no-op situation? I'm curious what the case for passing `null` may be.

**Comment by jmini** [comment]
In my implementation I am throwing an `IllegalParameterException`.

I agree with you `null` is not a valid value for this parameter in this method.

---

I just discovered the `NullPointerException` when I updated to MP-OpenAPI `2.0` in an other project where I use smallrye to compare behavior between implementations (see https://github.com/OpenAPITools/empoa/commit/c5c6ebd93b8e24f03c7bf1b5dfba107acfa4c37b)

**Comment by MikeEdgar** [comment]
This might be something to add to the method's JavaDoc in the MP OpenAPI spec project. I personally lean more toward the NPE (with a helpful message) since it's a bit more specific, but either exception would be fine.

**Comment by phillip-kruger** [comment]
I think a NPE is fine here ? But a IllegalArgumentException should also be fine. I think we can close this issue ?

**Comment by MikeEdgar** [comment]
Fine with me - @jmini your thoughts? Do you think this merits opening an issue in the spec project to update the JavaDoc to specify the exception thrown in this case?

**Comment by MikeEdgar** [comment]
Closing - this discussion can be picked up in the MP OpenAPI project if necessary.
