### ISSUE TITLE
Add support for multiple applications

### ISSUE THREAD

**Issue by Thihup** [smallrye/smallrye-open-api#645]
Does this implementation support multiple applications?
The spec doesn't require it, so I don't know if this is work for the runtime container or if this implementation should implement something to allow multiple applications.

> Multiple applications
The 1.0 version of the MicroProfile OpenAPI specification does not define how the /openapi endpoint may be partitioned in the event that the MicroProfile runtime supports deployment of multiple applications. If an implementation wishes to support multiple applications within a MicroProfile runtime, the semantics of the /openapi endpoint are expected to be the logical union of all the applications in the runtime, which would imply merging multiple OpenAPI documents into a single valid document (handling conflicting IDs and unique names).

**Comment by MikeEdgar** [comment]
Hi @Thihup - multiple deployments are not supported by the scanner and would be a concern of the runtime container, as you said.

**Comment by phillip-kruger** [comment]
Closing here. @Thihup - check with the runtime (Wildfy / OpenLiberty / Quarkus)
