### ISSUE TITLE
@Parameter ignored on parameter if @PathParam also present

### ISSUE THREAD

**Issue by tjquinno** [smallrye/smallrye-open-api#646]
(transcribed with some editing from a Google Groups discussion https://groups.google.com/g/smallrye/c/xvhDsfsE6F4)

OpenAPI seems to ignore a `@Parameter` annotation on a parameter if there is also a `@PathParam` annotation.

Here's an example:

https://github.com/tjquinno/helidon/blob/0be4b63cfaadd04ac55cb4ba716716117b396d09/examples/microprofile/openapi-basic/src/main/java/io/helidon/microprofile/examples/openapi/basic/GreetResource.java#L114-L117

```java
    public JsonObject getMessage(
            @Parameter(description = "This is ignored")
            @PathParam("name") String name) {
```
I've seen this in 2.0.17 and earlier releases.

Here's what I saw stepping through the code in my case.

The code happens to process the `@PathParam` first (not that it should matter), then the argument-level `@Parameter` annotation.

When the code processes `@Parameter`, `ParameterProcessor#getParameterContext` tries to find the pre-existing context for the parameter. There seems to be one — with key `name: name, in: path` but the key passed to `getParameterContext` associated with the `@Parameter` annotation is `name: name, in: null`. I'm not sure if that's OK or not, but in any event the code does not find the pre-existing context using any of the three attempts:

- in the map directly (this seems expected),
- using `haveSameAnnotatedTarget` in 1205:1211 (to me, this is a surprise), or
- the "last chance" check at the end of the method.

I'm guessing that maybe the intent was that `haveSameAnnotatedTarget` would return `true` for this case, given that the pre-existing context entry created from the `@PathParam` and the context being created for the parameter-level `@Parameter` annotation should reflect the same target.

I did not see that `MethodParameterInfo` implements `equals`, so it would inherit the implementation from `Object` which does a simple `==` comparison of the two object references. And, indeed, the code is comparing two different instances of `MethodParameterInfo` although they look to me to be referring to the same target. 

If `haveSameAnnotatedTarget` returned `true` here, then I think the rest of the code would combine the information from the two annotations which, from the outside anyway, would seem to make sense. As it is, I see two contexts in the processor's `params` collection where I'd expect to see a single, combined context for the parameter.

But maybe there's more to it that I'm missing.

Mike reported seeing the expected results, not mine, when he tried the same example. I can't explain why we are getting different results unless perhaps the order in which the `@PathParam` and `@Parameter` annotations are dealt with does matter and for some reason our test runs process them in different orders.

Perhaps if `MethodParameterInfo` overrode `equals` the order wouldn't matter (if in fact that's the problem). Maybe it should implement `equals` anyway? I realize that class is not in SmallRye OpenAPI's code base.

If there's anything else I can try from here, please let me know. For the moment I'm not sure what I might be doing to cause the problem.

**Comment by MikeEdgar** [comment]
@tjquinno Hi Tim - I'm curious if when the scanner is processing these classes, is it using a pre-generated Jandex index (from file) or the one created from the application at startup? It is surprising that you see different instances of `MethodParameterInfo` on the same method, so I'd like to get a better understand of how you're building the indexes.

**Comment by tjquinno** [comment]
@MikeEdgar Hi, Mike.

We use the Jandex Maven plug-in default settings (release 2.1.1.Final via plug-in management). 

https://github.com/tjquinno/helidon/blob/0be4b63cfaadd04ac55cb4ba716716117b396d09/examples/microprofile/openapi-basic/pom.xml#L81-L89

```xml
            <plugin>
                <groupId>org.jboss.jandex</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>make-index</id>
                    </execution>
                </executions>
            </plugin>
```

I've attached a zip of the `jandex.idx` file in case that helps.

[jandex.zip](https://github.com/smallrye/smallrye-open-api/files/5887369/jandex.zip)

**Comment by MikeEdgar** [comment]
@tjquinno Tim, when I step through in debug mode, I see that the Jandex index loaded from the plugin does not contain the `@Parameter` annotation on the `name` method parameter. Depending on where it is being dropped, this looks like a bug in either Jandex or the Jandex plugin.

**Comment by tjquinno** [comment]
Thanks for the follow-up, @MikeEdgar 

Weird. I don't see problems in the Jandex index. 

I've attached the index dump without and with the added `@Parameter` parameter-level annotation. Here's the diff:

```
diff withoutAddedParameter.txt withAddedParameter.txt
37a38,40
> org.eclipse.microprofile.openapi.annotations.parameters.Parameter:
>     Parameter: javax.json.JsonObject getMessage(java.lang.String name) #0
>         (description = "This is ignored")
60c63
< Read jandex.idx in 0.0210 seconds
---
> Read jandex.idx in 0.0280 seconds
```

I haven't read the Jandex dumps much so maybe I'm missing something, but what I'm seeing from them lines up with my experience stepping through with the debugger. 

[withoutAddedParameter.txt](https://github.com/smallrye/smallrye-open-api/files/5904446/withoutAddedParameter.txt)
[withAddedParameter.txt](https://github.com/smallrye/smallrye-open-api/files/5904475/withAddedParameter.txt)

**Comment by MikeEdgar** [comment]
@tjquinno , can you confirm that the index you attached earlier did contain the annotation when you run dump? Also, which version of Jandex did you use for the dump?

**Comment by tjquinno** [comment]
Confirming.

Here's the command I used (with redirection to a different file in each case):

`java -jar ~/.m2/repository/org/jboss/jandex/2.1.2.Final/jandex-2.1.2.Final.jar -d target/classes/META-INF/jandex.idx > withAddedParameter.txt`

Here are the index files:
[indexes.zip](https://github.com/smallrye/smallrye-open-api/files/5904542/indexes.zip)

**Comment by MikeEdgar** [comment]
@tjquinno - I haven't had a chance to get back to this, but it appears at first glance that the first index attached was the one without the annotation. I'll take a look at testing with the other index as soon as I get a chance.

**Comment by tjquinno** [comment]
@MikeEdgar Hmm. I just downloaded my own attachment, unzipped it, and `diff`ed the dumps of the `.idx` files. The `jandexWithParam.idx` file is larger, and the `@Parameter` annotation I added during the experiment seems to appear in it:

```
unzip -l ~/Downloads/indexes.zip
Archive: xxx/Downloads/indexes.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     2105  02-01-2021 08:37   jandexWithParam.idx
     2065  02-01-2021 08:38   jandexWithoutParam.idx
---------                     -------
     4170                     2 files

diff <(java -jar ~/.m2/repository/org/jboss/jandex/2.1.2.Final/jandex-2.1.2.Final.jar -d ~/Downloads/indexes/jandexWithoutParam.idx) \
<(java -jar ~/.m2/repository/org/jboss/jandex/2.1.2.Final/jandex-2.1.2.Final.jar -d ~/Downloads/indexes/jandexWithParam.idx)
37a38,40
> org.eclipse.microprofile.openapi.annotations.parameters.Parameter:
>     Parameter: javax.json.JsonObject getMessage(java.lang.String name) #0
>         (description = "This is ignored")
60c63
< Read jandexWithoutParam.idx in 0.0330 seconds
---
> Read jandexWithParam.idx in 0.0270 seconds
```
Anyway, I do not see the Jandex plug-in or anything else in the tool chain skipping the parameter-level `@Parameter` annotation. 

Let me know if there's anything else I can do from here.

**Comment by MikeEdgar** [comment]
@tjquinno - it looks like the original attachment zip (from the 1/28 comment) contained the index without the parameter annotation. I've successfully been able to reproduce the issue now using the "jandexWithParam" index. As you suggested earlier, this will take a change to compare the two objects more deeply than just using `equals`.
