### ISSUE TITLE
Is there any way override the conversion of Java object (JAXBElement) to JSON?

### ISSUE THREAD

**Issue by Denkalenkachenka** [smallrye/smallrye-open-api#650]
I wonder if there is any way I could take control over the conversion of the Java Object (JAXBElement) to JSON? The problem is that when openapi generates document, the JSON gets the wrong format. It looks like this in swagger-ui.

![bild](https://user-images.githubusercontent.com/78076219/106744722-6a19e280-6620-11eb-8284-1d212e134c38.png)

It shouldn't include the "namespaceURI", "prefix" and so on.

I have generated the classes from a WSDL-file and I need to marshall the objects like this:
![bild](https://user-images.githubusercontent.com/78076219/106746425-d39af080-6622-11eb-8d92-ccaeea2c6bf9.png)

- Is there any way I can achieve this so the JSON gets the correct format in swagger-ui? 
- Is it possible to override the method that openapi uses to marshall Object to JSON? 
- Which method in which interface is this?

**Comment by phillip-kruger** [comment]
Hi. Can you share the code for `RegisterDocumentCaseSvcDto` ?

**Comment by Denkalenkachenka** [comment]
Here comes the structure of `RegisterDocumentCaseSvcDto`

```
package v1.datacontracts.miljo.api.milo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegisterDocumentCaseSvcDto", propOrder = {
    "caseSubtitle",
    "caseSubtitleFree",
})
public class RegisterDocumentCaseSvcDto {

    @XmlElementRef(name = "CaseSubtitle", namespace = "urn:Milo.API.Miljo.DataContracts.V1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> caseSubtitle;
    @XmlElementRef(name = "CaseSubtitleFree", namespace = "urn:Milo.API.Miljo.DataContracts.V1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> caseSubtitleFree;

    /**
     * Gets the value of the caseSubtitle property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCaseSubtitle() {
        return caseSubtitle;
    }

    /**
     * Sets the value of the caseSubtitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCaseSubtitle(JAXBElement<String> value) {
        this.caseSubtitle = value;
    }

    /**
     * Gets the value of the caseSubtitleFree property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCaseSubtitleFree() {
        return caseSubtitleFree;
    }

    /**
     * Sets the value of the caseSubtitleFree property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCaseSubtitleFree(JAXBElement<String> value) {
        this.caseSubtitleFree = value;
    }
```

**Comment by MikeEdgar** [comment]
If you can change the source code for the DTO, try adding `@Schema(implementation = String.class)` to each of the fields.

If you can't change the source or don't want to because it's generated, there may be another option.

**Comment by Denkalenkachenka** [comment]
@MikeEdgar Thank you for you answer. Yes, you are correct. I would rather not change the generated classes. But thanks for the tip!

Do you know which method is used to generate the schema from the Java object? Maybe it is possible to override that method?

**Comment by Denkalenkachenka** [comment]
The reason I dont want to change the generated classes is because I got hundreds of generated classes and some fields are the type of another class that are the type of another class and so on... 

Example: 
`protected JAXBElement<ArrayOfRegisterDocumentPartyRoleDto> partyRoles;`

**Comment by MikeEdgar** [comment]
@Denkalenkachenka - try this.

Add to your application's properties, then add `@Schema(ref = "RegisterDocumentCaseSvcDto")` to the `createCase` method parameter. The idea is that you can specify a schema in JSON in your config, then reference it to override the generated schema.
```
mp.openapi.schema.v1.datacontracts.miljo.api.milo.RegisterDocumentCaseSvcDto={ \
  "name": "RegisterDocumentCaseSvcDto" \
  "type": "object" \
  "properties": { \
    "caseSubtitle": { "type": "string" }, \
    "caseSubtitle": { "caseSubtitleFree": "string" }, \
  } \
}
```
I know since you probably have many of them it's not ideal. Do you require the use of `JAXBElement`s? I know sometimes the JAXB generator can be adjusted to avoid them, but other times they are necessary based on the XSD.

**Comment by Denkalenkachenka** [comment]
@MikeEdgar 
Thank you for trying to help me. That idea was interesting. That means that you can get full control over what is generated in the OpenAPI-contract. That is very good to know.

But yes it's not ideal. It will be alot of manual work and as developers we hate that, right? :smile: 

Yes unfortunately I don't have access to the source code of the code that generates the WSDL-file. It's a third party product...

Maybe I can make some script that changes the WSDL-file before I use it to generate the classes. I dont know..

**Comment by MikeEdgar** [comment]
It seems like perhaps `JAXBElement` should be handled similar to `Optional`. What do you think @phillip-kruger ? I.e., use the generic type instead.

**Comment by phillip-kruger** [comment]
That can work. I think.

**Comment by MikeEdgar** [comment]
@Denkalenkachenka - with the referenced pull requests, the generic type of `JAXBElement` fields should be used instead. E.g. `String` in your sample DTO.

**Comment by Denkalenkachenka** [comment]
@MikeEdgar @phillip-kruger 
Great job guys! :star:
