### ISSUE TITLE
Implement Swagger UI Authentication configuration in IndexCreator

### ISSUE THREAD

**Issue by Legion2** [smallrye/smallrye-open-api#663]
Currently the implementation of IndexCreator is not complete and contains a TODO:
https://github.com/smallrye/smallrye-open-api/blob/965315eec6b54b15f085b36b36443413f910f478/ui/open-api-ui/src/main/java/io/smallrye/openapi/ui/IndexCreator.java#L213-L216

This functionality is required to configure OAuth 2.0 parameters which cannot be specified in the OpenAPI specification, such as `usePkceWithAuthorizationCodeGrant` and `additionalQueryStringParams`, see https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md. These configuration options are not part of the normal swagger ui config and must be configured using instance methods such as `ui.initOAuth`.
The implementation of this feature is required for quarkusio/quarkus#13845

**Comment by phillip-kruger** [comment]
Nice ! I forgot that todo was there. Let me have a look
