### ISSUE TITLE
Support for naming schemas (camelCase / sname_case) for properties

### ISSUE THREAD

**Issue by lenalebt** [smallrye/smallrye-open-api#712]
Hi,
I'm currently looking for support to globally change the naming strategy used.

All my classes use standard Kotlin camelCase notations, but the API itself should always be exported as snake_case. I configured Jackson globally, like so:

```
ObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE)
```

and I also tried adding an `@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy::class)` to all the data classes. Works like a charm for serialization/deserialization (either way). However, the exported OpenAPI definitions do not obey the settings (totally get it for the first via ObjectMapper one). I could in theory go with explicit naming via `@JsonProperty`, but given that this is a global setting everywhere else makes it a bit tedious.

Did you already have something like this in mind? I'd also be fine with adding some kind of configuration flag somewhere to make it possible.

**Comment by phillip-kruger** [comment]
@MikeEdgar w.d.y.t ?

**Comment by MikeEdgar** [comment]
@phillip-kruger - I think this is something that could be supported (along with Jsonb's naming strategies). It would be nice if somehow the scanner could just instantiate the naming strategy and call its formatting method rather than putting all that logic in SmallRye itself.

**Comment by gwenneg** [comment]
This would be a great addition, I'm looking forward to this!

**Comment by lenalebt** [comment]
Thank you very much for implemeting this, highly appreciated :)!

**Comment by MikeEdgar** [comment]
> Thank you very much for implementing this, highly appreciated :)!

Glad to add it :) It  may be a little while before it's available. @phillip-kruger , w.d.y.t - do we backport to `2.0.x` and release?

**Comment by phillip-kruger** [comment]
I don't think that would make if available any quicker. We should be able to get this into Quarkus 2
