### ISSUE TITLE
Openapi document is missing some schemas with unused generic type parameters

### ISSUE THREAD

**Issue by Legion2** [smallrye/smallrye-open-api#715]
I have the following class with a generic parameter which is not used inside the class (kotlin code):
```kotlin
data class TypeReference<T>(val namespace: String, val name: String)
```
The generic parameter is only used at compile time to check that the class is only used in the correct context.

The class is exposed in the REST API multiple times with different generic type parameters. But in the generated openapi document the schemas for the class are missing and result in an error when loading it in swagger ui:
`Could not resolve reference: Could not resolve pointer: /components/schemas/TypeReferenceFoo does not exist in document`.

I'm using quarkus 1.12.0.Final.

**Comment by MikeEdgar** [comment]
Hi @Legion2 - the fix for this would have been included in 1.11.4. I expect it will be in the next 1.12.x when released. Please give it a try with 1.11.4 and let us know if you still see the issue. Thanks

**Comment by MikeEdgar** [comment]
Looks to be the same as #688

**Comment by Legion2** [comment]
#688 is already in quarkus 1.12.0.Final and it fixed many of the missing schemas in my openapi document, but this one class is still missing its schema.

**Comment by MikeEdgar** [comment]
Hi @Legion2 - got it, you're right. Can you provide a reproducer including how the class is referenced from the REST endpoint method?

**Comment by Legion2** [comment]
@MikeEdgar Ok I now have a reproducer, it is not the problem that the generic type is not used. The problem is that when two generic types are nested, the inner is not resolved.
```kotlin
@Path("/api/test")
class Test {

    @GET
    @Path("foo")
    fun getFoo(): Foo {
        return Foo(Generic2(Generic1("test")))
    }
}

data class Generic1<T>(val value: T)

data class Generic2<T>(val nested: Generic1<T>)

data class Foo(val generic: Generic2<String>)
```
`Could not resolve reference: Could not resolve pointer: /components/schemas/Generic1String does not exist in document`

**Comment by MikeEdgar** [comment]
Thanks @Legion2 - I was able to reproduce the issue. I assume your output contains a `Generic1Object` schema in the `compoenents/schemas` sections, correct? I'll look into getting this fixed for the next release.

**Comment by Legion2** [comment]
> I assume your output contains a Generic1Object schema in the compoenents/schemas sections, correct?

@MikeEdgar yes

```yaml
    Generic2String:
      type: object
      properties:
        nested:
          $ref: '#/components/schemas/Generic1String'
    Generic1Object:
      type: object
      properties:
        value:
          type: object
    Foo:
      type: object
      properties:
        generic:
          $ref: '#/components/schemas/Generic2String'
```
