### ISSUE TITLE
Add schema reference of nested objects

### ISSUE THREAD

**Issue by opeti** [smallrye/smallrye-open-api#73]
Currently only top level classes are added to schemas section of the document and only these schemas are referenced. However if there is a nested class, it is always flattened out instead of creating a schema and referencing it.

For example I have the following 2 classes and a JAX-RS resource:
```
public class Foo {
	private String name;
	private Bar bar;

	//... getters/setters
}
```
```
public class Bar {
	private String note;

	//...getter/setter
}
```
```
@Path("foo")
public class FooResource {
	@GET
	public Foo getFoo() {
		return new Foo();
	}
}
```

Then the generated openapi documentation will look like:
```
paths:
  /foo:
    get:
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Foo'

components:
  schemas:
    Foo:
      properties:
        bar:
          type: object
          properties:
            note:
              type: string
        name:
          type: string
```

If class Bar is used many times, it is always flattened out everywhere instead of creating a schema for it and referencing it. So the desired format would be:
```
paths:
  /foo:
    get:
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Foo'

components:
  schemas:
    Foo:
      properties:
        bar:
          $ref: '#/components/schemas/Bar'
        name:
          type: string
    Bar:
      properties:
        note:
          type: string
```
I haven't found a way in the actual implementation to force out the Bar schema creation and referencing it where it is used.

**Comment by MikeEdgar** [comment]
Fixed by #97, using the extension property `mp.openapi.extensions.schema-references.enable`.
