### ISSUE TITLE
Introduce a simpler version of ApiResponse annotation

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-open-api#76]
OpenApi has an [ApiResponse annotation](https://github.com/eclipse/microprofile-open-api/blob/master/api/src/main/java/org/eclipse/microprofile/openapi/annotations/responses/APIResponse.java) which, via its nested Content, can provide the information about the JAX-RS Response entity class.

While this annotation covers well for a case where Response dynamically sets different entity types per the current response media type, it is too complex for a typical case of Response returning a known single entity type only, with @Produces already typing a response media type.

One proposal is to have something like this:
```
@Produces("application/json")
@ApiResponseType(MyType.class)
@GET
public Response get() { return Response.ok(new MyType()).build(); }   
```
but other options should also be considered

**Comment by EricWittmann** [comment]
This is an interesting proposal that the specification should consider.  I'll raise it as a discussion point there before we do anything vendor specific.

**Comment by sberyozkin** [comment]
Hi @EricWittmann, thanks

**Comment by MikeEdgar** [comment]
This is pending a spec change [eclipse/microprofile-open-api#363] which is a MP OpenAPI 2.0 candidate.

**Comment by MikeEdgar** [comment]
I'm working on this along with eclipse/microprofile-open-api#363.

**Comment by phillip-kruger** [comment]
Hi @MikeEdgar - I am busy with a (fairly big) code structure change. Would you be able to wait until my change is in ?

**Comment by MikeEdgar** [comment]
@phillip-kruger - yes, no problem at all to wait.

**Comment by phillip-kruger** [comment]
Thanks :)

**Comment by sberyozkin** [comment]
@MikeEdgar thanks
