### ISSUE TITLE
anyOf OpenAPI-generation

### ISSUE THREAD

**Issue by DennisNilssonB3** [smallrye/smallrye-open-api#762]
Is there any way to generate this OpenAPI-specification from the code with @APIResponse?
```
"200":
  description: OK
  content:
    application/json:
      schema:
        type: array
        items:
          anyOf:
          - $ref: '#/components/schemas/LeaseContract'
          - $ref: '#/components/schemas/AnotherContract'
```

I tried this syntax but it doesn't work:
```
@APIResponse(responseCode = "200", description = "OK", 
content = @Content(schema = @Schema(type = SchemaType.ARRAY, anyOf = {LeaseContract.class, AnotherContract.class })))
```
This code results in this OpenAPI (notice that the "items" field is missing):
```
schema:
  type: array
  anyOf:
  - $ref: '#/components/schemas/LeaseContract'
  - $ref: '#/components/schemas/AnotherContract'
```

It seems to be that the property "implementation" (in the code) generates the "items"-object in the OpenAPI-specification. Is it possible to combine "anyOf" with "implementation"?

**Comment by msmiths** [comment]
@DennisNilssonB3 I imagine that you will need to specify values for the `discriminatorProperty` and `discriminatorMapping` attributes of the `@Schema` annotation. You can find an example the MP OpenAPI Pet Store TCK application here:

https://github.com/eclipse/microprofile-open-api/blob/c74248e745e9b8d1e09b5d671c9c4bf1b47778c1/tck/src/main/java/org/eclipse/microprofile/openapi/apps/petstore/resource/PetStoreResource.java#L118-L127

**Comment by MikeEdgar** [comment]
@DennisNilssonB3 , something like the following may work for you. Of course if you already have a natural class to annotate with the `@Schema(anyOf = {...})` that would be a better option.

```java
@Schema(anyOf = { LeaseContract.class, AnotherContract.class })
public class AnyContractSchema {
    // Empty 
}

@APIResponse(
    responseCode = "200",
    description = "OK", 
    content = @Content(
        schema = @Schema(
            type = SchemaType.ARRAY,
            implementation = AnyContractSchema.class)))

```

**Comment by DennisNilssonB3** [comment]
@MikeEdgar , Aha! That makes sense. You just put `@Schema(anyOf = {...})` on the class the two other extends. Very well explained. Thank you!

**Comment by DennisNilssonB3** [comment]
@msmiths , Thank you for the information about discriminator. I will definitly need this information another time.
