### ISSUE TITLE
Add Instant to list of known datetime types.

### ISSUE THREAD

**Issue by damonsutherland** [smallrye/smallrye-open-api#769]
```
    @GET
    @Path("/data/{field}")
    public Object getData(
        @PathParam("field") String sourceField,
        @QueryParam("id") Integer id,
        @QueryParam("account") Integer accountId,
        @QueryParam("date") LocalDate evalDate,
        @QueryParam("asKnownOn") @Schema(implementation = String.class, format = "date-time") Instant asKnownOn
    )
```

In the above example, the Instant argument is represented as an object:

```
{
  "nanos": 0,
  "seconds": 0,
  "epochSecond": 0,
  "nano": 0
}
```

I would expect it to be an example string in the format "yyyy-MM-ddThh:mm:ss.sssZ".

**Comment by MikeEdgar** [comment]
@damonsutherland , wrapping the `@Schema` with `@Parameter(schema = ...)` should give you what you need. It does seem reasonable/natural to expect the annotation to work directly on the method argument, however. Also, we can likely add `Instant` to the list of known types.

**Comment by damonsutherland** [comment]
@MikeEdgar Thanks.  Would you like me to create a feature request for the items you mention, or leave this ticket open?

**Comment by MikeEdgar** [comment]
> @MikeEdgar Thanks. Would you like me to create a feature request for the items you mention, or leave this ticket open?

@damonsutherland - a feature request for `@Schema` support on resource method parameters would be great. The other feature for `Instant` is already implemented by @phillip-kruger :)
