### ISSUE TITLE
Does quarkus openapi support Inheritance and Polymorphism

### ISSUE THREAD

**Issue by hhovhann** [smallrye/smallrye-open-api#776]
Hi Guys, thanks for your hard work.
Have a question about quarkus support for https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/ as well as anyOf, allOf, OneOf in openapi.yml level.
Tried to configure my openapi.yml but gave some issues with that.
I have my DTO's and wanted to use Inheritance and Polymorphism as we have here
In https://editor.swagger.io/ the code works but in quarkus UI I see some strange anyOf and not working properly.
Do you support such stuff?

Some code from openapi.yml here.

```
paths:
  /risk/barrier:
    post:
      tags:
      - Risk Module Endpoints
      summary: Creates a list of barriers
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/ListActivityBarrierDTO'
                - $ref: '#/components/schemas/ListEquipmentBarrierDTO'
......
components:
    BarrierDTO:
      type: object
      required:
        - name
      properties:
        id:
          format: int64
          type: integer
        name:
          maxLength: 255
          pattern: \S
          type: string
          nullable: false
        description:
          maxLength: 255
          type: string
    ActivityBarrierDTO:
      allOf: # Combines the BarrierDTO and the inline model
        - $ref: '#/components/schemas/BarrierDTO'
        - type: object
          required:
            - htt
            - area
          properties:
            htt:
              maxLength: 255
              pattern: \S
              type: string
              nullable: false
            area:
              maxLength: 255
              pattern: \S
              type: string
              nullable: false
    EquipmentBarrierDTO:
      allOf:
        - $ref: '#/components/schemas/BarrierDTO'
        - type: object
          required:
            - tagId
          properties:
            tagId:
              maxLength: 255
              type: string
              nullable: false
    ListActivityBarrierDTO:
      type: array
      items:
        $ref: '#/components/schemas/ActivityBarrierDTO'
    ListEquipmentBarrierDTO:
      type: array
      items:
        $ref: '#/components/schemas/EquipmentBarrierDTO'
```

What I am doing wrong?

**Comment by MikeEdgar** [comment]
Hi @hhovhann - is the YAML you posted a spec that you edited manually, or something generated by the annotation scanner that is not meeting your expectation?

**Comment by hhovhann** [comment]
Hi Mike, thanks for the quick response.
No, I am now using pure openapi.yml and only one Endpoint has @RequestBody because of a similar issue only without List, but again with abstract type and children.
For this endpoint, there is no open API annotation in Api Controller.

**Comment by hhovhann** [comment]
@MikeEdgar also tried with this and commented out in openapi.yml requestBody part for proper endpoint, and with that even not working as with openapi yml case :)
    @RequestBody(content = @Content(schema = @Schema(type = SchemaType.ARRAY, anyOf = {ActivityMessageDTO.class, EquipmentMessageDTO.class} )))

**Comment by MikeEdgar** [comment]
Is the YAML returned by the server (at `/q/openapi`) different from the YAML you provided? It seems as though disabling annotation scanning may be what you need using `mp.openapi.scan.disable=true` in `application.properties`.

**Comment by hhovhann** [comment]
@MikeEdgar `mp.openapi.scan.disable=true` this help and now it shows similar what had in the swagger editor.
So this means that annotation configuration will not have any affection on changes.
About `/q/openapi` -  yes there are differences when that property isn't defined.

Thanks @MikeEdgar for quick help
