### ISSUE TITLE
Open API isn't handling arrays correctly

### ISSUE THREAD

**Issue by felipewind** [smallrye/smallrye-open-api#779]
As @MikeEdgar requested in [this issue on the Quarkus project](https://github.com/quarkusio/quarkus/issues/14814), I openned this issue because I believe that Open API isn't handling arrays correctly.

I've created this project to test this situation - [smallrye-open-api-test](https://github.com/felipewind/smallrye-open-api-test)

My endpoint class:
```java
public class ClientEndpoint {

    @GET
    @Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
    @Operation(summary = "List Clients", description = "List all Clients")
    @APIResponse(responseCode = "200", description = "Clients", content = {
            @Content(mediaType = "application/json", schema = @Schema(implementation = Client[].class)) })
    public Response getClients() {
```

My Client class that is used as the scheme:
```java
import org.eclipse.microprofile.openapi.annotations.media.Schema;
public class Client {

    public Client(String name, Car car, Address... address) {
        this.name = name;        
        this.car = car;
        this.address = address;
    }

    private String name;

    // @Schema(implementation = Address[].class)
    private Address[] address;

    private Car car;
    // ....
    public static class Address {}
    public static class Car {}
    //...
```

Without the `org.eclipse.microprofile.openapi.annotations.media.Schema` annotation above, I receive the following error on the console:
```
$ mvn quarkus:dev
...
2021-04-14 16:47:06,958 WARN  [io.qua.arc.pro.BeanArchives] (build-43) Failed to index [Lorg.acme.model.Client$Address;: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader
....
```

And in the swagger-ui:
![image](https://user-images.githubusercontent.com/47837222/114771355-d3b21d80-9d42-11eb-8238-b37592d976ff.png)
```
Errors
Resolver error at paths./clients.get.responses.200.content.application/json.schema.items.properties.address.items.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/Address does not exist in document
```

If I use the `org.eclipse.microprofile.openapi.annotations.media.Schema` annotation, everything works fine.

Sorry if I did something wrong!

**Comment by MikeEdgar** [comment]
Thanks for reporting this. I'm not sure why you received the ARC error, but the OpenAPI scanner part should be resolved with the linked pull requests :)

**Comment by felipewind** [comment]
> Thanks for reporting this. I'm not sure why you received the ARC error, but the OpenAPI scanner part should be resolved with the linked pull requests :)

Thanks a lot @MikeEdgar :)

Should I close this issue?

**Comment by MikeEdgar** [comment]
> Should I close this issue?

No need, once the PR is reviewed and merged it will close automatically.

**Comment by felipewind** [comment]
> > Should I close this issue?
> 
> No need, once the PR is reviewed and merged it will close automatically.

After this merge, do you know if the next release of Quarkus will have this improvement of the smallrye-openapi?

**Comment by phillip-kruger** [comment]
@felipewind it should be in the next Quarkus
