### ISSUE TITLE
Duplicate objects when using generics

### ISSUE THREAD

**Issue by jonsalvas** [smallrye/smallrye-open-api#803]
quarkus-smallrye-openapi.version: 2.1.4

I have the following dto classes in place:

```
@Schema(allOf = Food.class)
public class DryFood extends Food {

}
```

```
public class Food {

}
```

```
public class Pet<T extends Food> {

  private T food;

  public T getFood() {
    return food;
  }

  public void setFood(T food) {
    this.food = food;
  }
}
```

The generated yaml (excerpt) is:

```
...
components:
  schemas:
    DryFood:
      type: object
      allOf:
      - $ref: '#/components/schemas/Food'
    Food:
      type: object
    Food1:
      type: object
    Pet:
      type: object
      properties:
        food:
          $ref: '#/components/schemas/Food1'
```

It seems that using the generic class Pet, SmallRye generates an additional DTO. One for the extended type Food in class DryFood and one for the generic in class Pet. As soon as I remove the `<T extends Food>` and adjust the Setter accordingly, the OpenAPI YAML is generated correctly. Is this a bug or is it intended behaviour for some reason?

**Comment by MikeEdgar** [comment]
Hi @jonsalvas - did you mean for the `Food` field in `Pet` to be type `T` instead? This seems like a bug, but I'm wondering if putting a `@Schema` on the `Food` class will help.

**Comment by jonsalvas** [comment]
yep, sorry corrected this. And putting @Schema on Food class did not do the trick, unfortunately.

**Comment by MikeEdgar** [comment]
@jonsalvas - is the `Pet` class referenced from another bean or a REST resource where `T` is given as `DryFood` (or another type)? It's unable to match up with the `Food` schema entry because `T extends Food` is not the same type as `Food`. Of course you can annotate the `food` field with `@Schema(implementation = Food.class)` to force it.

Also, you may want the schema for `DryFood` to instead be `@Schema(allOf = { Food.class, DryFood.class })`

**Comment by jonsalvas** [comment]
@MikeEdgar The hint with forcing the Schema-Class was worth a mint, thanks a lot!! :-) Now, the duplicate object disappeared.
Regarding your question: in the original code (the code above is of course only a simplified example) I had e.g. a Dog<Dryfood> that extends Pet<Food> and instead of referencing Dryfood in the Dog object, Smallrye pointed to the parent Food. I was only able to solve that by adding a getFood-Getter in the Dog class annotated with @Schema(implementation = DryFood.class). It works but is hacky. 

Are there plans to support Generics a little better in the future?

**Comment by MikeEdgar** [comment]
@jonsalvas - so you have `Dog extends Pet<DryFood>` or am I misunderstanding? As long as the type variables can be resolved (i.e. they are replaced with a type parameter somewhere, such as `Pet<DryFood>`), the scanner should fully support generics. There is certainly the possibility for edge cases that are missed though. If you still think there is a problem and are willing to provide a full example project that demonstrates the problem, I would like to have a look and get it resolved.

**Comment by jonsalvas** [comment]
yes exactly. I have created a full simplified example project to reproduce the issue:
https://github.com/jonsalvas/smallrye-generics-issue-example
I use the smallrye maven plugin to generate the spec.

As you can see in the example Dog extends from Pet<DryFood>, however smallrye generates the Dog class by referencing Food instead of Dryfood:

```
Dog:
      type: object
      properties:
        food:
          $ref: '#/components/schemas/Food'
```

To reproduce the original issue (described above), 
1. remove the `@Schema(implementation = Food.class)`from Pet class 
2. and change Dog to Pet in PetResource
which should produce the Food1 object in the spec.

**Comment by MikeEdgar** [comment]
> change Dog to Pet in PetResource

When you specify `Pet` in the resource class, is any type parameter given? E.g. `Pet<Food>`, `Pet<DryFood>`, or `Pet<?>` ?

**Comment by jonsalvas** [comment]
no indeed just Pet, good point. But if I specify Pet<DryFood> as Type parameter in the resource class I get "PetDryFood" as type in the spec.

**Comment by MikeEdgar** [comment]
@jonsalvas, suppose you want to use `Pet` (raw) or `Pet<?>` in your resource class. What would you expect your output to be? I think `Pet<SomeTypeOfFood>` will likely need to be a different type from whatever `Pet<?>` would generate since the type of `food` is known for one and not the other (or at least not a single value is known if there are multiple types of `Food`). I can imagine having `food` generate a schema with `oneOf`, listing all the types of `Food`, but that might be overkill for most use cases.

**Comment by jonsalvas** [comment]
@MikeEdgar sorry for answering so late, I've been busy with other things.. Yea, I agree that the "issue" in my last comment is expected behaviour, because the generator cannot really know which possible types of Pets eating DryFood exist (or at least it is not trivial to determine). So specifying the specific class in the resource is obviously mandatory, which however has the disadvantage that you cannot have polymorphic resources. So for instance you would need one resource for each specific Pet. 

I start to think whether generics in general is not a bad idea to use in DTO's. Especially, because when generating the clients with openapi-generator, the generics signature is of course lost as the idea of generics is not existent in openapi anyway..At least the `oneOf` option you suggested sounds like a way to support this in a certain way.

**Comment by MikeEdgar** [comment]
@jonsalvas - just doing a follow-up on this one and I want to make sure you've been able to get the output you need/expect. Let me know if there is still anything open on your side or feel free to close this issue. If I don't hear back, I'll close later this week.

**Comment by Felk** [comment]
I encountered a similar (or maybe even the exact same) issue, namely smallrye generating a base class twice if it is used in generics. The smallest example I could come up with looks like this:

```java
class Base { String baseField; }

@Schema(allOf = Base.class)
class Foo extends Base { String fooField; }

class Wrapper<T extends Base> {
    public String nongenericWrapperField;
    public T genericWrappingField;
}

@Schema(allOf = Wrapper.class)
class WrapperFoo extends Wrapper<Foo> { String wrapperFooField; }
```

And the generated schema looks like this:
```json
{
  "Base": {
    "type": "object",
    "properties": {
      "baseField": {"type": "string"}
    }
  },
  "Base1": {
    "type": "object",
    "properties": {
      "baseField": {"type": "string"}
    }
  },
  "Foo": {
    "type": "object",
    "allOf": [{"$ref": "#/components/schemas/Base"}],
    "properties": {
      "fooField": {"type": "string"}
    }
  },
  "Wrapper": {
    "type": "object",
    "properties": {
      "nongenericWrapperField": {"type": "string"},
      "genericWrappingField": {"$ref": "#/components/schemas/Base1"}
    }
  },
  "WrapperFoo": {
    "type": "object",
    "allOf": [{"$ref": "#/components/schemas/Wrapper"}],
    "properties": {
      "wrapperFooField": {"type": "string"}
    }
  }
}
```

`Base` is duplicated as `Base1`, with the additional problem that `WrapperFoo` no longer contains `Foo`, but `Base1` and therefore does not contain `fooField`.

A suitable workaround seems to be to just never express an `allOf` relationship to a generic type, and instead extract all common, non-generic fields to a non-generic base class, and have the generic class' field just be inlined into the concrete type:

```java
class Base { String baseField; }

@Schema(allOf = Base.class)
class Foo extends Base { String fooField; }

class WrapperNonGeneric { public String nongenericWrapperField; }
class Wrapper<T extends Base> extends WrapperNonGeneric { public T genericWrappingField; }

@Schema(allOf = WrapperNonGeneric.class)
class WrapperFoo extends Wrapper<Foo> { String wrapperFooField; }
```

which produces a workable schema:

```json
{
  "Base": {
    "type": "object",
    "properties": {
      "baseField": {"type": "string"}
    }
  },
  "Foo": {
    "type": "object",
    "allOf": [{"$ref": "#/components/schemas/Base"}],
    "properties": {
      "fooField": {"type": "string"}
    }
  },
  "WrapperFoo": {
    "type": "object",
    "allOf": [{"$ref": "#/components/schemas/WrapperNonGeneric"}],
    "properties": {
      "genericWrappingField": {"$ref": "#/components/schemas/Foo"},
      "wrapperFooField": {"type": "string"}
    }
  },
  "WrapperNonGeneric": {
    "type": "object",
    "properties": {
      "nongenericWrapperField": {"type": "string"}
    }
  }
}
```

**Comment by MikeEdgar** [comment]
Thank you for the example @Felk , I'll take a look.

**Comment by MikeEdgar** [comment]
@Felk - I looked at your example a bit more and indeed using a generic type in an `allOf` (or any other location where a class constant for a class with type arguments is used without type parameters) forces the scanner to lose the type parameter information. Your solution to extract properties you'd like to re-use to a non-generic type is (I believe) the correct approach.

Closing this issue for now, but please comment if you think there is a bug with this.
