### ISSUE TITLE
operationId auto generation fails for inheritance

### ISSUE THREAD

**Issue by codegourmet** [smallrye/smallrye-open-api#819]
When I use `CLASS_METHOD` as operationId generation strategy, and my resource implements an interface, the interface name is used for operationId instead of the concrete jaxrs resource class's name.

So, in the case of

`GreetingInterface` -> `GreetingResource`

it should generate: `operationId: GreetingResource_hello`,
but it does: `operationId: GreetingInterface_hello`

This is a problem since when I have for example

`GreetingResourceA implements GreetingInterface`
`GreetingResourceB implements GreetingInterface`

I will get duplicate operationId errors when generating a client (`GreetingInterface_hello`, `GreetingInterface_hello`).

My concrete use case is an annotated interface (and implementation) for basic CRUD operations so I don't need to repeat them for each model.

I tried to do some digging and testing, but couldn't get the existing unit test to pick up my example resource (result was always empty).

Here is the implementation and the test in the smallrye-openapi code:

https://github.com/smallrye/smallrye-open-api/blob/main/core/src/main/java/io/smallrye/openapi/runtime/io/operation/OperationReader.java#L145

https://github.com/smallrye/smallrye-open-api/blob/main/extension-jaxrs/src/test/java/io/smallrye/openapi/runtime/scanner/OperationIdTest.java

Here are an example and a link to a quarkus example project.

Example:

```java
public interface GreetingInterface {

    @GET
    public String hello();

}
```

```java
@Path("/hello")
public class GreetingResource implements GreetingInterface {

    public String hello() {
        return "Hello RESTEasy";
    }

}
```

Result:
```json
---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /hello:
    get:
      operationId: GreetingInterface_hello
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
```

expected: `operationId: GreetingResource_hello`
actual: `operationId: GreetingInterface_hello`

Example Repo URL: https://github.com/codegourmet/openapi-operationid-example

**Comment by phillip-kruger** [comment]
Hi @codegourmet 

I will look at this a.s.a.p. If you have an idea how to fix this, PR's are welcome :)

**Comment by MikeEdgar** [comment]
I can take a look.

**Comment by codegourmet** [comment]
You guys are absolutely fantastic.
