### ISSUE TITLE
How to post list of files?

### ISSUE THREAD

**Issue by deepfunction** [smallrye/smallrye-open-api#857]
I try to post body with object and list of files.
![1](https://user-images.githubusercontent.com/48287188/126158045-ce9d0b15-23c1-4434-84a4-22e088f42e00.jpg)
![2](https://user-images.githubusercontent.com/48287188/126158134-a1bce558-9b45-4600-a01b-2ad314bdd1ae.jpg)
And what i see in the swagger ui.
![3](https://user-images.githubusercontent.com/48287188/126158168-79d6a0a4-763e-4f20-be37-19eb587a5f82.jpg)
So, how to create something like this
![4](https://user-images.githubusercontent.com/48287188/126158331-828835dc-572c-47c6-b471-9d4829ffb119.jpg)

**Comment by MikeEdgar** [comment]
@deepfunction - does using a `List` of `File`s actually work at runtime? Did you try a list of `InputStream` or `byte[]` ? I think this will require a change to the scanner.
