### ISSUE TITLE
Generated OpenAPI schema with @Schema(anyOf={...}) for array types seems to be wrong

### ISSUE THREAD

**Issue by thake** [smallrye/smallrye-open-api#889]
Consider the following model:
```java
@Schema
class Foo {
  @Schema(anyOf = {Bar.class})
  List<Object> bars;
}
@Schema
class Bar {
}
```

generated the following OpenAPI spec:
```yaml
---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths: {}
components:
  schemas:
    Bar:
      type: object
    Foo:
      type: object
      properties:
        bars:
          type: array
          items: {}
          anyOf:
          - $ref: '#/components/schemas/Bar'
```

This seems to be incorrect to me, because the schema of the bars property is an array and an anyOf type. I would expect the following schema to be generated for the bars property:
```yaml
bars:
  type: array
  items: 
    anyOf: 
      - $ref: '#/components/schemas/Bar'
```

**Comment by thake** [comment]
@MikeEdgar thanks for your fast response. Thanks for the hint to OASFilter. Actually, I'm already using it to work around this issue. Do you know a way to generate this kind of schema without an OASFilter? Using OASFilter for rather usual situations (e.g. the list could be of a sealed interface type) seems to be not ideal.

I will try to raise an issue in the spec project to address the need for `@Schema`-Annotations on generic types.

**Comment by MikeEdgar** [comment]
@thake , you could introduce an object used just for the `items` of the `bars` list.
```java
@Schema
class Bar {
}

@Schema(anyOf = { Bar.class })
class BarItems {
}

@Schema
class Foo {
@Schema(implementation = BarItems[].class)
    List<Object> bars;
}
```

**Comment by thake** [comment]
@MikeEdgar thanks for your help! This seems like a better alternative.
