### ISSUE TITLE
IndexHtmlCreator generated incorrect OAuth2 code

### ISSUE THREAD

**Issue by stuartwdouglas** [smallrye/smallrye-open-api#894]
`initOAuth` is a function on `SwaggerUIBundle`, so the generated code needs to be moved after the `SwaggerUIBundle` is created, and the call changed to `window.ui.initOAuth` instead of `ui.initOAuth`.

**Comment by phillip-kruger** [comment]
Already fixed :) see https://github.com/smallrye/smallrye-open-api/pull/887
Waiting on a release.
