### ISSUE TITLE
The absence of annotation confuses openapi/swagger

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-open-api#896]
With resteasy reactive, you can omit some annotations.
For example, the following endpoint is valid:

```
@GET
@Path("/{id}")
public Response getOne(long id) {
    Movie movie = Movie.findById(id);
    if (movie == null) {
        return Response.status(404).build();
    } else {
        return Response.ok(movie).build();
    }
}
```

However, it confuses openapi/swagger and we can't invoke it from the Quarkus dev console:

![image](https://user-images.githubusercontent.com/402301/131792330-5b57e416-93ea-4387-be68-50d1542dc42e.png)

**Comment by cescoffier** [comment]
CC @phillip-kruger @geoand

**Comment by phillip-kruger** [comment]
We will have to add support for that in openapi. At the moment it will assume that is the body

**Comment by MikeEdgar** [comment]
This is definitely a bug. There are unit tests specifically for this.

**Comment by phillip-kruger** [comment]
So the problem is not that it did not create the path param, that actually worked (see below). The problem is that it also added the response body for that param, and that should be omitted.

```
/movies/{id}:
    get:
      tags:
      - Movie Resource
      parameters:
      - name: id
        in: path
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              format: int64
              type: integer
      responses:
        "200":
          description: OK
```

**Comment by phillip-kruger** [comment]
mmm, I can not recreate this in our tests in SmallRye....

**Comment by phillip-kruger** [comment]
Here the test in SmallRye, seems ok https://github.com/smallrye/smallrye-open-api/pull/899

I am still trying to recreate this.
