### ISSUE TITLE
Warning SROAP04005 logged when using Uni<Void>as return method of rest client interface

### ISSUE THREAD

**Issue by mswiderski** [smallrye/smallrye-open-api#914]
When using rest-client-reactive (quarkus extension) that uses following method on the interface

````
    @POST
    @Path("/name/{countryName}")
    Uni<Void> createCountry(String countryName);
````

with OpenAPI extension in the project, following warning is logged

````
SROAP04005: Could not find schema class in index: java.lang.Void

````
There is no observed lost in functionality but it scans the REST client interface and complains about the types there.

**Comment by phillip-kruger** [comment]
Thanks @mswiderski  ! We will fix a.s.a.p

**Comment by mswiderski** [comment]
thanks for fast fix on this!
