### ISSUE TITLE
Not hiding RestClient operations

### ISSUE THREAD

**Issue by phillip-kruger** [smallrye/smallrye-open-api#915]
see https://github.com/geoand/quarkus-java17-demo/pull/1

**Comment by phillip-kruger** [comment]
Investigation points to the reactive libraries, switching to the non-reactive libraries (for Server and client) this works. @MikeEdgar any idea ?

**Comment by MikeEdgar** [comment]
@phillip-kruger - do the reactive libraries somehow provide implementations for the client interface? The scanner ignores any interfaces without a concrete implementation unless the interface is listed via an `mp.` include property.

**Comment by phillip-kruger** [comment]
Aaa, ok I am not sure about that, but would it not be safer to ignore if the interface is annotated with `@RegisterRestClient` ?

**Comment by MikeEdgar** [comment]
We had that but made it to work more broadly. There was an old issue where (I think) it was adjusted to support some multi-module project scenario.

**Comment by MikeEdgar** [comment]
Issue #449 has the history of this. There were two PRs to fix it, ultimately doing away with checking `@RegisterRestClient` directly.

**Comment by phillip-kruger** [comment]
Thanks @MikeEdgar - I am still unsure how this works for Non-Reactive, but not for reactive ?

**Comment by MikeEdgar** [comment]
Total guess, but maybe reactive generates some sort of implementation for the client.

**Comment by phillip-kruger** [comment]
that could be. Should we not always ignore when @RegisterRestClient is on the class first, before the other logic kicks in ?

**Comment by MikeEdgar** [comment]
Possibly, but I think there will impact what was done for #449. Let me take a look at the same app you linked and see why it's not being hidden. If there is a generated class, maybe there is something about it that will indicate it can be ignored.

**Comment by phillip-kruger** [comment]
Ok thanks :)
