### ISSUE TITLE
maven-plugin make it easier to scan dependend schemas

### ISSUE THREAD

**Issue by Postremus** [smallrye/smallrye-open-api#952]
I want to create multiple openapi schemas from the same maven module.
One of the schemas is for public consumption, the other one is internal.

My source tree looks like this:
![image](https://user-images.githubusercontent.com/1223135/140271604-cb0bed22-c546-4102-aecd-8c2b72e08824.png)

For the internal schema, I just define `<scanPackages>^org.acme</scanPackages>`. All of the classes needed are found.
For the public schema, I have to define `<scanPackages>^org.acme.pub|org.acme.model</scanPackages>`. 
Otherwise only the resources in org.acme.pub are found, and I would get following warning:
[INFO] --- smallrye-open-api-maven-plugin:2.1.15:generate-schema (public-openapi) @ sroa-maven-plugin ---
Nov. 04, 2021 8:08:52 VORM. io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner process
WARN: SROAP04005: Could not find schema class in index: org.acme.model.SomeModel

This is only a simplified example of my source tree. In my real project, I have the model classes sometimes in different artifacts (e.g. enums), which would quickly make this configuration unreadable.

Is there any way to only specifiy the location of the resource classes `org.acme.pub`, and let the maven plugin figure out all dependend schemas itself?

Reproducer project:
[sroa-maven-plugin.zip](https://github.com/smallrye/smallrye-open-api/files/7472919/sroa-maven-plugin.zip)

**Comment by Postremus** [comment]
@phillip-kruger Please assign to me, I want to work on this next.

**Comment by phillip-kruger** [comment]
Thanks !
