### ISSUE TITLE
Schemas generated from scanned objects missing type="object"

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-open-api#96]
I am doing some work on #73 and I noticed that schema entries generated from scanned objects are missing the "type": "object" attribute in the resulting document. From what I have read, it seems that omission of the type technically results in the schema being very permissive, which I do not think is desired in this scenario.

What are the thoughts of the development team on having the annotation scan process also generate a type attribute on object schemas added to the components list? Changing the process to generate it would result in breakage for several unit tests which would need to be adjusted as a result.

**Comment by EricWittmann** [comment]
I definitely think that adding the type property makes sense, unless it breaks the TCK.

**Comment by MikeEdgar** [comment]
Fixed by #97.
