### ISSUE TITLE
SmallRye config and MP OpenAPI Subsystem Configuration

### ISSUE THREAD

**Issue by Cakmakli-a** [smallrye/smallrye-open-api#975]
Hello, 

i read [MP OpenAPI Subsystem Configuration](https://github.com/wildfly/wildfly/blob/main/docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_OpenAPI.adoc) but nevertheless have some questions related to the config file
`microprofile-config.properties`.

```
mp.openapi.extensions.enabled=true
mp.openapi.extensions.path=/rest-demo/rest/openapi
mp.openapi.scan.packages=de.rest.server
mp.openapi.scan.classes=de.rest.server.RestFullWirr
mp.openapi.extensions.servers.relative=false

openapi.ui.contextRoot=/rest-demo/
openapi.ui.yamlUrl=/rest-demo/rest/openapi
openapi.ui.exploreFormVisibility=visible
openapi.ui.title=Test the rest endpoint
openapi.ui.swaggerUiTheme=muted
```

i'm not sure with this two entries and not sure what is expected.
* mp.openapi.extensions.path
* openapi.ui.contextRoot

contextRoot is equal to web context ?
how to handle a rest activator like "rest" ?

greetings
cakmakli

**Comment by phillip-kruger** [comment]
@Cakmakli-a what runtime are you using ? And if you are using [openapi](https://github.com/microprofile-extensions/openapi-ext) is that to get swagger-ui ?
