### ISSUE TITLE
Does not include properties annotated with @JsonbTransient in schema

### ISSUE THREAD

**Issue by vanuatoo** [smallrye/smallrye-open-api#982]
In our projects we use JAX-RS, JSON-B and BeanValidation
When programming POST requests we usually transmit Entity object directly which usually has id field.
For security purposes we set @JsonbTransient on setId method.

Generated UI shows that you can pass id key to the POST request body. It would be nice to hide that field.

**Comment by phillip-kruger** [comment]
Do you have a small reproducer we can look at ?

**Comment by vanuatoo** [comment]
I can upload Quarkus project. Is it OK?

**Comment by MikeEdgar** [comment]
That's perfect, thanks.

**Comment by vanuatoo** [comment]
Here is the project

https://github.com/vanuatoo/smallrye

Run the project by running
./mvnw quarkus:dev

And access swagger-ui in the browser by browsing:
http://localhost:8080/q/swagger-ui
